Grayscaled Alarm and Status Display Icons
NebulaSS13/Nebula pull request #1022
Opened 2020-12-12 10:30 UTC by Andromeda-K22

This PR changes fire alarms and status displays to using greyscaled icons instead of static icons. Included are a handful I whipped up, so this should allow for an easier variety of code displays.

2020-12-12 10:34 UTC, MistakeNot4892 commented on code/datums/security_state.dm
> +	alarm_appearance = new alarm_appearance_type
Need to typecheck this in case it's null, since the default value is null.

2020-12-20 16:17 UTC, MistakeNot4892 requested changes
Please rebase and squash this, then I will approve it for merge.

2020-12-20 17:01 UTC, MistakeNot4892 approved these changes
If I was a cruel man I'd go :eyes: at the fix commit.

2020-12-20 17:02 UTC, Andromeda-K22 commented
🔪

2020-12-21 14:48 UTC, merged