SQL based notes panel
NebulaSS13/Nebula pull request #1285
Opened 2021-02-06 23:27 UTC by eckff

2021-02-07 00:21 UTC, Andrew-Fall requested changes
SQL needs backticks

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +		var/DBQuery/query_find_ckey = dbcon.NewQuery("SELECT ckey FROM erro_player WHERE ckey = '[new_ckey]'")
Needs backticks for columns and tables
dbcon.NewQuery("SELECT \`ckey\` FROM \`erro_player\` WHERE \`ckey\` = '[new_ckey]'")

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +	var/DBQuery/query_noteadd = dbcon.NewQuery("INSERT INTO erro_messages (type, targetckey, adminckey, text, timestamp, server) VALUES ('note', '[target_sql_ckey]', '[admin_sql_ckey]', '[notetext]', '[
dbcon.NewQuery("INSERT INTO \`erro_messages\` (\`type\`, \`targetckey\`, \`adminckey\`, \`text\`, \`timestamp\`, \`server\`) VALUES ('note', '[target_sql_ckey]', '[admin_sql_ckey]', '[notetext]', '[timestamp]', '[server]')")

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +	var/DBQuery/query_find_note_del = dbcon.NewQuery("SELECT targetckey, text, adminckey FROM erro_messages WHERE id = [note_id] and type = 'note'")
dbcon.NewQuery("SELECT \`targetckey\`, \`text\`, \`adminckey\` FROM \`erro_messages\` WHERE \`id\` = [note_id] and \`type\` = 'note'")

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +	var/DBQuery/query_del_note = dbcon.NewQuery("DELETE FROM erro_messages WHERE id = [note_id]")
dbcon.NewQuery("DELETE FROM \`erro_messages\` WHERE \`id\` = [note_id]")

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +	var/DBQuery/query_find_note_edit = dbcon.NewQuery("SELECT targetckey, text, adminckey FROM erro_messages WHERE id = [note_id] and type = 'note'")
dbcon.NewQuery("SELECT \`targetckey\`, \`text\`, \`adminckey\` FROM \`erro_messages\` WHERE \`id\` = [note_id] and \`type\` = 'note'")

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +		var/DBQuery/query_update_note = dbcon.NewQuery("UPDATE erro_messages SET text = '[new_note]', lasteditor = '[sql_ckey]', edits = CONCAT(IFNULL(edits,''),'[edit_text]') WHERE id = [note_id]")
Backticks

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +		var/DBQuery/query_get_notes = dbcon.NewQuery("SELECT id, timestamp, text, adminckey, lasteditor, server FROM erro_messages WHERE targetckey = '[target_sql_ckey]' and type = 'note' ORDER BY timestam
Backticks

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/sql_notes.dm
> +		var/DBQuery/query_list_notes = dbcon.NewQuery("SELECT DISTINCT targetckey FROM erro_messages WHERE targetckey REGEXP '[search]' ORDER BY targetckey")
Backticks

2021-02-07 00:21 UTC, Andrew-Fall commented on code/modules/admin/topic.dm
> +		var/DBQuery/query_noteedits = dbcon.NewQuery("SELECT edits FROM erro_messages WHERE id = '[note_id]'")
Backticks

2021-02-07 01:14 UTC, Andrew-Fall submitted a review, later dismissed

2021-02-07 11:22 UTC, eckff commented
Require help with testing. Unable to test locally.

2021-02-07 12:50 UTC, eckff commented
Reconverting from draft for review. DNM till we don't test this.

2021-02-08 03:29 UTC, MistakeNot4892 commented on code/modules/admin/sql_notes.dm
> +	if(!dbcon.IsConnected())
`!dbcon?.IsConnected`

2021-02-08 03:29 UTC, MistakeNot4892 commented on code/modules/admin/sql_notes.dm
> +		to_chat(usr, "<span class='danger'>Failed to establish database connection.</span>")
`SPAN_WARNING`

2021-02-08 03:47 UTC, MistakeNot4892 commented on code/modules/admin/sql_notes.dm
> +	if(!dbcon.IsConnected())
nvm

2021-04-13 09:28 UTC, MistakeNot4892 commented
I keep forgetting this exists  but it's now two weeks stale and last update was that it needed testing with a MySQL server before being mergable, so feel free to reopen when it has been tested. I don't have any experience using MySQL and no access to an instance so can't really offer to test it myself. Could possibly ask Lohi nicely?

2021-04-13 09:28 UTC, closed without merging