Brains refactoring.
NebulaSS13/Nebula pull request #1302
Opened 2021-02-09 05:22 UTC by MistakeNot4892

- Repaths brains from carbon to living.
- Deletes a bunch of brain environmental processing. Brains are an organ, and organs die on their own regardless; might as well let the mob take state from the brain instead of handling it separately.
- Reworks some MMI and brainmob code - MMIs use the held brain's brainmob instead of maintaining a second one to bounce client mind around with.

**TODO:**
- Map brain organ state to the brainmob for death etc.
- Possibly condense posibrains into regular brains instead of having them be their own subtype with all their own handling.
- Kill MMI holders or make them also a regular brain with some extra handling; at the moment they are an organ holding an item holding an organ holding a brainmob.
- Test everything.

2021-02-09 07:01 UTC, eckff requested changes

2021-02-09 07:01 UTC, eckff commented on code/modules/mob/living/carbon/brain/MMI.dm
> +	to_chat(user, SPAN_NOTICE("You upend \the [src], spilling \the [holding_brain] onto \the [get_turf(src)]."))
`You open`

2021-02-09 07:01 UTC, eckff commented on code/modules/mob/living/carbon/brain/MMI.dm
> +		to_chat(user, SPAN_WARNING("You upend \the [src], but the case is locked shut."))
`You open`

2021-02-09 07:01 UTC, eckff commented on code/modules/mob/living/carbon/brain/MMI.dm
> +		to_chat(user, SPAN_WARNING("You upend \the [src], but there's nothing in it."))
`You open`

2021-02-12 07:39 UTC, MistakeNot4892 commented
This has spun off into a refactor of laws as well, no idea when it'll be finished. God help me.

2021-02-12 07:44 UTC, MistakeNot4892 commented on code/_onclick/hud/ai.dm
> -	adding += new /obj/screen/ai_button(null,
TODO readd

2021-06-30 07:04 UTC, MistakeNot4892 commented
Will reopen this when I get back to it.

2021-07-01 04:12 UTC, closed without merging