Wide-scale MMI and brainmob refactor.
NebulaSS13/Nebula pull request #1447
Opened 2021-03-08 11:42 UTC by MistakeNot4892

- Repaths brains from carbon to living.
- Deletes a bunch of brain environmental processing. Brains are an organ, and organs die on their own regardless; might as well let the mob take state from the brain instead of handling it separately.
- Reworks ~~some~~ all MMI and brainmob code - MMIs use the held brain's brainmob instead of maintaining a second one to bounce client mind around with.
- Collapses the positronic brain into the digital MMI subtype.

**TODO:**
- [x] Map brain organ state to the brainmob for death etc.
- [x] Readd the system reboot loop to MMIs.
- [x] Readd visual disruption from a damaged MMI.
- [x] Possibly condense posibrains into regular brains instead of having them be their own subtype with all their own handling.
- [ ] Finish ripping all the brain stuff out of the laws PR and put it into this PR.
- [ ] Test everything.

2021-03-29 04:55 UTC, MistakeNot4892 commented
This is pretty close to done, just need to fix an issue with the MMI deleting itself on removal.

2021-07-20 10:45 UTC, MistakeNot4892 commented
Will reopen when this is mergeable.

2021-08-09 06:36 UTC, MistakeNot4892 commented
This appears to be functionally working so ready for review, just has some small stuff to fix.

2021-11-14 11:42 UTC, MistakeNot4892 commented
Note to self to uodate/reteat.

2021-12-23 09:46 UTC, MistakeNot4892 commented
Not going to get this properly tested and working.

2022-11-02 11:06 UTC, MistakeNot4892 commented
Ended up completely reworking this, oops.

2022-11-03 23:15 UTC, out-of-phaze requested changes
Preliminary review to try to get this to pass tests.

2022-11-03 23:15 UTC, out-of-phaze commented on code/modules/mob/living/silicon/robot/component.dm
> +// TODO: remove the robot.brain and robot.cell variables and completely rely on the robot component system
isn't that var named `central_processor` now?

2022-11-03 23:15 UTC, out-of-phaze commented on code/modules/organs/internal/brain.dm
> +	initialize_brain()
Should this be here? Before, brainmobs were only made in `transfer_identity`; it looks like this is why tests are failing, and besides, `create_if_missing` is used in the new equivalent of the `transfer_identity` proc. Why is it necessary to forcibly create a brainmob here, which has to register to its parent + creates a virtual mob + may cause all other sorts of mayhem?

2022-11-03 23:57 UTC, MistakeNot4892 commented on code/modules/organs/internal/brain.dm
> +	initialize_brain()
Renaming `initialize_brain()` to `initialize_brainmob()` and calling it instead of `_brainmob = new` in `get_brainmob()`

2022-11-03 23:58 UTC, MistakeNot4892 commented on code/modules/mob/living/silicon/robot/component.dm
> +// TODO: remove the robot.brain and robot.cell variables and completely rely on the robot component system
For reference I did a mass rename of `mmi` to `brain` then `brain` to `central_processor` so there'll be places I missed yeah.

2022-11-10 15:19 UTC, out-of-phaze requested changes, later dismissed
Repeating the issue from the Discord so it can't get forgotten/lost:

Brainmob transfer isn't happening with decapitation because it relies on `organ/proc/on_remove_effects`, which is called in `mob/living/proc/on_lost_organ`, which is called in `mob/living/proc/remove_organ`... but not in `organ/proc/do_uninstall`.

When a body part is dismembered, it has `remove_organ` called, which calls `on_lost_organ` on the dismembered limb, but then calls `do_uninstall` to remove its child organs, so they never have `on_lost_organ` or `on_remove_effects` called. The way to solve this is to, well... fix that. Reorder the call chain to be consistent with removal effects.

2022-11-10 15:19 UTC, out-of-phaze commented on code/modules/organs/internal/brain.dm
> +	var/VAR_PRIVATE/mob/living/_brainmob = /mob/living/brain
```suggestion
	VAR_PRIVATE/mob/living/_brainmob = /mob/living/brain
```

2022-11-11 02:00 UTC, PsyCommando commented on code/modules/organs/external/head.dm
> +	if(owner && (glowing_eyes || owner.has_chemical_effect(CE_GLOWINGEYES, 1)))
This means the glowing eyes effect won't show on decapitated heads, no?

2022-11-12 12:20 UTC, MistakeNot4892 commented
Issue with detachment turned out to be gating the transfer procs behind `get_brainmob()` after making it lazy, appears to be working now.

2022-11-12 12:20 UTC, MistakeNot4892 commented on code/modules/organs/external/head.dm
> +	if(owner && (glowing_eyes || owner.has_chemical_effect(CE_GLOWINGEYES, 1)))
Fixed.

2022-11-12 12:20 UTC, MistakeNot4892 commented on code/modules/organs/internal/brain.dm
> +	var/VAR_PRIVATE/mob/living/_brainmob = /mob/living/brain
Fixed.

2022-11-12 12:21 UTC, MistakeNot4892 commented on code/controllers/subsystems/initialization/robots.dm
>  	var/list/mob_types_by_title = list(
This system needs declification to be modpack compatible, leaving a note for myself. May move shackle reimplementation into that system too.

2022-11-12 12:33 UTC, MistakeNot4892 commented
Depends on #2811 #2812 #2815 and #2794.

2022-11-12 16:12 UTC, MistakeNot4892 commented
Summary for future me when I've slept:
- Prosthetics do not set detached on removal for reasons that entirely escape me. This prevents set_detached() from being used as the brainmob transfer point.
- Heads move their internal organs into implants/detach them on removal and do not move them back on reattachment.

2023-08-17 08:05 UTC, MistakeNot4892 commented
Noting the brain appeared to not have owner set when reinstalled.

2024-01-05 10:56 UTC, out-of-phaze commented
Also seems to rename "positronic brain" to "computer intelligence core"?

2024-01-05 12:43 UTC, MistakeNot4892 commented
Right, yes. I remember now.
- Rename was to remove the positronics lore inherited from Bay along with the BP_POSIBRAIN and /mob/silicon/posimob or whatever it was. Lore-agnostic codebase etc. It should be straightforward for servers that want to make them positronics or readd a distinction between robots and positronics to make a subtype or change the lore strings. The icons are all still the same posibrains iirc.
- `/obj/item/organ/internal/brain/robotic` is separate from `brain_interface` because it doesn't need any of the additional logic that comes with the brain interface. The interface object that existed previously for posibrains/MMIs was solely because the MMI/posibrain wasn't an organ and had to have a wrapper.

2024-01-13 19:03 UTC, out-of-phaze approved these changes, later dismissed

2024-01-15 09:25 UTC, out-of-phaze submitted a review, later dismissed

2024-01-18 12:17 UTC, out-of-phaze submitted a review, later dismissed

2024-01-20 13:59 UTC, out-of-phaze submitted a review, later dismissed

2024-01-21 12:21 UTC, out-of-phaze approved these changes, later dismissed

2024-01-24 14:33 UTC, out-of-phaze approved these changes

2024-01-25 15:05 UTC, merged