Added ore lists to strata.
NebulaSS13/Nebula pull request #1561
Opened 2021-04-21 15:57 UTC by MistakeNot4892

- Exoplanets now select a strata based on their ambient temperature. This logic can stand to be made more interesting in the future.
- Strata now contain an ore list and autogenerate weights based on the material decls in the list at compile time.

2021-04-22 11:15 UTC, comma submitted a review, later dismissed

2021-04-22 23:36 UTC, afterthought2 requested changes

2021-04-22 23:36 UTC, afterthought2 commented on code/controllers/subsystems/initialization/materials.dm
> +var/warned_two
Debug code?

2021-04-23 21:24 UTC, afterthought2 approved these changes

2021-04-23 21:28 UTC, merged