ports visual filter helpers from polaris
NebulaSS13/Nebula pull request #1711
Opened 2021-05-30 13:09 UTC by Andromeda-K22

dependency for #1710 also generally useful to use filters in more places for pretty things ™️

2021-05-30 13:11 UTC, MistakeNot4892 approved these changes, later dismissed

2021-05-31 00:54 UTC, Lohikar commented
I feel like this should hook into Z-Mimic as well, an `UPDATE_OO_IF_PRESENT` in `update_filters()` would probably work.

2021-05-31 00:55 UTC, Lohikar requested changes
This should hook into Z-Mimic as well, an UPDATE_OO_IF_PRESENT in update_filters() would probably be all that you need to do.

2021-05-31 00:57 UTC, Lohikar commented
Though handling animating filters for mimics might be more involved, and is something that #1710 probably will need.

2021-05-31 02:11 UTC, Lohikar approved these changes

2021-05-31 02:28 UTC, merged