Converts world/Topic commands to an extensible decl format.
NebulaSS13/Nebula pull request #1749
Opened 2021-06-21 14:31 UTC by MarinaGryphon

- Converts world/Topic commands to an extensible decl format.
  - There is now an option to make localhost world/Topic() requests (from TGS or local scripts) immune to throttling.

This is so that downstreams/modpacks can add their own Topic() commands. For example, the psionics modpack could add a Topic() command to let admins view all active psions without having to edit core game files.

2021-06-22 02:15 UTC, quardbreak requested changes

2021-06-22 02:15 UTC, quardbreak commented on code/game/world_topic_commands.dm
> +	for(var/mob/M in global.player_list)
ayy lmao legacy code
the entire thing can be replaced with `global.clients || 0`

2021-06-22 22:42 UTC, MistakeNot4892 commented on code/game/world.dm
> +	var/command_key = params[1]
This will runtime if the params are malformed.

2021-06-23 01:03 UTC, MarinaGryphon commented on code/game/world.dm
> +	var/list/params = params2list(T)
```suggestion
	var/list/params = params2list(T)
	if(!params)
		return
```

2021-06-23 01:16 UTC, MarinaGryphon commented on code/game/world.dm
> +	if(!params)
```suggestion
	if(!length(params))
```
i am too coddled by assoc lists

2021-06-23 01:24 UTC, Lohikar commented on html/changelogs/MDP-declify-topic.yml
> +changes:
No changelogs for backend changes please.

2021-06-23 01:24 UTC, Lohikar commented on config/example/config.txt
> +#THROTTLE_IMMUNE_LOCALHOST
`NO_THROTTLE_LOCALHOST` would probably be less awkward.

2021-06-23 01:24 UTC, Lohikar commented on code/game/world_topic_commands.dm
> +/decl/topic_command/proc/can_use(var/T, var/addr, var/master, var/key)
As mentioned on discord, this should probably be renamed.

2021-06-23 11:50 UTC, MistakeNot4892 commented
This overall looks fine to me, will leave approval to @Lohikar but happy to merge after.

2021-06-26 04:31 UTC, Lohikar approved these changes
Looks fine to me.

2021-06-26 04:41 UTC, merged