implements a decl-based method for adding onto human/examine()
NebulaSS13/Nebula pull request #1768
Opened 2021-06-25 18:11 UTC by Andromeda-K22

implements /decl/human_examination - which is more or less just a stub proc so modpacks can add onto human/examine() without too much fuss.

2021-06-25 18:41 UTC, Techhead0 commented on code/modules/mob/living/carbon/human/examine.dm
> +			msg += adding_text
If you wanna optimize, you could compact this down to:
```
msg += HE.do_examine(user, distance, src) || null
```
But it doesn't really matter. (And the `|| null` is onlt there to keep it from adding "0" if a 0 is returned)

2021-06-25 21:59 UTC, MistakeNot4892 approved these changes, later dismissed

2021-06-27 23:22 UTC, Lohikar requested changes, later dismissed
Squash.

2021-06-28 10:26 UTC, MistakeNot4892 approved these changes

2021-06-29 21:42 UTC, merged