Fixes sonar pings.
NebulaSS13/Nebula pull request #1795
Opened 2021-06-30 06:14 UTC by MistakeNot4892

- Fixes #1793.
- Doesn't fix the sonar effect not being shown until you peek through the sensors console, unsure why.

2021-06-30 12:35 UTC, comma submitted a review, later dismissed

2021-07-01 00:06 UTC, Lohikar requested changes, later dismissed

2021-07-01 00:06 UTC, Lohikar commented on code/modules/overmap/contacts/_contacts.dm
> +	var/list/showing = (owner ? (owner.linked?.navigation_viewers || owner.viewers) : null)
This is awful to read. Please just split this into a regular if.

2021-07-01 00:06 UTC, Lohikar commented on code/modules/overmap/contacts/_contacts.dm
> +				M.client?.images |= images
You might as well lift this client null check into the istype above, bit clearer that way imo.

2021-07-01 00:06 UTC, Lohikar commented on code/modules/overmap/contacts/_contacts.dm
> +	var/list/showing = (owner ? (owner.linked?.navigation_viewers || owner.viewers) : null)
Ditto wrt: if

2021-07-01 22:25 UTC, afterthought2 approved these changes

2021-07-02 23:46 UTC, merged