switches the integrated maneuvering module to use it's own gas tank
NebulaSS13/Nebula pull request #1841
Opened 2021-07-07 02:55 UTC by Andromeda-K22

The maneuvering thrusters module for RIGs now uses it's own gas tank.

2021-07-07 08:49 UTC, quardbreak requested changes

2021-07-07 08:49 UTC, quardbreak commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	jets = null
`QDEL_NULL(jets)`

2021-07-07 09:49 UTC, MistakeNot4892 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	. = ..()
````
/obj/item/rig_module/maneuvering_jets/attackby(obj/item/W, mob/user)
  ...
  if(jets stuff)
    return TRUE
  . = ..()
  ````

2021-07-09 14:02 UTC, MistakeNot4892 submitted a review, later dismissed

2021-07-10 06:41 UTC, Andromeda-K22 commented
maybe going to cook up a custom sprite for the RIG jetpack so it's visually distinct

2021-07-11 02:33 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/tanks/jetpack.dm
> +	desc = "The 'manuvering' part of an Manuvering jets module for a hardsuit. You could ... probably use this standalone?"
Random uppercase M? Also `...` shouldn't have a space before it.

2021-07-11 22:21 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/tanks/jetpack.dm
> +	desc = "The 'manuvering' part of an Manuvering jets module for a hardsuit. You could ... probably use this standalone?"
Missed this yesterday sorry, `an maneuvering`.

2021-07-12 13:34 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/tanks/jetpack.dm
> +	desc = "The 'manuvering' part of an manuvering jets module for a hardsuit. You could... probably use this standalone?"
`an maneuvering`

2021-07-13 02:59 UTC, MistakeNot4892 approved these changes
Needs squashmerge.

2021-07-14 10:50 UTC, merged