Less weird light bulbs.
NebulaSS13/Nebula pull request #2133
Opened 2021-10-02 11:37 UTC by chaoko99

## Description of changes

Emissive light bulbs. The dream is to remove the light shaft and replace it with filters. That'd be cool.

## Why and what will this PR improve
Pretty lights with purer colors.

## Authorship
chaoko99 edit

## Changelog

:cl:
tweak: Light bulbs are emissive and color better.
/:cl:

2021-10-02 11:38 UTC, MistakeNot4892 commented
You committed your .dme and this was previously reverted in the past.

2021-10-02 11:42 UTC, MistakeNot4892 requested changes

2021-10-02 11:42 UTC, MistakeNot4892 commented on html/changelogs/AutoChangeLog-pr-2127.yml
> +  - imageadd: New combat shield sprite.
er

2021-10-02 11:43 UTC, chaoko99 commented
will make another attempt when I unfuck my branch stand by

2021-10-02 11:48 UTC, chaoko99 commented
branch unfucked

2021-10-03 01:05 UTC, chaoko99 commented
Scope of this PR has widened. Closing until I have something more concrete.

2021-10-03 01:05 UTC, closed without merging