ventcrawl: diagonal direction no longer breaks movement
NebulaSS13/Nebula pull request #2268
Opened 2021-12-27 11:25 UTC by quardbreak

## Description of changes
Strips diagonal directions on move.

## Why and what will this PR improve
Bugfix. Mobs should not leave pipes because of diagonal move.

## Authorship
https://github.com/ss220-space/Baystation12/pull/95

2021-12-27 21:34 UTC, afterthought2 commented
This doesn't really work: imagine you are on a 4-way manifold with simple pipes going north, south, east, west, and those are the only pipes on the map. From the manifold turf you call move northeast, which does not get stripped (north and east are initialize dirs because there is a pipe east and a pipe north), but there is no pipe to the northeast.

I suggest the simpler solution of just blocking all diagonal moves (if diagonal return) while ventcrawling.

2021-12-28 04:11 UTC, Vallat requested changes

2021-12-28 04:11 UTC, Vallat commented on code/modules/ventcrawl/ventcrawl_atmospherics.dm
> +	direction &= ~(direction & ~initialize_directions)
Remark accepted
![image](https://user-images.githubusercontent.com/10997188/147527134-59ca9dca-1cf2-48bf-97b9-18ad2bfedf22.png)
```suggestion
	direction = (direction & NORTH) || (direction & SOUTH) || (direction & WEST) || (direction & EAST)
```

2022-01-04 00:21 UTC, afterthought2 approved these changes

2022-01-11 21:20 UTC, merged