Fix character setup + change_species
NebulaSS13/Nebula pull request #2284
Opened 2022-02-05 20:37 UTC by MarinaGryphon

## Description of changes
Replaces a number of uses of set_species with change_species, and moves like, one thing from change_species to set_species.
Fixes a bunch of issues with character setup: HearthOfHestia/Nebula#189, as well as the fact that it just flat-out doesn't render properly at all following #2184.

## Why and what will this PR improve
Character setup ought to work, and the proper helper functions ought to be used.

## Authorship

Me.

2022-02-05 20:44 UTC, afterthought2 commented on code/modules/species/species.dm
> +	if((species_flags & SPECIES_FLAG_SYNTHETIC) != BP_IS_PROSTHETIC(E))
You can't check for equality safely like this; they are bitflags and might differ. Add `!`s or use logic operators.

2022-02-05 23:00 UTC, PsyCommando requested changes
Looks great to me! Besides one or two proc calls I listed. Otherwise, you've fixed a lot of things I didn't catch in my Pr!

2022-02-05 23:00 UTC, PsyCommando commented on code/modules/client/preferences.dm
> +	character.change_species(species)
Good catch!

2022-02-05 23:00 UTC, PsyCommando commented on code/modules/mob/living/carbon/human/human.dm
> +	species.update_appearence_descriptors(src)
Don't call this here. Its called later in apply_species_appearance() during normal setup().
Otherwise this causes the mob to do a full deep update twice during normal init and etc. I'd suggest calling apply_species_appearance() lower down the call chain if you manually have to call set_species.

2022-02-05 23:00 UTC, PsyCommando commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species?.create_missing_organs(src)
Hmm, I think this might not work as expected depending on the value of 'ignore_prosthetic_prefs'

2022-02-05 23:00 UTC, PsyCommando commented on code/modules/organs/external/_external.dm
> +				LAZYDISTINCTADD(internal_organs, I)
Well, shit.. That's a good catch! I can't believe that slipped in ^^;

2022-02-05 23:09 UTC, MarinaGryphon commented on code/modules/mob/living/carbon/human/human.dm
> +	species.update_appearence_descriptors(src)
Yeah, turns out it wasn't necessary after changing `mannequin.set_species` for species preview icons to `mannequin.change_species`! I'll remove this line.

2022-02-19 21:47 UTC, afterthought2 approved these changes

2022-02-23 00:21 UTC, merged

2022-03-20 01:49 UTC, PsyCommando commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species?.create_missing_organs(src)
Just leaving this for the record, but putting this here can cause infinite recursion in some conditions.. Pretty sure.