#2325 with tweaks.
NebulaSS13/Nebula pull request #2434
Opened 2022-05-26 12:14 UTC by MistakeNot4892

## Description of changes
Commit from #2325 with the requested changes. Quard seems to be gone from the Discord so unsure if he will implement them, figured I'd do it myself.

## Why and what will this PR improve
Character preview in prefs is larger and cleaner, and pAIs get their own preview when Global is selected.

## Authorship
@quardbreak for the main changes, I just tweaked a couple things.

## Changelog
:cl:
tweak: Character preview is a bit bigger and nicer.
/:cl:

2022-06-01 23:21 UTC, afterthought2 reviewed
I can't actually follow what's happening in the code relative to when the pAI vs. the mob is shown to the user because of how it's set up: whichever call you make last will win, so it just depends on the ordering of the calls. As such, I have no idea if this is logically sound.

I think it would be much saner to have a single call (kind of like we do in atom code with `update_icon`) that you make to correctly display whatever should be shown based on prefs state, be that the pAI, the mannequin, nothing, whatever. It might be coupled with possibly one (1) auxiliary public function that's used to rebuild the preview mannequin (i.e. delete and rebuild the inventory) to alleviate performance concerns.

2022-06-01 23:21 UTC, afterthought2 commented on code/modules/client/preference_setup/preference_setup.dm
> +	prefs.update_pai_preview()
This call seems illegal (no args, so it still makes a blank mutable appearance and does something with it).

2022-06-01 23:21 UTC, afterthought2 commented on code/modules/client/preference_setup/preference_setup.dm
> +			category.selected(user.client.prefs)
I think `user.client.prefs` is actually wrong; these retain a ref to their prefs datum.

2022-06-01 23:21 UTC, afterthought2 commented on code/modules/client/preference_setup/preference_setup.dm
> +		pref_mob.client.prefs.update_character_preview_map()
Again, should just be the instance's held prefs ref.

2022-06-01 23:21 UTC, afterthought2 commented on code/modules/mob/new_player/preferences_setup.dm
> +/datum/preferences/proc/update_character_preview_map()
Why rename this? It's confusing; this proc doesn't actually do anything with the map control that any of the other split out ones don't do; the main thing it does is the expensive step of deleting and rebuilding the mannequin inventory.

The number of procs involved in this whole business feels needlessly confusing.

2022-06-01 23:47 UTC, afterthought2 requested changes
Actually I understated my objections in the previous comment. Looking over this more carefully and testing locally, the _only reason it actually works_ is the pAI update call in the html content getter for the global prefs tab. This should not even be there; that proc is not a refresh proc and should not be messing with client state (and defeats the purpose of the system). It also obfuscates that some of the other refresh calls are broken (see my comment), it obfuscates the fact that some calls from the global state menu will currently rebuild the mannequin, display the mannequin briefly (because of the way prefs/Topic and base Topic are set up, and it's visible to me even testing locally with no latency), and then replace that with the pAI appearance afterwards when the callstack arrives at that `contents` proc.

2022-06-01 23:48 UTC, afterthought2 commented on code/modules/client/preference_setup/global/03_pai.dm
> +	pref.update_pai_preview(candidate.chassis)
This is what I was objecting to; this does not belong in this proc.

2022-06-02 00:22 UTC, MistakeNot4892 commented
Honestly I was adopting this because I thought it was alright, I'm not willing to revise it to the extent requested.

2022-06-02 00:22 UTC, closed without merging