Inventory slots.
NebulaSS13/Nebula pull request #2533
Opened 2022-06-15 05:59 UTC by MistakeNot4892

## Description of changes
This is a hefty one. 
- Removes all direct references to inventory stuff on mobs.
- Moves almost all inventory stuff to /mob/living or /mob.
- Expands the held item slot datums to work as generic inventory slots and plugs them in as appropriate.

## TODO ##
- [X] Implement slot datums.
- [X] Collapse procs.
- [ ] Get basic inventory condensing/rewrite actually workign in practice.
- [ ] Convert species gear lists to have appropriate ui locs.
- [ ] Convert nymph inventories to use a slot and bespoke behavior.
- [ ] Convert synthetic inventories to use slots and bespoke behavior.

## Why and what will this PR improve
Unifies inventory code in one spot and makes expanding it later trivial.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2022-11-10 17:53 UTC, out-of-phaze requested changes
This review is only addressing this todo item: `Sort out GC fails on inv slot datums.`

I think I found a potential cause, though.

2022-11-10 17:53 UTC, out-of-phaze commented on code/modules/mob/living/living.dm
> +	. = ..()
Why are you calling the parent's Destroy() prior to removing auras? Shouldn't almost all Destroy() behavior on non-top-level types be done prior to the parent call?

2022-11-10 17:53 UTC, out-of-phaze commented on code/modules/mob/living/living_inventory.dm
> +	LAZYREMOVE(inventory_slots, slot_id)
Does this ever remove it from `held_item_slots`? That feels like it'd cause hand slots to have a hanging reference that makes them fail GC.

2023-03-14 08:08 UTC, MistakeNot4892 commented on code/modules/mob/living/living.dm
> +	. = ..()
Clearing the inventory slots here means they don't get deleted in the `/atom/movable` contents clearing logic.

2023-03-14 08:09 UTC, MistakeNot4892 commented on code/modules/mob/living/living_inventory.dm
> +	LAZYREMOVE(inventory_slots, slot_id)
It shouldn't ever be present in `held_item_slots` as far as I recall. This might be outdated/wrong, it has been awhile since I touched this logic, but the lists should be distinct.

2023-03-14 08:10 UTC, MistakeNot4892 commented on code/_onclick/click.dm
> +/mob/proc/can_use_held_item(var/obj/item/held)
Note to self to split this out.

2023-03-14 09:07 UTC, MistakeNot4892 commented on code/modules/mob/living/living_inventory.dm
> +	LAZYREMOVE(inventory_slots, slot_id)
`held_item_slot_strings` is a linear list of slot strings and doesn't hold any references.

2023-06-02 22:05 UTC, MistakeNot4892 commented
This has been split up into several other PRs.

2023-06-02 22:05 UTC, closed without merging