Probably fixes medical side effects
NebulaSS13/Nebula pull request #268
Opened 2020-04-09 19:57 UTC by eckff

Opening for diff. Ports some medical side effects changes from Infinitystation

2020-04-11 04:34 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +	var/list/L = subtypesof(/datum/medical_effect)
```
	for(var/T in subtypesof(/datum/medical_effect))
		var/datum/medical_effect/M = T
		if(initial(M.name) == name)
			M = new T
			M.strength = strength
			M.start = life_tick
			side_effects += M
			break
```
Either this, or you should be deleting `M` if it isn't valid.

2020-04-11 04:35 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
>  		var/datum/medical_effect/M = new T
As above, these need to use `initial()` or clean up after being instantiated. Preferrably they should be cached somewhere for reference.

2020-04-11 04:35 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +				H.custom_pain("You feel a light pain in your head.", 5, affecting = head)
Maybe `in your [head.name]` for these, for species without 'heads'?

2020-04-11 04:36 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +				H.custom_pain("You feel a bit light around the stomach.", 10, affecting = groin)
As above, not all species have stomachs.

2020-04-11 04:36 UTC, MistakeNot4892 commented
Do these actually get used anywhere?

2020-04-11 20:57 UTC, comma commented
They're definetly not, not since like 2013 or earlier

2020-04-14 08:04 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
>  		var/datum/medical_effect/M = new T
If you just add `else qdel(M)` at line 64 this will be ok.

2020-04-14 08:04 UTC, MistakeNot4892 requested changes
Just add the qdel and I'll approve this, it's unused code anyway so improvement is harmless.

2020-04-14 10:38 UTC, MistakeNot4892 approved these changes

2020-04-14 10:47 UTC, merged