Cursed parrot rewrite. [MDB IGNORE] [IDB IGNORE]
NebulaSS13/Nebula pull request #2751
Opened 2022-10-20 10:23 UTC by MistakeNot4892

## Description of changes

Depends on #3008

Rewrote parrots to implement inventory procs and use datum AI. This might be a good use case for implementing FSM AI in the future since the states are now fairly clearly defined.

## Why and what will this PR improve
Parrot code bad.

## Authorship
Myself.

## Changelog
:cl:
tweak: Parrots now use intents for determining if they grab, attack or perch, rather than verbs.
/:cl:

2022-10-20 13:06 UTC, MistakeNot4892 commented
Outstanding issues:
- Perching behavior is not working for the AI, but works alright for player controlled.
- Moving as a player controlled parrot isn't clearing resting status like it should.

2023-02-09 01:21 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +		if(!istype(ears, /obj/item/radio/headset))
Should be `ispath`.

2023-02-09 01:22 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +	if(istype(A, /obj) && atom_is_perchable(A))
`isobj`

2023-03-14 05:14 UTC, MistakeNot4892 commented
I'm calling this done, I'll fix whatever's left after the telecomms PR goes in.

2023-04-24 05:00 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> -			return TRUE
This is an error.

2023-04-24 05:02 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +	// We can't rely on mob_can_equip() as it checks ishuman().
This will possibly be out of date by the time this PR goes in.

2023-04-24 05:03 UTC, MistakeNot4892 commented on code/datums/ai/ai.dm
> +/datum/ai/Destroy()
This got cherrypicked I think, needs to be checked.

2023-04-30 02:37 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +		glide_size = perched_on_atom.glide_size
Nonzero chance that not syncing `animate_movement` here might cause some visual issues; I had to deal with that when working on vehicles at one point.

2023-04-30 02:50 UTC, out-of-phaze requested changes
Only one small concern about perching. I don't really like the defines used in the parrot AI code but it also kind of went over my head anyway, so I just skimmed it.

2023-04-30 02:50 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +	return !perched_on_atom && istype(target) && (target.obj_flags & OBJ_FLAG_PARROT_PERCHABLE) && !(locate(/mob/living) in get_turf(target))
This will stop parrots from perching on objects they're on the same tile as, which I don't think is intended.

2023-05-30 04:48 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +		glide_size = perched_on_atom.glide_size
Not super clear on where I would reset this for the parrot.

2023-05-30 19:15 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/parrot/_parrot.dm
> +		resting = FALSE
Should probably reset `animate_movement` to its initial value here?

2023-06-01 03:57 UTC, MistakeNot4892 commented
Going to rebase this on #3081 when it's ready to go.

2023-09-10 20:55 UTC, out-of-phaze commented
What's the status on this one? Blocked by/waiting for any other PRs?

2023-09-10 23:23 UTC, MistakeNot4892 commented
Probably good to go when I rebase it.

2023-09-11 14:22 UTC, MistakeNot4892 commented
I managed to make this depend on mob inventory slots more broadly so will revisit when that stuff is done. -_-

2023-10-23 03:47 UTC, closed without merging