Expanding the z-level data system. [MDB IGNORE]
NebulaSS13/Nebula pull request #2785
Opened 2022-10-26 13:07 UTC by MistakeNot4892

Opening for CI/diff.

## Description of changes
- Enforces having a z-level object per level.
- Moves a bunch of z-level handling onto SSmapping
- Moves a bunch of overmap ambience and atmosphere into the level data object.
- Moves a bunch of turf, area and enviroment setup from the global map datum onto the level data object.
- Renames/adds level data to the maps as needed.

## Why and what will this PR improve
Allows per-level environmental setup, takes steps towards disemboweling the global map datum and moving exoplanet gen off the object init.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2022-10-26 13:08 UTC, MistakeNot4892 commented on code/__defines/misc.dm
> -#define INCREMENT_WORLD_Z_SIZE world.maxz++; global.connected_z_cache.Cut(); if (SSzcopy.zlev_maximums.len) { SSzcopy.calculate_zstack_limits() }
Lohi before you bite my head off, I will inline stuff down the track when it's all cleaned up and I can identify stuff that can go back into macros.

2022-10-27 20:11 UTC, Kapu1178 commented on code/controllers/subsystems/zlevels.dm
> +		var/obj/abstract/level_data/level = levels_by_z["[tz]"]
I hope you dont want to use this in any hot code like atmos because string interp is agonizingly slow

2022-11-01 15:45 UTC, out-of-phaze requested changes
~~haha undocumented tray runtime bugfix go brr~~
A few concerns and some style/speed issues.
Also have some vague gripes about exoplanets using `zlevels[1]` for stuff but I have no idea if that'd ever break.

2022-11-01 15:45 UTC, out-of-phaze commented on code/controllers/subsystems/mapping.dm
> +	. = ..()
Unnecessary; there is no parent functionality or return value here.

2022-11-01 15:45 UTC, out-of-phaze commented on code/controllers/subsystems/mapping.dm
> +/datum/controller/subsystem/mapping/New()
This should probably be `PreInit` instead of `New`? Since there's a comment saying "`//Do not override datum/controller/subsystem/New()`"".

2022-11-01 15:45 UTC, out-of-phaze commented on code/controllers/subsystems/mapping.dm
> +		CRASH("Invalid z-level supplied to get_connected_levels: [z || "NULL"]")
This incorrectly reports "NULL" instead of 0 if something calls `get_connected_levels(0)`, which is kinda annoying.

2022-11-01 15:45 UTC, out-of-phaze commented on code/controllers/subsystems/mapping.dm
> +			level.find_connected_levels(.)
Okay, honestly, this is kind of gross. `find_connected_levels` mutates `levels_by_id[other_id]` and returns nothing, which feels weird. If we find any laterally connected levels, shouldn't they be returned by this proc?

2022-11-01 15:45 UTC, out-of-phaze commented on code/game/base_turf.dm
> +	SSmapping.base_turf_by_z["[choice]"] = new_base_path
```suggestion
	SSmapping.base_turf_by_z[num2text(choice)] = new_base_path
```
Nearly twice as fast, in my testing, and also we should be using num2text to convert nums to text instead of interpolation just generally.

2022-11-01 15:45 UTC, out-of-phaze commented on code/game/gamemodes/endgame/ftl_jump/ftl_jump.dm
> +		SSmapping.accessible_z_levels -= "[z]" //not accessible during the jump
```suggestion
		SSmapping.accessible_z_levels -= num2text(z) //not accessible during the jump
```
Twice as fast and easier to understand.

2022-11-01 15:45 UTC, out-of-phaze commented on code/game/machinery/cryopod.dm
> +		var/obj/effect/overmap/visitable/O = global.overmap_sectors["[z]"]
```suggestion
		var/obj/effect/overmap/visitable/O = global.overmap_sectors[num2text(z)]
```
Same as above, sorry for nitpicking but I figure that since you're already touching this code...

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/mining/mine_turfs.dm
> +	if (!global.mining_floors["[src.z]"])
```suggestion
	if (!global.mining_floors[num2text(z)])
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/mining/mine_turfs.dm
> +		global.mining_floors["[src.z]"] = list()
```suggestion
		global.mining_floors[num2text(z)] = list()
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/mining/mine_turfs.dm
> +	global.mining_floors["[src.z]"] += src
```suggestion
	global.mining_floors[num2text(z)] += src
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/mining/mine_turfs.dm
> +	if (global.mining_floors["[src.z]"])
```suggestion
	if (global.mining_floors[num2text(z)])
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/mining/mine_turfs.dm
> +		global.mining_floors["[src.z]"] -= src
```suggestion
		global.mining_floors[num2text(z)] -= src
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/multiz/level_data.dm
> +		SSmapping.base_turf_by_z["[my_z]"] = base_turf
```suggestion
		SSmapping.base_turf_by_z[num2text(my_z)] = base_turf
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/multiz/level_data.dm
> +		var/obj/effect/overmap/overmap_entity = global.overmap_sectors["[z]"]
```suggestion
		var/obj/effect/overmap/overmap_entity = global.overmap_sectors[num2text(z)]
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/multiz/level_data.dm
> +	for(var/thing in global.mining_floors["[my_z]"])
```suggestion
	for(var/thing in global.mining_floors[num2text(my_z)])
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/overmap/sectors.dm
>  	var/datum/overmap/overmap = global.overmaps_by_z["[z]"]
Since you're in the area:
```suggestion
	var/datum/overmap/overmap = global.overmaps_by_z[num2text(z)]
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/overmap/sectors.dm
>  			global.overmap_sectors["[zlevel]"] = src
Ditto, optional but would be nice.
```suggestion
			global.overmap_sectors[num2text(zlevel)] = src
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/overmap/spacetravel.dm
>  		global.overmap_sectors -= "[num]"
Optional, but you touched this file already, so:
```suggestion
		global.overmap_sectors -= num2text(num)
```

2022-11-01 15:45 UTC, out-of-phaze commented on code/modules/overmap/spacetravel.dm
>  	var/datum/overmap/overmap = global.overmaps_by_z["[z]"]
See above, optional:
```suggestion
	var/datum/overmap/overmap = global.overmaps_by_z[num2text(z)]
```

2022-11-01 15:45 UTC, out-of-phaze commented on maps/away/lost_supply_base/lost_supply_base.dm
> +	//generate_mining_by_z = 1
Why is this commented out instead of just removed?

2022-11-01 15:45 UTC, out-of-phaze commented on maps/away/mining/mining.dm
> +	//base_turf_for_zs = /turf/simulated/floor/asteroid
See above, why is this commented out instead of removed?

2022-11-01 17:00 UTC, MistakeNot4892 commented on maps/away/lost_supply_base/lost_supply_base.dm
> +	//generate_mining_by_z = 1
Haven't gotten around to mapping the landmarks that run mining gen in and left the comments as markers. PR is a draft :P

2022-11-01 17:09 UTC, MistakeNot4892 commented on code/controllers/subsystems/mapping.dm
> +/datum/controller/subsystem/mapping/New()
Fair, wasn't aware of that proc.

2022-11-01 17:10 UTC, MistakeNot4892 commented on code/controllers/subsystems/mapping.dm
> +			level.find_connected_levels(.)
It doesn't mutate that, and it works the way it does to prevent looping on a circular set of level references.

2022-11-01 17:12 UTC, MistakeNot4892 commented on code/game/base_turf.dm
> +	SSmapping.base_turf_by_z["[choice]"] = new_base_path
I'm planning on seeing if we can just expand this list when we increment world.maxz and use the z as the index without stringifying.

2022-11-01 17:17 UTC, out-of-phaze commented on code/controllers/subsystems/mapping.dm
> +			level.find_connected_levels(.)
Reread it, looks fine to me. Don't know what I was thinking.

2023-02-08 05:49 UTC, afterthought2 approved these changes

2023-02-09 14:43 UTC, merged