Markings rewrite/refactor. [IDB IGNORE]
NebulaSS13/Nebula pull request #2870
Opened 2023-01-10 14:10 UTC by MistakeNot4892

## Description of changes
- Renames all 'torso' states to 'chest' to line up with the BP defines.
- Adds a mask system for body markings and damage overlays, and collapses them into single states.

## Why and what will this PR improve
Makes it much less painful to add or edit markings, and makes damage states less muddy by multiplying them against solid white.

## Authorship
Myself for most of the code, with reference to Kapu's clipping logic linked in Discord.

## Changelog
Nothing player-facing.

2023-01-12 20:21 UTC, out-of-phaze requested changes

2023-01-12 20:21 UTC, out-of-phaze commented on code/modules/sprite_accessories/_accessory_markings.dm
> +		icons[bodytype][bodypart] = list()
Should this be using the lazyinitlist macros to be more succinct? The repeated ifs are a bit intimidating at first.
```suggestion
	LAZYINITLIST(icons[bodytype])
	LAZYINITLIST(icons[bodytype][bodypart])
```

2023-01-12 20:21 UTC, out-of-phaze commented on code/modules/organs/prosthetics/prosthetics_manufacturer.dm
> +			. += "torso state present in icon"
Resolving this issue should be relatively straightforward from the message.
```suggestion
			. += "deprecated \"torso\" state present in icon, use \"chest\" instead"
```

2023-01-12 20:21 UTC, out-of-phaze commented on code/modules/organs/prosthetics/prosthetics_manufacturer.dm
> +			. += "chest state not present in icon"
If for some reason we ever change what BP_CHEST is defined to, this should probably say the proper state name.
```suggestion
			. += BP_CHEST + " state not present in icon"
```

2023-02-05 03:29 UTC, afterthought2 approved these changes

2023-02-08 05:49 UTC, merged