Nullcaf coffee
NebulaSS13/Nebula pull request #2936
Opened 2023-01-29 04:30 UTC by comma

## Description of changes
Adds null caffeine coffee drink
Can be bought in vendomats with normal coffee.
Doesn't give you jitters but gives you pain instead. It's also psi disrupting.

Added  support for chems blocking psi, they will be consumed when stress check is done (though usually vessels break first)

## Why and what will this PR improve
I think it's funny and also more tie ins with psionic system and ways to screw with them

## Authorship
Me

## Changelog
:cl:
add: Added nullcaf, a type of coffee. It doesnt' give jitters, just hurts. It's also psi inert, but will evaporate when withstanding psionic stress.
/:cl:

2023-01-29 10:25 UTC, MistakeNot4892 commented on mods/content/psionics/items/_items.dm
> +				reagents.remove_reagent(reagent_type, -stress)
You could really fuck with them by vaporizing into the atmosphere.

2023-01-29 10:25 UTC, MistakeNot4892 commented on mods/content/psionics/items/_items.dm
> +	if(!.)
Shouldn't this be `. > 0`?

2023-02-04 15:48 UTC, comma commented on mods/content/psionics/items/_items.dm
> +				reagents.remove_reagent(reagent_type, -stress)
Made it just heat up the vessel

2023-02-04 15:48 UTC, comma commented on mods/content/psionics/items/_items.dm
> +	if(!.)
Done

2023-02-26 22:28 UTC, MistakeNot4892 commented on mods/content/psionics/datum/chems.dm
> +	return used
Should this be `stress - used`?

2023-02-26 22:29 UTC, MistakeNot4892 commented on code/modules/reagents/chems/chems_drinks.dm
> +		M.custom_pain(SPAN_NOTICE("A sudden pain spike through your temples jolts you awake."), 5)
`A sudden spike of pain` would read a bit cleaner.

2023-02-26 22:29 UTC, MistakeNot4892 commented on code/modules/reagents/chems/chems_drinks.dm
> +	lore_text = "Extra bitter coffee purged by the patented neutron bombing process. Guaranteed to contain no more than 2% inert dust. "
`a` instead of `the` before `patented neutron bombing process` imo.

2023-04-30 11:10 UTC, comma commented on code/modules/reagents/chems/chems_drinks.dm
> +	lore_text = "Extra bitter coffee purged by the patented neutron bombing process. Guaranteed to contain no more than 2% inert dust. "
Done

2023-04-30 11:10 UTC, comma commented on code/modules/reagents/chems/chems_drinks.dm
> +		M.custom_pain(SPAN_NOTICE("A sudden pain spike through your temples jolts you awake."), 5)
Done

2023-05-01 21:34 UTC, out-of-phaze requested changes

2023-05-01 21:34 UTC, out-of-phaze commented on code/modules/reagents/chems/chems_drinks.dm
> +		M.apply_effect(10, PAIN, 0)
This is redundant if you use `custom_pain()`. Should just use one or the other.

2023-05-01 21:34 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/drinks.dm
> +	name = "cup of null"
I feel like this is going to be confusing for people who don't understand what nullcaf is. I figure this is probably supposed to be a reference to the old `nothing` reagent but it doesn't really work here.

2023-05-10 21:55 UTC, closed without merging