Moving internals proc to mob level.
NebulaSS13/Nebula pull request #2963
Opened 2023-02-10 11:39 UTC by MistakeNot4892

## Description of changes
Moves internals logic into its own file and condenses it on `/mob/living`.

## Why and what will this PR improve
Splitting this out of the inventory rewrite PR plus working towards destroying the /carbon mobtype.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-02-12 03:55 UTC, out-of-phaze requested changes
Some stubs exist and are redefined on the same level later in the file, which should be corrected.

Non-blocking suggestions: Feels like the PR title should say `living` or `mob/living` or `living mob` level. Also, maybe consider moving `var/obj/item/tank/internal = null` to the living level as well, so that we can remove the last of the carbon-level overrides in `internals.dm`?

2023-02-12 03:55 UTC, out-of-phaze commented on code/modules/mob/living/internals.dm
> +/mob/living/proc/set_internals_to_best_available_tank(var/breathes_gas = /decl/material/gas/oxygen, var/list/poison_gas = list(/decl/material/gas/chlorine))
Having a stub here when it's also redefined later seems redundant and just adds overhead. See line 82.

2023-02-12 03:55 UTC, out-of-phaze commented on code/modules/mob/living/internals.dm
> +/mob/living/proc/set_internals(obj/item/tank/source, source_string)
This is overridden at the /mob/living level on line 71.

2023-02-12 03:55 UTC, out-of-phaze commented on code/modules/mob/living/internals.dm
> +/mob/living/proc/toggle_internals(var/mob/living/user)
This is overridden at the /mob/living level on line 39.

2023-02-12 03:55 UTC, out-of-phaze commented on code/modules/mob/living/internals.dm
> +	for(var/slot in global.internal_source_slots)
Why not check `get_possible_internals_sources()` here and remove `global.internal_source_slots` entirely? Currently this results in a weird disparity between someone turning on their own internals and someone else enabling it for them.

2023-02-13 04:43 UTC, MistakeNot4892 commented on code/modules/mob/living/internals.dm
> +	for(var/slot in global.internal_source_slots)
Did some refactoring around this to make both places use the same proc, and to fold held items into the base proc.

2023-02-26 20:41 UTC, out-of-phaze approved these changes
One issue with a comment and one future compatibility note, both non-blocking.

Future compatibility note: `parse_zone` is incompatible with modular zones like `BP_L_HAND_UPPER`, `BP_M_HAND`, etc. The way this breaks currently appears to be handled properly, however, in that if the slot name is null it only uses the name of the tank in the message. In the future, it may be wise to replace `parse_zone` with `GET_EXTERNAL_ORGAN(src, zone)?.name` or even `GET_EXTERNAL_ORGAN(src, zone)::name` (so that it's `left upper forelimb` instead of `Unbranded robotic left upper forelimb` or whatever), but for now this should be safe.

2023-02-26 20:41 UTC, out-of-phaze commented on code/modules/mob/living/internals.dm
> +// Set internals on or off. Implemented properly on /carbon
```suggestion
// Set internals on or off.
```
At this point the comment isn't very useful, so you could also just remove it entirely.

2023-03-01 22:57 UTC, merged