Codex entries generated per atom will be kept on the atom.
NebulaSS13/Nebula pull request #2984
Opened 2023-02-15 22:43 UTC by MistakeNot4892

## Description of changes
- Atoms will keep a ref to any specific codex entry they generate instead of caching them on the subsystem.
- The subsystem will no longer track atom-specific codex entries and will not run uniqueness checks on them.

## Why and what will this PR improve
Examining two MREs causes the codex to complain.

## Authorship
@out-of-phaze for pointing out the issue, me for the code.

## Changelog
Nothing player-facing.

2023-02-20 04:57 UTC, out-of-phaze requested changes
May be worth gating `SScodex.all_entries -= src` in `/datum/codex_entry/Destroy` (`code/modules/codex/entries/_codex_entry.dm:63`) behind `store_codex_entry`, that's a large list and a lot of atoms with temporary entries getting deleted could impact things like explosion processing.

2023-02-20 04:57 UTC, out-of-phaze commented on code/controllers/subsystems/initialization/codex.dm
> +	var/list/entries_by_ref =    list()
```suggestion
```
Unused var?

2023-02-20 04:58 UTC, MistakeNot4892 commented on code/controllers/subsystems/initialization/codex.dm
> +	var/list/entries_by_ref =    list()
Yeah added before I decided to do it per-atom.

2023-02-24 22:50 UTC, out-of-phaze approved these changes
The Destroy code implies that more than one entry in `index_file` and `search_cache` can be/contain `src`. Assuming that's true, this is fine, although since `cached -= src` can't remove src if it isn't there and that does a search anyway, it might be better to just remove the `src in cached` check on line 74—I'd prefer if someone double-check that before any changes are made, though.

No blocking concerns.

2023-02-25 00:11 UTC, MistakeNot4892 commented
The only thing that should be destroying codex entries is atom cleanup anyway, so the expanded Destroy() is more for the sake of thoroughness than any practical concern.

2023-02-26 13:32 UTC, merged