Hands slot refactor, supporting framework for inv slots.
NebulaSS13/Nebula pull request #3031
Opened 2023-03-29 05:51 UTC by MistakeNot4892

## Description of changes
Splitting some more logic out of #2533. Finally getting the inventory slot datums implemented. This time it's the hands slot refactor and some associated inventory code rewrites that condense it down and move the old style hard references into their own procs for later removal.

This also moves stripping down to `/mob` level.

I've tested this locally and everything appears to be working as expected.

## Why and what will this PR improve
Working towards datum inventories.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-03-29 06:59 UTC, MistakeNot4892 commented
Stripping also tested, seems to be working.

2023-04-17 16:39 UTC, PsyCommando commented
Is this going to affect/alter things that occupy more than one hand slot?
Because, it's been pretty hard to make items that block both slots cleanly. There's the two handed efficiency check currently, but it only works for weapons, and not for say a big crate you have to carry, and want to prevent carrying two of them, one in each hand slots.

2023-04-18 02:06 UTC, MistakeNot4892 commented
`Is this going to affect/alter things that occupy more than one hand slot?`
This does not change the user experience or behavior at all. We also don't currently have anything that occupies multiple hand slots - it would probably make it somewhat easier to implement structurally but doesn't support it out of the box.

2023-04-25 02:13 UTC, out-of-phaze requested changes
Local testing revealed that if a held item gets qdeleted, like inflatable doors for example, that hand is permanently unusable (until you call clear_slot() with VV). Pls fix.

2023-04-25 02:13 UTC, out-of-phaze commented on code/modules/mob/mob_grabs.dm
>  // See /mob/living/carbon for this one.
This comment should be on `/mob/proc/get_organ`, since `has_organ` isn't stubbed.

2023-04-26 08:35 UTC, out-of-phaze submitted a review, later dismissed
With the qdeleted item fix in, it works fine in local testing.

2023-04-30 10:17 UTC, out-of-phaze commented on code/modules/mob/mob.dm
> +		if(suit.has_sensor == 1)
```suggestion
		if(suit.has_sensor == SUIT_HAS_SENSORS)
```
Regression in merge resolution.

2023-05-09 10:10 UTC, out-of-phaze approved these changes

2023-05-10 10:37 UTC, merged