Implementing general inventory slots.
NebulaSS13/Nebula pull request #3081
Opened 2023-05-10 23:47 UTC by MistakeNot4892

## Description of changes
Implements datum inventory slots. Splitting out of #2533.

- Inventory slot datums have been added to replace the extant slot definitions on species and in legacy code.
- `held_item_slots` -> `_held_item_slots`, is now a linear list of strings only used for checking if something is a held slot.
- `inventory_slots` -> `_inventory_slots`, associative list of slot string to slot datum.

**TODO:**
- [x] Fix QDELETED check preventing item drops.
- [x] Work out what is QDELing inventory slots and causing them to vanish.
- [x] Work out why nothing will equip to hand slots.
- [x] Check why coverage isn't being respected.
- [x] Work out why pockets don't work.
- [ ] Test more.

**Tested:**
- Basic equipping and unequipping.
- Moving items to and from hands.
- Moving items to and from storage.
- Checking robots still work as expected.
- Stripping and reequipping.

## Why and what will this PR improve
Flexible modular inventory code.

## Authorship
Myself.

## Changelog
In theory, nothing player-facing.

2023-06-01 19:28 UTC, out-of-phaze commented on code/modules/mob/inventory.dm
>  	if(!istype(W))
This is where the QDELETED check was that broke item dropping. It looks to me like this should work fine now.

2023-06-01 20:12 UTC, out-of-phaze requested changes
Preliminary review to address CI failure/testing regression from an inverted check.

2023-06-01 20:12 UTC, out-of-phaze commented on code/datums/inventory_slots/slots/slot_ears.dm
> +	return ..() && prop.w_class <= ITEM_SIZE_TINY
This is why CI is failing. `/obj/item/clothing/head/hairflower`, used in the test, is not `ITEM_SIZE_TINY` and therefore can't be equipped now.
```
			if((w_class > ITEM_SIZE_TINY) && !(slot_flags & SLOT_EARS))
				return FALSE
```
It seems you've inverted the current check, which is intended to allow tiny items to be hidden in the ear slot even without the SLOT_EARS flag.
```suggestion
	return ..() || prop.w_class > ITEM_SIZE_TINY
```
I checked and couldn't find any other cases where this logic was inverted; pockets use something similar and it works fine.

2023-06-02 09:14 UTC, MistakeNot4892 commented on code/datums/inventory_slots/slots/slot_ears.dm
> +	return ..() && prop.w_class <= ITEM_SIZE_TINY
Good eye for the issue, suggestion is not quite right - fix was to move the slot checking to a proc and `..() || prop.w_class <= ITEM_SIZE_TINY`

2023-06-02 11:06 UTC, out-of-phaze commented on code/datums/inventory_slots/slots/slot_ears.dm
> +	return ..() && prop.w_class <= ITEM_SIZE_TINY
Gah, don't know how I messed the logic up that bad.

2023-06-02 13:13 UTC, out-of-phaze approved these changes
Really impressed with the expanded unit test coverage for this, will hopefully make future changes to this system less error-prone.

2023-06-03 12:59 UTC, merged