Semi-port of banners from Polaris.
NebulaSS13/Nebula pull request #3102
Opened 2023-06-04 13:27 UTC by MistakeNot4892

## Description of changes
Adds banner frames and banners. Banner frames are made from wood/steel/etc, banners are made at the textiles fabricator. You can hang banners on banner frames.

![image](https://github.com/NebulaSS13/Nebula/assets/2468979/52bd735a-afb6-410b-b67c-22748ec34ff5)

The above are presets, banners and frames are set up to take colour from material.

Someone might want to go over the icons at some point, I greyscaled them very roughly.

## Why and what will this PR improve
Decorative item used by a few downstreams, made a bit more modular and interactive for Neb.

## Authorship
Myself for the code.
Icons originated on Polaris before I greyscaled them (poorly), I'm not sure where the are from originally. I remember seeing them on Paradise way back in the day.

## Changelog
:cl:
add: You can now build banner stands and print banners at a textiles fabricator, or craft one from cloth.
/:cl:

2023-06-08 10:52 UTC, MistakeNot4892 commented
Going to unfreeze this as it's small and the potential for bugs is minimal.

2023-06-09 10:12 UTC, comma approved these changes

2023-06-09 16:53 UTC, out-of-phaze requested changes
Seems there may have been an accidental port? I don't see any other references to VirGov in the government modpack. The only current references to Vir in the code are short for Virology.

2023-06-09 16:53 UTC, out-of-phaze commented on mods/content/government/items/clutter.dm
> +	hung_desc = "The banner is emblazoned with a white VirGov seal."
What is VirGov? Was this an unintentional port when you cherry-picked it from your Polaris branch?

2023-06-09 21:55 UTC, MistakeNot4892 commented on mods/content/government/items/clutter.dm
> +	hung_desc = "The banner is emblazoned with a white VirGov seal."
Not unintentional, just lazy. I can trim it out if it matters.

2023-06-09 22:00 UTC, out-of-phaze approved these changes

2023-06-09 22:01 UTC, merged