Readds mild painkillers, makes them the 'default' painkiller.
NebulaSS13/Nebula pull request #3109
Opened 2023-06-10 12:26 UTC by MistakeNot4892

## Description of changes
- Most default painkillers will now be 'mild painkillers', which are lower power, but not narcotic, with a higher overdose threshold.
- Strong painkillers have been added, replacing mild painkillers in some contexts.

## Why and what will this PR improve
The default painkiller being morphine-grade has been pretty lethal in the past.

## Authorship
Done with reference to Baystation painkiller values.

## Changelog
:cl:
tweak: Strong (narcotic) painkillers and mild (non-narcotic) painkillers are now distinct chemicals.
/:cl:

2023-06-10 12:27 UTC, MistakeNot4892 commented on code/modules/hydroponics/seed_datums.dm
> -/datum/seed/algae/bruisegrass
Forgot I snipped this. It's a ValSal thing from ScavStation days.

2023-06-17 01:21 UTC, out-of-phaze requested changes

2023-06-17 01:21 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/borghydro.dm
> +		/decl/material/liquid/painkillers
```suggestion
		/decl/material/liquid/painkillers/strong
```
Please don't let surgeon borgs do surgery on people with just Tylenol.

2023-06-17 01:21 UTC, out-of-phaze commented on code/modules/reagents/chems/chems_painkillers.dm
>  	SET_STATUS_MAX(M, STAT_DRUGGY, 10)
Why would overdosing on non-opiate painkillers get you high? Maybe move the druggy effect under `if(narcotic)` below.

2023-06-17 01:21 UTC, out-of-phaze commented on code/modules/reagents/chems/chems_painkillers.dm
> +	M.add_chemical_effect(CE_TOXIN, 1)
I don't *think* ODing on opiates is toxic? The breathloss is pretty punishing already, isn't it? I'd either put this behind an `else` after `if(narcotic)` or give it its own separate overdose toxicity var.

2023-06-18 15:39 UTC, out-of-phaze approved these changes

2023-06-21 08:46 UTC, merged