Moving aquatic simple_animal level down to base simple_animal.
NebulaSS13/Nebula pull request #3177
Opened 2023-07-01 13:15 UTC by MistakeNot4892

## Description of changes
Merges aquatic logic at base simple_animal level.

## Why and what will this PR improve
Cleaner code.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-07-05 03:33 UTC, afterthought2 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		icon_state += "-dying"
Why gate this behind aquatic, as opposed to just letting the `HAS_STATUS` figure it out?

2023-07-05 03:34 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		icon_state += "-dying"
Valid point I guess. I guess mainly because STAT_PARA doesn't imply dying for most mobs. But that said, most mobs won't have a `world-dying` state.

2023-07-05 03:35 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		icon_state += "-dying"
I might rename it to `-paralyzed` and remove the aquatic check.

2023-07-05 11:10 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		icon_state += "-dying"
Done.

2023-07-05 23:04 UTC, afterthought2 submitted a review, later dismissed

2023-07-08 14:24 UTC, out-of-phaze requested changes

2023-07-08 14:24 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/aquatic/aquatic_carp.dm
> -	meat_type = /obj/item/chems/food/fish/carp
Unintentional change? `retaliate/aquatic` only has normal fish meat, not carp meat.

2023-07-08 14:24 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		if(PENDING_STATUS(src, STAT_PARA))
Doesn't this mean it won't get paralyzed if it isn't already?

2023-07-08 14:24 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	// don't bother checking it twice if we got a supplied 0 val.
Sort of a nitpick but this comment is about checking `atmos_suitable`, not `environment`, isn't it? Shouldn't it be next to that line?

2023-07-08 14:30 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		if(PENDING_STATUS(src, STAT_PARA))
Yeah that's missing a `!`. Should probably be HAS_STATUS I guess though that puts suffocation on a 2-second delay which might not be ideal.

2023-07-08 21:12 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		if(PENDING_STATUS(src, STAT_PARA))
But it already uses `SET_STATUS_MAX` anyway, why are we checking that to begin with...?

2023-07-13 14:24 UTC, out-of-phaze approved these changes

2023-07-13 14:24 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		if(!HAS_STATUS(src, STAT_PARA)) // gated to avoid redundant update_icon() calls.
I'll note that this probably means you'll get a free tick or two without paralysis every 3 or so ticks, but maybe that's intended?

2023-07-14 22:11 UTC, merged