Deletes changeling.
NebulaSS13/Nebula pull request #3189
Opened 2023-07-04 03:03 UTC by MistakeNot4892

## Description of changes
Per Discord vote, bins changeling for the time being.
![image](https://github.com/NebulaSS13/Nebula/assets/2468979/1c3929da-5bd0-4d4c-884b-83669844fdda)

## Why and what will this PR improve
- Changeling is unmaintained.
- Changeling has not been meaningfully updated on this codeline since 2013.
- Changeling has a hard dependency on DNA, which we would like to remove or completely rewrite.

This PR does not block the reintroduction of changeling, but any replacement is going to need to adhere to modern code standards and pass review.

## Authorship
Myself.

## Changelog
:cl:
del: Removed changeling.
/:cl:

2023-07-04 19:54 UTC, out-of-phaze requested changes

2023-07-04 19:54 UTC, out-of-phaze commented on code/datums/mind/mind.dm
> +	if(current?.mind == src) //remove ourself from our old body's mind variable
Is it fine to gate `SSnano.user_transferred(current, new_character)` behind this instead of just behind `if(current)`?

2023-07-04 19:54 UTC, out-of-phaze commented on code/game/gamemodes/objectives/objective_absorb.dm
Delete this file, it makes no sense without Changeling.

2023-07-04 19:54 UTC, out-of-phaze commented on code/datums/mind/mind.dm
Delete the "absorb" references on lines 282, 340, and 356.

2023-07-04 19:54 UTC, out-of-phaze commented on code/modules/mob/grab/grab_datum.dm
> +	var/can_absorb = 0							// Whether this grab state is strong enough to absorb the person you're grabbing. Deprecated.
Why not remove this variable entirely? It's entirely unused outside of `/mob/proc/changeling_absorb_dna()`.

2023-07-05 03:04 UTC, MistakeNot4892 commented on code/datums/mind/mind.dm
> +	if(current?.mind == src) //remove ourself from our old body's mind variable
Checking now. The `== src` bit is used in /datum/mind/Destroy() so seemed appropriate. Looks like user_transferred() just transfers UIs so I'll do if(current) then gate the nulling under its own check.

2023-07-05 09:12 UTC, out-of-phaze approved these changes

2023-07-10 03:21 UTC, merged