Polaris signs and floor decals.
NebulaSS13/Nebula pull request #3195
Opened 2023-07-07 08:00 UTC by MistakeNot4892

## Description of changes
- Ports some floor decals and signs from Polaris.
- Adds unit tests for floor decals/sign icons.

## Why and what will this PR improve
Useful for porting Polaris maps, also unit tests are always good.

## Authorship
Myself for the code, Polaris for the icons.

## Changelog
Nothing player-facing.

2023-07-08 14:13 UTC, out-of-phaze requested changes

2023-07-08 14:13 UTC, out-of-phaze commented on code/game/objects/structures/signs/direction_signs.dm
> +	desc          = "A sign indicating what hangar the observe is near."
```suggestion
	desc          = "A sign indicating which hangar its reader is near."
```

2023-07-11 04:24 UTC, afterthought2 approved these changes

2023-07-11 12:24 UTC, out-of-phaze approved these changes

2023-07-11 12:24 UTC, merged