Condensing some bodytemp handling on /mob/living.
NebulaSS13/Nebula pull request #3235
Opened 2023-07-18 12:59 UTC by MistakeNot4892

## Description of changes
Per title, moving human-level bodytemp equalizing down to /mob/living.

## Why and what will this PR improve
Usual argument, makes it easier to kill carbon and generalize/share environment handling logic.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-07-20 17:17 UTC, comma approved these changes, later dismissed

2023-07-27 22:37 UTC, out-of-phaze requested changes

2023-07-27 22:37 UTC, out-of-phaze commented on code/modules/mob/living/life.dm
> +	stabilize_body_temperature()
This should be indented, otherwise dead mobs and mobs in stasis will still change their body temperature.

2023-08-04 04:20 UTC, out-of-phaze approved these changes

2023-08-05 19:35 UTC, merged