Moved PIXEL_SCALE into a DEFAULT_APPEARANCE_FLAGS var.
NebulaSS13/Nebula pull request #3252
Opened 2023-07-23 15:10 UTC by MistakeNot4892

## Description of changes
- Adds `DEFAULT_APPEARANCE_FLAGS` currently containing only `PIXEL_SCALE`.
- Sets this by default on several types (atom, atom/movable, image, mutable_appearance).
- Removes direct setting in favour of |= in cases that previously included PIXEL_SCALE.

## Why and what will this PR improve
Part of the work towards porting Bay emissives, also generally cleaner code.

## Authorship
Unsure, possibly CrimsonShrike, this is part of the port chain.

## Changelog
Nothing player-facing ideally.

2023-07-24 08:07 UTC, out-of-phaze requested changes
Comment: in the future (515+) I think a number of these could be replaced with type-relative definitions, like:
```
    appearance_flags = parent_type::appearance_flags | KEEP_TOGETHER & ~TILE_BOUND
```
which prevents having to re-specify all the parent's flags.

2023-07-24 08:07 UTC, out-of-phaze commented on code/game/objects/structures/rubble.dm
> -		I.appearance_flags = PIXEL_SCALE
This line served to remove `TILE_BOUND` and should remain here.
```dm
		I.appearance_flags &= ~TILE_BOUND
```

2023-07-24 08:09 UTC, MistakeNot4892 commented on code/game/objects/structures/rubble.dm
> -		I.appearance_flags = PIXEL_SCALE
`I` is a fresh image instance and never had `TILE_BOUND` set.

2023-07-24 08:11 UTC, out-of-phaze approved these changes, later dismissed

2023-08-01 21:02 UTC, out-of-phaze approved these changes

2023-08-04 00:28 UTC, merged