Max health and updatehealth() rewrite.
NebulaSS13/Nebula pull request #3256
Opened 2023-07-24 11:11 UTC by MistakeNot4892

## Description of changes
- `updatehealth` is now `update_health`.
- `update_health` removed from a bunch of locations and folded into a `do_update_health` arg to appropriate damage setters.
- Other redundant `update_health` calls removed.
- `maxHealth` on blobs is now `blob_max_health`.
- `maxHealth` on mobs is now `mob_default_max_health`.
- Added a `get_max_health()` getter for retrieving max health. 
- Condenses a lot of death checking into `updatehealth()` and new procs (`get_total_life_damage()` and `should_be_dead()`) and cleans up death() calls outside of `updatehealth()`.

## Why and what will this PR improve
Centralizes health updates, less unnecessary/redundant calls, will allow for aspects etc to modify maxhealth down the track.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-07-25 05:02 UTC, MistakeNot4892 commented
Clobbered a ton of my own changes to this, rip.

2023-08-09 20:55 UTC, PsyCommando commented
Those are mob changes right? Because I got the same thing going for /obj?

2023-08-09 23:18 UTC, MistakeNot4892 commented
Yeah this is specifically for mobs. It should make it much easier to unify down the track.

2023-08-12 14:34 UTC, MistakeNot4892 commented
This spiralled a bit out of control, but should be good to review now.

2023-08-23 09:52 UTC, MistakeNot4892 commented
These CI fails are baffling. Wondering if I have an infinite loop in my code somewhere.

2023-08-30 15:14 UTC, MistakeNot4892 commented
Honestly I am expecting this to cause a lot of bugs, but I don't think we're going to isolate them in review due to how labyrinthine these systems are. Fixing them piecemeal as they come up seems like a more effective approach to me.

2023-12-13 19:13 UTC, out-of-phaze requested changes
Making health not update by default after damage feels like a major footgun waiting to happen for new contributors... I had to deal with issues related to that on Sunset in chem code. Is it really necessary?

EDIT: As discussed on Discord, it should probably be changed to update by default.

2023-12-13 19:13 UTC, out-of-phaze commented on code/modules/mob/living/carbon/brain/brain.dm
> +	return stat == CONSCIOUS && istype(loc, /obj/item/mmi)
Will this cause issues for brainmobs in posibrains, or are those still a subtype of MMI at this point?

2023-12-13 19:13 UTC, out-of-phaze commented on code/modules/mob/living/carbon/brain/life.dm
> +				alert = 0
```suggestion
				alert = FALSE
```

2023-12-13 19:13 UTC, out-of-phaze commented on code/modules/mob/living/carbon/brain/life.dm
> +					alert = 1
```suggestion
					alert = TRUE
```
Same goes for other uses of `alert = 1` in here.

2023-12-13 19:13 UTC, out-of-phaze commented on code/modules/mob/living/life.dm
> -		updatehealth()
This... is necessary to make sure that `CE_REGEN_BURN` and `CE_REGEN_BRUTE` cause fewer repeated update_health calls, no? Now `heal_organ_damage()` calls it directly, meaning other overrides will build onto that—for example, downstream I have a couple extra healing chem effects on top of these two. The check is to make sure update_health() is delayed until `apply_chemical_effects()` is over.

2024-01-04 06:34 UTC, out-of-phaze approved these changes

2024-01-05 06:41 UTC, merged