Holomap fixes
NebulaSS13/Nebula pull request #3271
Opened 2023-08-12 15:46 UTC by MistakeNot4892

- Holomaps don't runtime error on qdel or reinit.
- Holomap cursors work first go instead of only after a level change.
Thanks @out-of-phaze for identifying the cursor issue and a fix.

2023-08-12 16:48 UTC, out-of-phaze requested changes

2023-08-12 16:48 UTC, out-of-phaze commented on code/controllers/subsystems/holomap.dm
>  	var/icon/big_map = icon(HOLOMAP_ICON, "stationmap")
This variable is now unused also, which means we're wasting two 480x480 blend ops.

2023-08-15 13:17 UTC, MistakeNot4892 commented
Rebased onto dev rip.

2023-08-15 20:09 UTC, out-of-phaze approved these changes

2023-08-16 09:39 UTC, merged