Converting human icon code to exist on the inventory slots instead.
NebulaSS13/Nebula pull request #3289
Opened 2023-08-23 08:45 UTC by MistakeNot4892

## Description of changes
- Inventory slot `update_overlay` now becomes `update_mob_equipment_overlay`.
- `update_mob_equipment_overlay` can handle a null prop being passed in.
- `update_mob_equipment_overlay` is called by `refresh_visible_overlays` at `/mob/living` level.
- The various `update_inv_foo` procs have been rolled into their respective inventory slots which are now updated with `update_equipment_overlay`.
- `set/get_current_mob_over/underlay` added for the human `over/underlays_standing` updating.
- `overlays_standing` is now `mob_overlays`, `underlays_standing` is now `mob_underlays`. Direct use of these lists has been replaced with getters/setters pending a better layering solution.

Tested on local but I expect I will have missed `src` or not set slots in some places.

## Why and what will this PR improve
Centralizes inventory updates in a way that allows for many mobs to benefit from the logic, not just humans.
Allows me to do some cheating with inventory slots when replacing the hattable extension in the future.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-08-27 15:07 UTC, out-of-phaze requested changes

2023-08-27 15:07 UTC, out-of-phaze commented on code/game/objects/item.dm
> +	return
```suggestion
	if(item_flags & ITEM_FLAG_IS_BELT)
		return slot_belt_str
	return null
```
Maybe? Unsure if necessary.

2023-08-27 15:07 UTC, out-of-phaze commented on code/game/objects/item.dm
> +	return
If it is, this should probably be included in a parent call in all the others, since, for example, clipping a mask to your belt would make sense.

2023-08-28 02:22 UTC, out-of-phaze requested changes

2023-08-28 02:22 UTC, out-of-phaze commented on code/game/objects/item.dm
> +	else
As far as I know, this `else` case can never be triggered now. Either `get_associated_equipment_slots` returns null or a list. Null is checked earlier.

2023-08-28 02:26 UTC, MistakeNot4892 commented on code/game/objects/item.dm
> +	else
Good point.

2023-08-28 02:27 UTC, MistakeNot4892 commented on code/game/objects/item.dm
> +	else
Removed the checking.

2023-08-29 20:27 UTC, out-of-phaze submitted a review, later dismissed

2023-09-01 13:39 UTC, out-of-phaze approved these changes

2023-09-02 14:10 UTC, merged