Vox bodytype updates.
NebulaSS13/Nebula pull request #3293
Opened 2023-08-27 10:58 UTC by MistakeNot4892

## Description of changes
- Finishes implementing servitor voxform (alt appearance).
- Adds alchemist voxform (aesthetic variation only).
- Adds a Set Bodytype helper to VV.
- Adds bodytype category checking to sprite accessories and renames ambiguous body flag checking.
- Adds basic icon validation to sprite accessories.
- Sets UIDs on the sprite accessories decls and enforces them.

## Why and what will this PR improve
- Pulls UID changes out of #3191.
- Somewhat more rigorous accessory testing, more debugging options for bodytypes.
- Vox servitor icons aren't just sitting in the codebase unused.

## Authorship
Myself.

## Changelog
:cl:
add: Vox now have two additional bodytypes.
/:cl:

2023-08-29 21:04 UTC, out-of-phaze requested changes
First pass caught some preferences stuff that should probably be simplified using helpers. I haven't gone through and replaced existing versions of this, but new/modified ones should definitely use the helpers instead of duplicating the code.

2023-08-29 21:04 UTC, out-of-phaze commented on code/modules/mob/new_player/preferences_setup.dm
> +	var/decl/species/mob_species = get_species_by_key(species || global.using_map.default_species)
```suggestion
	var/decl/species/mob_species = get_species_decl()
```

2023-08-29 21:04 UTC, out-of-phaze commented on code/modules/mob/new_player/preferences_setup.dm
> +	var/decl/bodytype/mob_bodytype = mob_species?.get_bodytype_by_name(bodytype) || mob_species?.default_bodytype || GET_DECL(global.using_map.default_bodytype)
```suggestion
	var/decl/bodytype/mob_bodytype = get_bodytype_decl()
```
`using_map.default_bodytype` is deprecated as far as I know. IMO it should be removed and all uses of it replaced with the default species' default bodytype.

2023-08-29 21:04 UTC, out-of-phaze commented on code/modules/mob/new_player/preferences_setup.dm
> +	var/decl/species/mob_species = get_species_by_key(species || global.using_map.default_species)
```suggestion
	var/decl/species/mob_species = get_species_decl()
```

2023-08-29 21:04 UTC, out-of-phaze commented on code/modules/mob/new_player/preferences_setup.dm
> +	var/decl/bodytype/mob_bodytype = mob_species?.get_bodytype_by_name(bodytype) || mob_species?.default_bodytype || GET_DECL(global.using_map.default_bodytype)
```suggestion
	var/decl/bodytype/mob_bodytype = get_bodytype_decl()
```

2023-08-30 11:36 UTC, MistakeNot4892 commented on code/modules/mob/new_player/preferences_setup.dm
> +	var/decl/bodytype/mob_bodytype = mob_species?.get_bodytype_by_name(bodytype) || mob_species?.default_bodytype || GET_DECL(global.using_map.default_bodytype)
It doesn't actually _have_ any other uses lol.

2023-09-13 17:48 UTC, out-of-phaze approved these changes, later dismissed
I still kind of think `check_gender` should be obliterated, because of the issues with it we discussed on Discord, but I won't block over it. Same with the unit test concern I raised, though if you want to fix that one before merge that's fine too.

2023-09-13 17:48 UTC, out-of-phaze commented on code/unit_tests/icon_tests.dm
> +			var/sat_name = "[initial(sat.name)] ([initial(sat.uid)])"
It seems like this part of the test is checking if there are any sprite accessories with the same UID and name. Isn't UID checking already done elsewhere? I don't see the purpose of this check if we're grouping by `name (uid)`—grouping by name at least makes sense for display purposes.

2023-09-15 00:07 UTC, MistakeNot4892 commented on code/unit_tests/icon_tests.dm
> +			var/sat_name = "[initial(sat.name)] ([initial(sat.uid)])"
Looks like this whole test is obviated by `validate()`.

2023-09-18 00:26 UTC, out-of-phaze approved these changes

2023-09-21 13:20 UTC, merged