Removing the hattable extension, replacing with inv slot.
NebulaSS13/Nebula pull request #3302
Opened 2023-09-06 13:51 UTC by MistakeNot4892

Opening for the diff, DNM.

## Description of changes
- Removes the hattable extension.
- Replaces it with inventory slots.
- Reworks various overlay handling procs to allow /mob/living to render equipment overlays.
- Reworks mousedrop adjacency to allow for dropping arbitrary items onto screen elements.
- Adds bodytypes to various mobs and removes an ishuman() check for equipment adjustment purposes.
- Slightly reworks item client screen presence to be more consistent for nonhumans.
- Swaps item holding dex flag for item equip dex flag in equip logic.

## Why and what will this PR improve
Cleaner/more consistent inventory code for mobs.
Working towards generalized inventory interactions for nonhumans.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-04 15:10 UTC, MistakeNot4892 commented
This is ready to go.

2023-10-23 17:19 UTC, out-of-phaze requested changes, later dismissed

2023-10-23 17:19 UTC, out-of-phaze commented on code/game/objects/item_mob_overlay.dm
> +	var/decl/bodytype/root_bodytype = H.get_bodytype()
```suggestion
	var/decl/bodytype/root_bodytype = user_mob.get_bodytype()
```
Unnecessary cast, plus the `ishuman()` was removed.

2023-10-24 00:49 UTC, MistakeNot4892 commented on code/game/objects/item_mob_overlay.dm
> +	var/decl/bodytype/root_bodytype = H.get_bodytype()
Fixed in another PR.

2023-11-01 19:50 UTC, out-of-phaze approved these changes

2023-11-02 22:47 UTC, merged