Fixes dispenser refilling
NebulaSS13/Nebula pull request #3306
Opened 2023-09-09 04:28 UTC by NataKilar

## Description of changes
Fixes refilling chemical dispensers (water tanks, sulphuric acid dispensers etc.) by returning FALSE to the dispenser refill proc if the refilling cap is open.
## Changelog
:cl:
bugfix: Fixed water tanks being unable to be refilled
/:cl:

2023-09-09 13:40 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers.dm
> +	if(!istype(target) || target.atom_flags & ATOM_FLAG_OPEN_CONTAINER)
`(target.atom_flags & ATOM_FLAG_OPEN_CONTAINER)`

2023-09-09 13:40 UTC, MistakeNot4892 requested changes
Chuck parens on there and I'll approve

2023-09-10 08:42 UTC, MistakeNot4892 approved these changes
Needs squash merge.

2023-09-10 18:27 UTC, out-of-phaze approved these changes

2023-09-10 18:27 UTC, merged