Breaking up some of lefthand.dmi and righthand.dmi.
NebulaSS13/Nebula pull request #3316
Opened 2023-09-12 14:21 UTC by MistakeNot4892

## Description of changes
Deletes several unused states from lefthand/righthand.dmi.
Reworks various items to use the single icon system instead.

## Why and what will this PR improve
Someday I want to destroy righthand.dmi and lefthand.dmi and this is needed for that.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-19 18:37 UTC, out-of-phaze reviewed
Did you make sure to test that syringe filling overlays still work? Without IDB, it's hard to check that without checking out the branch and running it, which is kind of a pain.

2023-10-19 18:37 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/syringe_gun.dm
> +		var/mutable_appearance/MA = syringe.appearance
Are pixel_x and pixel_y cleared? Would they even apply anyway?

2023-10-19 18:37 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	abstract_type = /obj/item/chems/hypospray
Isn't it convention for `abstract_type` to come first, i.e. before `name =`? That makes it clearer that it's abstract.

2023-10-19 22:21 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	abstract_type = /obj/item/chems/hypospray
I wasn't aware we had a convention for that

2023-10-20 03:49 UTC, MistakeNot4892 commented on code/modules/projectiles/guns/launcher/syringe_gun.dm
> +		var/mutable_appearance/MA = syringe.appearance
Fixed.

2023-10-20 03:49 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	abstract_type = /obj/item/chems/hypospray
Per Discord, leaving it where it is, but I readded a comment.

2023-10-23 16:49 UTC, out-of-phaze requested changes

2023-10-23 16:49 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/syringe_gun.dm
> +		var/mutable_appearance/MA = syringe.appearance
```dm
	if(randpixel)
		pixel_z = randpixel //an idea borrowed from some of the older pixel_y randomizations. Intended to make items appear to drop at a character
```
Looks like pixel_z should also be cleared. :(

2023-10-26 18:41 UTC, out-of-phaze approved these changes

2023-10-27 21:45 UTC, merged