Fix duplicate table removal and logging.
NebulaSS13/Nebula pull request #3338
Opened 2023-09-13 21:24 UTC by out-of-phaze

## Description of changes
Fixes a runtime in the code for removing duplicate tables, due to update_icon() being called on a deleted table.
Replaces the bespoke table duplicate removal code with what's already used for lattices and catwalks.

## Why and what will this PR improve
Fixes a runtime and improves code quality.

2023-09-13 23:53 UTC, MistakeNot4892 commented on code/game/objects/structures/tables.dm
> +		for(var/obj/structure/table/table in range(oldloc, 1))
I thought the runtime was coming from a destroyed table trying to call update_icon() on an uninitialized neighbor, rather than a qdeleted neighbor.

2023-09-13 23:58 UTC, MistakeNot4892 requested changes
Code looks good otherwise, just curious about that qdeleted vs uninitialized issue.

2023-09-14 04:25 UTC, out-of-phaze commented on code/game/objects/structures/tables.dm
> +		for(var/obj/structure/table/table in range(oldloc, 1))
iirc it was, then I changed it to use the macro and it was trying to call it on a qdeleted neighbor instead, I think?

2023-09-14 08:17 UTC, MistakeNot4892 approved these changes

2023-09-14 18:15 UTC, merged