Modernize unsim air comparisons and allow Test_ZAS_Connection for nonsim turfs
NebulaSS13/Nebula pull request #3341
Opened 2023-09-13 21:35 UTC by out-of-phaze

## Description of changes
Modernizes unsim air comparisons to actually compare the airmixes rather than just the initial gas vars.
Removes unnecessary typechecks in Test_ZAS_Connection so that nonsim turfs participating in zones can be checked.

## Why and what will this PR improve
Fix Test_ZAS_Connection for nonsim turfs participating in zones.
Improves unsim air comparisons to be more accurate.

2023-09-13 23:45 UTC, MistakeNot4892 commented on code/modules/ZAS/Diagnostic.dm
>  	if(!istype(other_turf))
This should probably be `!other_turf?.zone` or something along those lines if the expectation is that it's participating in ZAS.

2023-09-13 23:46 UTC, MistakeNot4892 requested changes
Not sure if my comment is the case or not.

2023-10-07 15:58 UTC, out-of-phaze commented on code/modules/ZAS/Diagnostic.dm
>  	if(!istype(other_turf))
it isn't, I used this to check why nonsim turfs weren't forming unsim edges on Tether

2023-10-07 21:17 UTC, MistakeNot4892 approved these changes

2023-10-08 22:13 UTC, merged