Port floor lamps from Polaris
NebulaSS13/Nebula pull request #3346
Opened 2023-09-13 21:49 UTC by out-of-phaze

## Description of changes
Ports floor lamps from Polaris, with substantial rewriting for better code quality.

## Why and what will this PR improve
Polaris parity, plus they look neat.

## Authorship
Polaris/Virgo for the sprites, some of the var values, and the initial code. Me for the modifications/rewriting/improvements.

2023-09-13 23:55 UTC, MistakeNot4892 commented on code/modules/power/floorlamp.dm
> +		return switch_state && !(stat & NOPOWER)
`operable()` instead of `!(stat & NOPOWER)` possibly?

2023-09-13 23:56 UTC, MistakeNot4892 commented on code/modules/power/floorlamp.dm
> +	else if(IS_SCREWDRIVER(held_item))
Not blocking, but it would be good if new inclusions could use `do_tool_interaction` instead of the typecheck pattern. At some point we're going to need to go back and change all of these to use it so the tool quality system is actually respected.

2023-09-13 23:57 UTC, MistakeNot4892 commented on code/modules/power/floorlamp.dm
> +	set_scale(1.2, 1.2) // i hate this
I hate this also, why not just a bigger icon?

2023-09-13 23:57 UTC, MistakeNot4892 requested changes
Only the `operable()` comment is potentially blocking.

2023-09-14 04:24 UTC, out-of-phaze commented on code/modules/power/floorlamp.dm
> +	set_scale(1.2, 1.2) // i hate this
no sprites for it + on polaris/virgo there's just no visual difference at all, so even a scale is better than nothing imo

2023-09-14 16:57 UTC, out-of-phaze commented on code/modules/power/floorlamp.dm
> +		return switch_state && !(stat & NOPOWER)
c.f. the code for normal lights
```dm
/obj/machinery/light/proc/expected_to_be_on()
	var/area/A = get_area(src)
	return A?.lightswitch && !(stat & NOPOWER)
```

2023-09-14 18:21 UTC, PlayerDeer commented
Dang my sprites are sick 👍 good PR

2023-09-16 08:27 UTC, MistakeNot4892 approved these changes

2023-09-17 12:48 UTC, merged