Upstreams fixes from Lighthouse and Shiptesting modpack branch
NebulaSS13/Nebula pull request #3397
Opened 2023-09-30 17:22 UTC by out-of-phaze

## Description of changes
- Fixes the auto-generation of hydrate UIDs, which just outright did not work (that's why the hydrate UIDs are manually set).
- Fixes/expands the disposals connection unit test
  - Adds exceptions to disposals connection map unit tests, since we don't have down-facing disposals outlets.
  - Stops unit test disposalholders from merging if they stall, so it's clearer that they've stalled.
  - Doubles the step limit for disposalholders, since some maps I was testing were too large (!!!) for the current one.
- Prevents the vault cash freezer closet from overfilling by correcting the w_class calculation.
- Adds more diagnostics to the air alarm connection unit test, to prevent more Desperado-esque frustration.
- Disables transmitter latency for unit testing, which should prevent the Desperado issue from ever happening again even with a boatload of timers.
- Makes camera tag autogeneration use sequential_id instead of a bespoke system.
- Allows holodeck control circuitboards to create subtypes of holodeck control computers, useful for maps with multiple holodecks.
- Makes heat exchange pipes' set_dir override return parent. Also makes it use the general initialize_directions helper directly.
- Fixes the slime scanner and slime grappling messages.
- Fixes edge mimic turfs doubling their air/gas overlay.
- Fixes not being able to wear PDAs (and other items) on your belt slot.

## Why and what will this PR improve
Fixes a bunch of issues I caught/solved downstream.

2023-09-30 18:37 UTC, comma approved these changes, later dismissed

2023-10-01 00:22 UTC, MistakeNot4892 requested changes
Otherwise looks good.

2023-10-01 00:22 UTC, MistakeNot4892 commented on mods/content/xenobiology/slime/_slime.dm
> +	var/prey = feeding_on.resolve()
`feeding_on?.resolve()` would avoid runtimes here.

2023-10-01 00:26 UTC, out-of-phaze commented on mods/content/xenobiology/slime/_slime.dm
> +	var/prey = feeding_on.resolve()
for some reason i thought feeding_on could never be null here, but maybe that was before i removed the `if(feeding_on)` check

2023-10-01 02:21 UTC, MistakeNot4892 approved these changes

2023-10-02 01:29 UTC, merged