Game modes are now decls.
NebulaSS13/Nebula pull request #3410
Opened 2023-10-04 05:21 UTC by MistakeNot4892

## Description of changes
- `/datum/game_mode` -> `/decl/game_mode`
- `config_tag` -> `uid`
- Various procs replaced with decl procs.

## Why and what will this PR improve
Less bespoke code, easier interaction with CI and other systems.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-04 11:12 UTC, comma submitted a review, later dismissed

2023-10-04 17:22 UTC, out-of-phaze requested changes
The `gamemode_cache` list and references to it should be removed entirely, I think, since it's no longer populated.

2023-10-04 17:22 UTC, out-of-phaze commented on code/modules/admin/verbs/cinematic.dm
>  			override = gamemode_cache[name]
`gamemode_cache` should be removed.

2023-10-04 22:43 UTC, MistakeNot4892 commented on code/modules/admin/verbs/cinematic.dm
>  			override = gamemode_cache[name]
Beh I thought I did. Cherrypick fail.

2023-10-06 14:13 UTC, Andrew-Fall commented on code/game/gamemodes/game_mode_latespawn.dm
> +	var/max_autotraitor_delay = 12000 // Approx 20 minutes.
While your here could you change these to MINUTES

2023-10-11 16:09 UTC, out-of-phaze approved these changes

2023-10-11 16:09 UTC, out-of-phaze commented on code/controllers/configuration.dm
> +		if (!game_mode.uid || !(game_mode.uid in modes))
`!game_mode.uid` is probably unnecessary since gamemodes have `DECL_FLAG_MANDATORY_UID`. Non-blocking.

2023-10-11 16:09 UTC, out-of-phaze commented on code/controllers/subsystems/ticker.dm
> +	var/master_mode = "extended"    //The underlying game mode (so "secret" or the voted mode). Saved to default back to previous round's mode in case the vote failed. This is a uid.
Technically I don't think `"secret"` is a uid. Non-blocking.

2023-10-15 23:07 UTC, merged

2023-10-15 23:38 UTC, MistakeNot4892 commented on code/controllers/subsystems/ticker.dm
> +	var/master_mode = "extended"    //The underlying game mode (so "secret" or the voted mode). Saved to default back to previous round's mode in case the vote failed. This is a uid.
Oh belatedly that was a find and replace mistake. Oops.