Trader cleanup and consistency pass.
NebulaSS13/Nebula pull request #3425
Opened 2023-10-10 12:13 UTC by MistakeNot4892

## Description of changes
- Traders use defines for their string stuff.
- Traders no longer have malformed or missing string values.
- Trader lists are formatted nicely.
- Traders have a unit test for their speech stuff.

## Why and what will this PR improve
Trader code keeps distracting me whenever other projects touch the goods lists. This should stop that.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-10 19:04 UTC, comma approved these changes, later dismissed

2023-10-11 17:46 UTC, out-of-phaze requested changes
Just some nitpicks about messages. Non-blocking, so if you don't want to bother, just say so and I'll approve and merge.

2023-10-11 17:46 UTC, out-of-phaze commented on code/datums/trading/_trader.dm
> +	return get_response(TRADER_BRIBE_REFUSAL, "How about.... no?")
```suggestion
	return get_response(TRADER_BRIBE_REFUSAL, "How about... no?")
```
Why the extra `.`? An ellipsis is `...`.

2023-10-11 17:46 UTC, out-of-phaze commented on code/datums/trading/_trader.dm
> +	return get_response(TRADER_BRIBE_REFUSAL, "How about.... no?")
```suggestion
	return get_response(TRADER_BRIBE_REFUSAL, "How about... no?")
```

2023-10-15 18:14 UTC, out-of-phaze approved these changes, later dismissed

2023-10-17 20:02 UTC, out-of-phaze submitted a review, later dismissed

2023-10-19 01:15 UTC, out-of-phaze approved these changes

2023-10-19 08:46 UTC, merged