Screen object unification.
NebulaSS13/Nebula pull request #3446
Opened 2023-10-16 03:58 UTC by MistakeNot4892

## Description of changes
- Unifies a lot of /obj/screen functionality on the base object.
- Centralizes the code in its own folder.
- Does a lot of cleanup and refactoring in the process of updating screen objects to use handle_click() etc.

## Why and what will this PR improve
Screen object code is a mess and this cleans it up significantly. Will help a lot with the eventual HUD datum rewrite I have in the pipeline.

## Testing
- [x] Intent selector
- [x] Zone selector
- [x] Inventory
- [x] Hands
- [x] Make sure gear highlights didn't get clobbered
- [x] Exosuits
- [x] Constructs
- [x] Robots
- [x] pAIs
- [x] AIs
- [x] Spells
- [x] Ability master
- [x] Action buttons
- [x] Gun fire mode selector
- [x] Credits
- [x] Global HUDs (NVG, thermals)
- [x] Pain/welding overlays
- [x] Radials
- [x] Click catchers
- [x] Cataloguer overlay
- [x] Holomaps
- [x] Storage
- [x] Probably other stuff I will remember later

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-21 00:38 UTC, MistakeNot4892 commented
Tested and ready to go.

2023-12-13 23:09 UTC, PsyCommando commented
I just have a slight comment/request. 
The action bar used to react to the incapacitation state of the character, so when they'd go unconscious or something the buttons would be grayed out and translucent.  (It also used to get stuck like that cause state updates didn't cause the ui to update consistently. But that's something else XD )

Maybe that feature could be built-in the base screen object? So you could just toggle it on the elements you want to go disabled when they can't be used?

2023-12-13 23:21 UTC, MistakeNot4892 commented
Sorry, that's out of scope for this.
I am generalizing it a bit in the HUD rewrite though.

2023-12-14 19:41 UTC, PsyCommando commented
> Sorry, that's out of scope for this. I am generalizing it a bit in the HUD rewrite though.

That's all good!

2024-01-04 06:42 UTC, out-of-phaze requested changes
Partial review, hasn't made any progress in the past few weeks so I'll probably give the rest of the PR a cursory look-over and then approve.

2024-01-04 06:42 UTC, out-of-phaze commented on code/_onclick/hud/deity.dm
> +	src.other = list()
Is there a reason to use `src` for these?

2024-01-04 06:42 UTC, out-of-phaze commented on code/_onclick/hud/screen/screen_intent.dm
> +/obj/screen/intent/deity
I don't know how to feel about this being separated from other deity code. I thought we were going to move gamemode content to modpacks?

2024-01-04 06:42 UTC, out-of-phaze commented on code/_onclick/hud/screen/screen_intent.dm
> +	name = "" //Don't want them to be able to actually right click it.
This might just make its name default to `deity_marker`, the last part of the path, I'm unsure. I know it does this for a `null`/unset name...

2024-01-04 06:45 UTC, MistakeNot4892 commented on code/_onclick/hud/screen/screen_intent.dm
> +/obj/screen/intent/deity
Sure, but until we do, I wanted to keep the screen stuff all in the same spot.

2024-01-04 06:46 UTC, MistakeNot4892 commented on code/_onclick/hud/screen/screen_intent.dm
> +	name = "" //Don't want them to be able to actually right click it.
This is the existing code. I don't know offhand if this works or if you need to do `verbs.Cut()` as well.

2024-01-04 06:51 UTC, out-of-phaze approved these changes

2024-01-05 06:52 UTC, merged