Cleaning up ID and PDA equipping.
NebulaSS13/Nebula pull request #3451
Opened 2023-10-17 12:40 UTC by MistakeNot4892

## Description of changes
Fixes https://github.com/ScavStation/ScavStation/issues/799. More specifically:
- `equip_rank` -> `equip_job_title` to disambiguate from military rank datums, which are also passed around these procs.
- `equip()` to `equip_outfit()` and `equip_job()` for searchability.
- `equip_id` override merged into base proc.
- `equip_id` calls unified on the outfit datum in the `equip_outfit` chain.
- `equip_outfit` arguments somewhat simplified/cleaned up.
- `setup_account()` moved prior to outfit dressing.

## Why and what will this PR improve
Fixes issues with equip ordering and ID not having assignment or account info set sometimes.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-10-21 02:46 UTC, out-of-phaze commented on code/datums/outfits/outfit.dm
> +/decl/hierarchy/outfit/proc/equip_outfit(mob/living/carbon/human/H, assignment, equip_adjustments, datum/job/job, datum/mil_rank/rank)
Do alt titles just not get added to the ID anymore?

2023-10-21 03:10 UTC, MistakeNot4892 commented on code/datums/outfits/outfit.dm
> +/decl/hierarchy/outfit/proc/equip_outfit(mob/living/carbon/human/H, assignment, equip_adjustments, datum/job/job, datum/mil_rank/rank)
I was using `rank` instead of `job.title`, fixed now.

2023-10-23 16:39 UTC, out-of-phaze requested changes

2023-10-23 16:39 UTC, out-of-phaze commented on code/datums/outfits/outfit.dm
> +		W.position = job.title
This still won't factor in the selected alt title, will it?

2023-10-24 00:23 UTC, MistakeNot4892 commented on code/datums/outfits/outfit.dm
> +		W.position = job.title
Alt title is `assignment`.

2023-10-24 01:09 UTC, out-of-phaze approved these changes

2023-10-27 03:06 UTC, merged