Rough pass on removing isSynthetic [DNM]
NebulaSS13/Nebula pull request #3472
Opened 2023-10-27 08:39 UTC by MistakeNot4892

## Description of changes
Kills isSynthetic(). Opening this for input/review, it is in no state for a merge currently.

## Why and what will this PR improve
isSynthetic() is a holdover from the previous attempt at FBP and is pretty much redundant in view of the new bodytype system. Getting rid of it will make various systems more flexible and available to nonhuman synthetics and partial cyborgs.

## Authorship
Myself and @out-of-phaze.

## Changelog
Hopefully nothing player-facing.

2023-11-21 22:27 UTC, PsyCommando reviewed
Just a couple things I had some ideas on.

2023-11-21 22:27 UTC, PsyCommando commented on code/_onclick/hud/human.dm
> +	if(GET_INTERNAL_ORGAN(target, BP_CELL))
So, I was thinking. The code that modifies/adds UI components depending on the kind of organ in the mob could probably be transformed into some generic way for organs to specify a UI element to add to the player ui? So you don't have to have those checks for specific robot organs?

2023-11-21 22:27 UTC, PsyCommando commented on code/datums/repositories/crew/binary.dm
> +	var/obj/item/organ/internal/cell/cell = H.should_have_organ(BP_CELL) && GET_INTERNAL_ORGAN(H, BP_CELL)
Maybe an accessor on the /mob level to get the mob's vitals could be better, instead of having to dig for the right organ to get data from in the crew data stuff?

2023-11-21 22:27 UTC, PsyCommando commented on code/game/machinery/rechargestation.dm
> +		if(H.should_have_organ(BP_CELL))
Maybe this proc could just use the base implementation of get_cell()? Since it's fairly low level. Mobs could just return the right thing themselves instead of having that big if/else type check.

2023-11-21 22:27 UTC, PsyCommando commented on code/game/objects/items/weapons/implants/implants/imprinting.dm
> +		if(!B || BP_IS_PROSTHETIC(B) || BP_IS_CRYSTAL(B))
I wonder if we couldn't generalize implant requirements and handle them in the base implant class? Cause most of them are just checking if an organ exist and what flags it has?

2023-11-21 22:27 UTC, PsyCommando commented on code/modules/client/preferences.dm
> +	if(!character.get_bodytype().is_robotic)
Will this error? Cause, there's no return type or ``:`` operator, and is_robotic wouldn't be defined?

2023-11-21 22:27 UTC, PsyCommando commented on code/modules/emotes/definitions/visible.dm
> +	. = ..() && user.check_has_mouth() && user.should_have_organ(BP_STOMACH)
Maybe some organs could have a list of emotes they can provide to the organ holder instead? So no need to do checks like that? For instance if a critter has a stomach, and it has the emote for vomiting listed, it's pretty safe to say there's a way for the vomit to come out and so on?

2023-11-21 22:27 UTC, PsyCommando commented on code/modules/events/ion_storm.dm
> +		if(brain && !BP_IS_PROSTHETIC(brain))
Maybe mobs could implement a proc to determine if they have anything vulnerable to a given damage type? Like EMP, Pain, Oxygen deprivation, Toxin, etc..

2023-11-22 07:15 UTC, MistakeNot4892 commented on code/modules/client/preferences.dm
> +	if(!character.get_bodytype().is_robotic)
`get_bodytype()` always returns an instance of /decl/bodytype - the linter is even aware of this thanks to RETURN_TYPE - and chaining calls like this is functionally identical to `:`. Might need a nullcheck though.

2023-11-24 03:47 UTC, out-of-phaze requested changes
Requesting changes from a partial review I did a few weeks ago. I'll start over with a blank slate once I get back to my computer.

2023-11-24 03:47 UTC, out-of-phaze commented on code/datums/repositories/crew/binary.dm
> +		crew_data["alert"] = cell.percent() < 10
What if the cell is destroyed by an EMP?
```suggestion
    if(H.should_have_organ(BP_CELL))
	    var/obj/item/organ/internal/cell/cell = H.get_organ(BP_CELL, /obj/item/organ/internal/cell)
		crew_data["alert"] = !cell || (cell.percent() < 10)
```
Using `get_organ()` instead of `GET_INTERNAL_ORGAN()` lets us use `!cell` instead of `!istype(cell)` by taking advantage of the typecheck in `get_organ()`.

2023-11-24 03:47 UTC, out-of-phaze commented on code/datums/traits/radiation_hardened.dm
> +	description = "While this creature can become radioactive, it will not suffer ill effects from being so."
```suggestion
	description = "While this creature can become irradiated, it will not suffer ill effects from being so."
```

2023-11-24 03:47 UTC, out-of-phaze commented on code/game/machinery/rechargestation.dm
Line 203 is redundant now unless there's some way to get a cell organ even if `should_have_organ(BP_CELL)` returns false. I guess for augments that could be true, but I don't think it's the case for cells.

2023-11-24 03:47 UTC, out-of-phaze commented on code/modules/species/species_bodytype.dm
> +	var/radiation_mod = 1 // Not as biologically fragile as meatboys.
```suggestion
	var/radiation_mod = 1
```
Comment doesn't apply here, it looks like it was originally for the Ascent Alates?

2024-02-11 11:22 UTC, MistakeNot4892 commented
Will revisit/reopen this in single-PRs as they are completed. Have backed it up as `wip/issythetic_removal` on my fork.

2024-02-11 11:22 UTC, closed without merging