Adding unit tests for turf icons and random spawner icons.
NebulaSS13/Nebula pull request #3479
Opened 2023-10-31 13:31 UTC by MistakeNot4892

Noticed a ton of missing icons in #3478 so splitting it off into its own PR.

2023-10-31 15:17 UTC, out-of-phaze requested changes

2023-10-31 15:17 UTC, out-of-phaze commented on code/game/machinery/doors/airlock_subtypes.dm
> +	return ..()
```suggestion
	queue_icon_update()
	return ..()
```
So that it actually has the open icon state.

2023-11-01 00:15 UTC, MistakeNot4892 commented on code/game/machinery/doors/airlock_subtypes.dm
> +	return ..()
Generalized it to door level and added an icon update queue to airlocks.

2023-11-06 22:10 UTC, out-of-phaze approved these changes

2023-11-19 00:35 UTC, merged