Fixes Taj considering eyes to be a limb.
NebulaSS13/Nebula pull request #3483
Opened 2023-11-02 05:40 UTC by MistakeNot4892

2023-11-02 13:56 UTC, out-of-phaze requested changes

2023-11-02 13:56 UTC, out-of-phaze commented on mods/species/bayliens/tajaran/datum/species_bodytypes.dm
> +	)
```suggestion
```
This is the same as the default.

2023-11-02 22:47 UTC, out-of-phaze approved these changes

2023-11-04 10:59 UTC, MistakeNot4892 commented
Selfmerging this as it's so tiny and I want to get staging started.

2023-11-04 10:59 UTC, merged