Implements can_be_injected_by().
NebulaSS13/Nebula pull request #3501
Opened 2023-12-01 09:50 UTC by MistakeNot4892

## Description of changes
@PsyCommando pointed out this proc was unused earlier, so I reviewed injection code and added it where I think it was intended to go.

## Why and what will this PR improve
Slightly cleaner code.

## Authorship
@PsyCommando found the issue, I did the code.

## Changelog
Nothing player-facing.

2023-12-01 09:50 UTC, MistakeNot4892 commented
Random pike commit too apparently.

2023-12-01 17:05 UTC, out-of-phaze requested changes

2023-12-01 17:05 UTC, out-of-phaze commented on code/modules/clothing/masks/smokable.dm
> +	return TRUE
Uh, why should this differ from `/atom/movable/can_be_injected_by(var/atom/injector)`? Now this returns true regardless of adjacency or free space. (Free space is checked in the one place `can_be_injected_by()` is called, so if it's unnecessary in the `/atom/movable` override, it should probably be removed from there.)

2023-12-01 17:05 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/familiars/familiars.dm
> +	offset_overhead_text_x = 16
I assume you didn't mean to include the pike commit?

2023-12-01 21:57 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/familiars/familiars.dm
> +	offset_overhead_text_x = 16
I didn't but it's also one line so I don't really care :U

2023-12-02 00:54 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/familiars/familiars.dm
> +	offset_overhead_text_x = 16
I think when I originally wrote this comment you hadn't mentioned it and then when I posted it in the morning you had. Sorry! Yeah, it's fine.

2023-12-02 01:56 UTC, MistakeNot4892 commented on code/modules/clothing/masks/smokable.dm
> +	return TRUE
Did some work on that, should be okay now.

2023-12-02 03:05 UTC, out-of-phaze approved these changes

2023-12-04 17:38 UTC, merged