Making tail icon gen a little less brittle.
NebulaSS13/Nebula pull request #3507
Opened 2023-12-08 23:37 UTC by MistakeNot4892

## Description of changes
- Reworks tail icon retrieval to be a bit less brittle in case of missing or broken values.
- Removes the trailing `_s` from static tail states.
- Removes the redundant `tail_animation` icon var since everything can use the tail icon.
- Deletes `icons/effects/species.dmi` as it is unused and misleading.
- Adds tail validation to bodytypes.
- Somewhere amongst all this, fixes tails not rendering on staging.

## Why and what will this PR improve
make tail work better

## Authorship
Myself.

## Changelog
Nothing player-facing.

2023-12-13 18:41 UTC, out-of-phaze requested changes, later dismissed

2023-12-13 18:41 UTC, out-of-phaze commented on code/modules/species/species_bodytype.dm
> +/decl/bodytype/proc/get_typical_user_species()
If this is only used for validation, I'd like that to be specified—something like `get_validation_user_species()` instead.

2023-12-13 19:28 UTC, MistakeNot4892 commented
Why the heck did I commit this straight to `staging`.

2023-12-29 04:08 UTC, out-of-phaze approved these changes

2023-12-31 07:01 UTC, merged