Material Melting and Boiling Update
NebulaSS13/Nebula pull request #3525
Opened 2023-12-12 00:18 UTC by CheeseDogg0

## Description of changes
Adds and updates melting and boiling points to various materials, including most metals, elemental materials, a couple acids, toxins, glasses and minerals.

## Why and what will this PR improve
Brings materials more inline with expected and realistic melting and boiling points.

## Authorship
Me, myself, and I. 

## Changelog
:cl:
add: Added melting and boiling points to some materials missing them
tweak: Changed some of the more ridiculous numbers to bring them more in line with real life
/:cl:

2023-12-12 00:22 UTC, MistakeNot4892 commented on code/modules/materials/definitions/liquids/materials_liquid_solvents.dm
> +	melting_point = 284
Is the melting point of sulfuric acid really 10C?

2023-12-12 00:26 UTC, MistakeNot4892 commented on code/modules/materials/definitions/liquids/materials_liquid_solvents.dm
> +	boiling_point = 193
Boils at -80C??

2023-12-12 00:27 UTC, MistakeNot4892 commented on code/modules/materials/definitions/liquids/materials_liquid_solvents.dm
> +	melting_point = 284
Apparently yes.

2023-12-12 00:31 UTC, MistakeNot4892 commented on code/modules/materials/definitions/solids/materials_solid_glass.dm
> +	melting_point = T0C + 1400
Minor consistency point but I feel like we should either be using T0C/CELCIUS for every temperature value on materials, or for none of them.

2023-12-12 09:39 UTC, comma commented on code/modules/materials/definitions/solids/materials_solid_metal.dm
> +	ignition_point = null
Can set this on `/decl/material/solid/` above instead of setting to null on every subtype

2023-12-13 00:41 UTC, MistakeNot4892 commented on code/modules/materials/definitions/solids/materials_solid_glass.dm
> +	melting_point = T0C + 1650
As mentioned I'm worried that the SM core fires will hit this temperature pretty quickly.

2023-12-13 07:01 UTC, MistakeNot4892 requested changes
Per the comments, there's some values that look erroneous or have some potential problems.

2023-12-15 03:17 UTC, CheeseDogg0 commented
Editied the files as requested

2023-12-15 08:50 UTC, MistakeNot4892 submitted a review, later dismissed

2023-12-15 23:25 UTC, CheeseDogg0 commented
Removed Accelerant values from minerals without ignition points

2023-12-16 01:30 UTC, MistakeNot4892 approved these changes

2023-12-18 15:00 UTC, merged