Various map object from Polaris map conversion.
NebulaSS13/Nebula pull request #3558
Opened 2024-01-06 18:11 UTC by MistakeNot4892

## Description of changes
Adds various objects (and repaths a few) used for the Polaris/Crux maps.

- Adds smartfridges for produce and material stacks.
- Adds box of flares.
- Adds several towel subtypes.
- Adds a random pill bottle spawner.
- Adds a marble bench subtype.
- Adds various job closets (pilot, medical L2, xenoflora, sidearm cabinet)
- Adds non-cargo exotic seed crate.
- Adds some modular computer presets.
- Adds a sugar-iron pill bottle.

## Why and what will this PR improve
Adds generally useful mapping objects.

## Authorship
Much of the new object code is adapted from Polaris.

## Changelog
Nothing player-facing hopefully.

2024-01-06 21:39 UTC, out-of-phaze requested changes
After these are addressed this would be good to merge, however I'm going to be a little nitpicky. Can you add a file named something like `3558_lowercase_closets.txt` in `/tools/map_migrations` (create the folder, it doesn't exist upstream) with the contents
```
/obj/structure/closet/secure_closet/CMO : /obj/structure/closet/secure_closet/cmo{@OLD}
/obj/structure/closet/secure_closet/RD : /obj/structure/closet/secure_closet/research_director{@OLD}
```
in order to help downstreams apply the repaths in this PR to their own maps?

2024-01-06 21:39 UTC, out-of-phaze commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +/obj/structure/closet/walllocker/emerglocker/WillContain()
If you look at how this type is implemented on Polaris, it's basically just `/obj/structure/emergency_dispenser`. Is this change (to be an actual closet) intentional?

2024-01-06 21:39 UTC, out-of-phaze commented on code/game/turfs/flooring/flooring_shuttle.dm
> +	icon_state = "plating"
Why is this necessary? Does `/turf/simulated/floor` not work? Nothing does `istype(foo, /turf/simulated/floor/shuttle)` and there's no logic defined on this either.

2024-01-06 21:39 UTC, out-of-phaze commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> +	req_access = list(access_xenobiology)
Is this intentional, or bad copypaste?

2024-01-07 00:35 UTC, MistakeNot4892 commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> +	req_access = list(access_xenobiology)
Intentional, we have no pilot access.

2024-01-07 02:38 UTC, MistakeNot4892 commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +/obj/structure/closet/walllocker/emerglocker/WillContain()
I didn't realize the emergency dispenser existed.

2024-01-07 02:39 UTC, MistakeNot4892 commented on code/game/turfs/flooring/flooring_shuttle.dm
> +	icon_state = "plating"
It was for a shuttle, so I decided to use the same root type until I can find time to go through and work out why shuttle floors need their own type at all.

2024-01-07 02:41 UTC, out-of-phaze commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +/obj/structure/closet/walllocker/emerglocker/WillContain()
They're terribly written but almost exactly the same as the emerglocker type, just without the crowbar.

2024-01-07 11:03 UTC, out-of-phaze approved these changes, later dismissed

2024-01-08 14:41 UTC, out-of-phaze approved these changes

2024-01-08 15:59 UTC, merged