Fancy food box rework.
NebulaSS13/Nebula pull request #3601
Opened 2024-01-19 06:50 UTC by MistakeNot4892

## Description of changes
- Fancy boxes are now `/box/fancy`.
- Donut boxes are now `/fancy`.
- Egg boxes, cracker bags, and donut boxes now take overlays from their contents.
- Eggs, crackers and donuts now use the single icon system.
- Pizza boxes have been totally rewritten. 
- Pizzas use the single icon system.
- Pizzas boxes have inhands.
- Throwing a pizza may ruin it (visual only).
- You can stack pizza boxes higher than 5 but it's probably a terrible idea.

Video of pizza stuff:
https://cdn.discordapp.com/attachments/678820025355862048/1197845870255816734/dreamseeker_kQl6Ped6wK.mp4?ex=65bcbfe6&is=65aa4ae6&hm=196a370f964ee564ff96b1f51042d05072b89acf6e23718452384c3e1f0a0721&

## Why and what will this PR improve
Working towards breaking up `icons/obj/food.dmi`, this is a starting point.
Pizza stuff was a fey mood inspired by Evree posting ruined pizza photos.

## Authorship
Myself.

## Changelog
:cl:
tweak: Egg and donut boxes are slightly fancier.
tweak: Pizza stacks have been enhanced to dangerous levels.
/:cl:

2024-01-21 12:13 UTC, out-of-phaze requested changes, later dismissed
I think the number of repaths in this PR would justify adding a migration in `tools/map_migrations/`.

Other than that, it looks fine, though I'd like if there were a more generalized system for the donut box/cracker sleeve behavior where we use a `_crackerbag` or `_donutbox` state suffix on the items inside the storage. It seems that the main thing to change is the suffix and the pixel offset, though it might also have a slight performance hit to manually check `istype(foo, key_item)`... though we don't do any typechecks for donuts/crackers currently, which I suppose is fine because we check the icon for a matching state.

2024-01-21 12:39 UTC, MistakeNot4892 commented
Yeah I avoided the typecheck so that in theory other stuff added down the track can have its own overlay state without needing any additional handling. I could generalize it down to /fancy possibly.

2024-01-25 15:28 UTC, out-of-phaze approved these changes

2024-01-25 19:35 UTC, out-of-phaze submitted a review, later dismissed

2024-01-25 19:35 UTC, out-of-phaze commented on code/game/objects/items/weapons/storage/fancy/_fancy.dm
> +	/// The root type  of the key item that this "fancy" container is meant to store.
```suggestion
	/// The root type of the key item that this "fancy" container is meant to store.
```

2024-01-25 19:35 UTC, out-of-phaze commented on code/game/objects/items/weapons/storage/fancy/_fancy.dm
> +/obj/item/storage/box/fancy/proc/offset_contents_overlay(var/overlay_index, var/image/overlay)
It might be good to rename this to something like `modify_contents_overlay` in the event that something other than offsetting is done in this by a subtype.

2024-01-26 07:42 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/storage/fancy/_fancy.dm
> +/obj/item/storage/box/fancy/proc/offset_contents_overlay(var/overlay_index, var/image/overlay)
Went with `adjust` to line up with the overlay adjustment proc on mobs.

2024-01-30 03:17 UTC, out-of-phaze approved these changes

2024-01-31 20:49 UTC, merged