Brick stacks are now used to make brick walls.
NebulaSS13/Nebula pull request #3670
Opened 2024-02-10 13:46 UTC by MistakeNot4892

## Description of changes
Bricks can be used to build walls without girders.

## Why and what will this PR improve
More flexible building/crafting.

## Authorship
Myself.

## Changelog
:cl:
tweak: Bricks can now be used to build walls without girders.
/:cl:

2024-02-12 03:31 UTC, out-of-phaze requested changes, later dismissed

2024-02-12 03:31 UTC, out-of-phaze commented on code/game/turfs/simulated/wall_types.dm
> +/turf/simulated/wall/brick
should this be an abstract type? if not, it should have `icon_state = "stone"` and a material set.

2024-02-12 23:29 UTC, MistakeNot4892 commented on code/game/turfs/simulated/wall_types.dm
> +/turf/simulated/wall/brick
Moved the non-colour stuff down from sandstone.

2024-02-15 18:02 UTC, comma commented on maps/away/mining/mining-orb.dmm
> +/turf/simulated/wall/brick/sandstone,
Please add the path update thingamabob for maps

2024-02-16 00:48 UTC, comma approved these changes

2024-02-16 05:20 UTC, out-of-phaze approved these changes

2024-02-16 05:21 UTC, merged