Adding plating for food.
NebulaSS13/Nebula pull request #3681
Opened 2024-02-12 14:02 UTC by MistakeNot4892

## Description of changes
This is a bit of a fey mood and is pretty anemic/rushed, willing to take input on implementation prior to merge.

- Removes plates, trays and platters from food icons in food.dmi.
- Adds plates/platters/trays that food can be placed on.
- Removes plate and tray trash items.
- Eating food off a plate dirties the plate, which can then be washed to clean it.

## Why and what will this PR improve
Trash plates/trays has always been a bit strange. This adds a slightly more interesting element to food.

## Authorship
Myself.

## Changelog
:cl:
tweak: Plates are no longer part of food when it emerges from the microwave, and must be retrieved from the dinnerware vendor and used to plate food.
/:cl:

2024-02-12 14:21 UTC, out-of-phaze commented
> Trash plates/trays has always been a bit strange.

paper plates and styrofoam trays, come on......

also cool PR will review soon

2024-02-12 14:24 UTC, out-of-phaze requested changes, later dismissed

2024-02-12 14:24 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/food.dm
> +	if(plate)
this is causing some CI fails. i think when we qdel the food the plate should be lost too, and it should instead be dropped in, i don't know, physically_destroyed or eating code instead

2024-02-12 23:16 UTC, MistakeNot4892 commented
> paper plates and styrofoam trays, come on......


We could add like, ten pack paper plates/plastic plates from cargo. Mostly I just dislike how you can eat a sandwich you made and it spawns a dirty plate that you can do nothing with except dump into the trash.

2024-02-14 19:04 UTC, comma commented on code/modules/food/plates/_plate.dm
> +		if(!user.try_unequip(W))
Maybe move this bloc into a proc which can be also called by food attackby? Seems like it's pretty much same code as there.

2024-02-14 19:08 UTC, comma commented on mods/content/government/away_sites/icarus/icarus-1.dmm
> +/obj/item/plate,
Maybe needs one of those map path update script things?

2024-02-15 14:40 UTC, out-of-phaze approved these changes

2024-02-15 15:50 UTC, merged