carbon/alien retype and associated carbon removals.
NebulaSS13/Nebula pull request #3682
Opened 2024-02-13 02:36 UTC by MistakeNot4892

## Description of changes
- `/mob/living/carbon/alien` has been retyped to `/mob/living/simple_animal/alien`. This is a pretty coarse conversion and I expect some stuff will be broken, but I would like to get the type rework in then fix issues as they arrive, as there will be a lot more issues from the remaining carbon removals.
- Removes `iscarbon()` and all uses, retyping things to either `/mob/living` or `/mob/living/carbon/human` as appropriate.

## Why and what will this PR improve
Carbon delenda est.

## Authorship
Myself.

## Changelog
In theory, nothing player-facing.

2024-02-15 19:32 UTC, MistakeNot4892 commented
Going to split this one up into several PRs I think.

2024-02-16 02:32 UTC, MistakeNot4892 commented
Depends on #3690 #3693

2024-03-12 04:14 UTC, out-of-phaze requested changes

2024-03-12 04:14 UTC, out-of-phaze commented on code/game/gamemodes/cult/runes.dm
> +		if(M.isSynthetic())
This is maybe an unintentional buff to FBPs, though it's not like confuse runes actually get used all that often.

2024-03-12 04:14 UTC, out-of-phaze commented on code/modules/mob/living/carbon/human/human.dm
> +	LAZYSET(appearance_descriptors, "age", age.sanitize_value(val))
We use LAZYACCESS on the line before, but `age` isn't nullchecked here.

2024-03-12 21:08 UTC, out-of-phaze submitted a review, later dismissed

2024-03-13 19:55 UTC, out-of-phaze approved these changes

2024-03-13 21:25 UTC, merged