Moving vis_contents changes onto a subsystem.
NebulaSS13/Nebula pull request #3709
Opened 2024-02-20 05:54 UTC by MistakeNot4892

## Description of changes
- Adds SSvis_contents_updates and appropriate procs.
- Changes existing vis_contents macros to be procs that use the subsystem.

## Why and what will this PR improve
vis_contents manipulation is expensive and current uses on /turf will benefit from being ordered during initialization.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-02-20 06:58 UTC, MistakeNot4892 commented
Per Discord it's unclear if this is a good idea or not. It increased Crux init by 5s (85s -> 90s).
EDIT: It's unclear if this was due to vis_contents or not, more profiling might be needed.

2024-02-20 12:51 UTC, out-of-phaze requested changes
That optimization commit I linked used SSmisc_late because it runs after SSair, which lets us skip updates that will be invalidated by zone building (a lot of them, surprisingly). I'd like to see it tested running after SSair rather than before.

2024-02-20 12:51 UTC, out-of-phaze commented on code/__defines/subsystems.dm
> +#define SS_INIT_VIS_CONTENTS     2
It should init after `SS_INIT_AIR` to avoid wasted updates before zones are built.

2024-02-25 01:41 UTC, MistakeNot4892 commented on code/__defines/subsystems.dm
> +#define SS_INIT_VIS_CONTENTS     2
Done.

2024-02-25 02:46 UTC, out-of-phaze approved these changes

2024-02-27 16:11 UTC, merged