[MDB IGNORE] Converts storage to a datum (sorry)
NebulaSS13/Nebula pull request #3716
Opened 2024-02-23 01:34 UTC by MistakeNot4892

DNM, opening for CI.

## Description of changes
- Merges behavior from `/obj/item/suit/storage` `/obj/item/storage` `/obj/structure/mirror` into `/datum/extension/storage`.
- Removes/repaths storage types globally.
- Replaces typechecks etc. with extension checks.
- Adds a new contents getter, `/atom/proc/get_stored_inventory()`, which defaults to `get_contained_external_atoms()`.

## TODO
- [X] Coarse conversion.
- [X] Repaths to remove redundant types.
- [x] Test basic storage functionality.
- [x] Test pockets functionality on suits.
- [x] Allow objects to be removed from structure inventory.
- [x] Work out how to separate mirror interface and storage interactions.
- [x] Test structure functionality on mirrors.
- [x] Test pneumatic cannon functionality (or rewrite)
- [x] Consider `get_contained_external_atoms()` in storage contents helper?
- [X] Test post-conversion to datum.
- [X] Test recycler.
- [x] Fix holders not closing UI on move away from mob (throwing your backpack)
- [x] Fix storage not updating UI on qdel of item (recycler).

## Why and what will this PR improve
Less redundant storage code, more flexible storage functionality, shorter typepaths generally. Lays the groundwork for some clothing and accessory stuff I want to do down the track.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-04-03 02:59 UTC, MistakeNot4892 commented
Ready to go.

2024-04-15 22:54 UTC, out-of-phaze requested changes

2024-04-15 22:54 UTC, out-of-phaze commented on code/datums/extensions/storage/_storage.dm
> +			stop_messages = 1
Setting this parameter here is useless, was it intended to actually do something?

2024-04-15 22:54 UTC, out-of-phaze commented on code/datums/extensions/storage/_storage.dm
> +			stop_messages = 1
Also, I really think some of these checks for specific items should be moved onto procs on those items, like `/obj/item/proc/can_item_be_inserted(datum/extension/storage/storage, mob/user, stop_messages = 0)`. Not blocking, I just don't like seeing a big pile of `istype(W)`s; maybe an idea for future work?

... also, on that note, would love if we used `item` or `weapon` or `item_to_insert` etc. instead of `W`.

2024-04-15 22:54 UTC, out-of-phaze commented on code/datums/extensions/storage/subtypes_basket.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE
you have `max_storage_space` here twice

2024-04-15 22:58 UTC, MistakeNot4892 commented on code/datums/extensions/storage/_storage.dm
> +			stop_messages = 1
This is all copied code, so don't ask me to explain it. There's a bunch of shit with implants and implanters that makes no sense to me.

2024-04-15 23:11 UTC, out-of-phaze commented on code/datums/extensions/storage/_storage.dm
> +			stop_messages = 1
will go through and clean it up later then

2024-04-16 08:13 UTC, out-of-phaze approved these changes

2024-04-17 06:10 UTC, merged