Adds trenches
NebulaSS13/Nebula pull request #3750
Opened 2024-02-27 06:11 UTC by MistakeNot4892

## Description of changes

Depends on #3759
- Exterior turfs can be dug out to make trenches using a shovel.
- Trenches will cause fall damage if moved over without creeping and must be climbed into or out of to safely traverse, unless flooded.

## Why and what will this PR improve
holes

## Authorship
Myself.

## Changelog
:cl:
add: Trenches/moats can now be dug in exterior turfs. 
/:cl:

2024-02-27 17:17 UTC, out-of-phaze requested changes

2024-02-27 17:17 UTC, out-of-phaze commented on code/modules/materials/definitions/solids/materials_solid_wood.dm
> +	if(stack_type == /obj/item/stack/material/log)
`if(ispath(stack_type)) return` on lines 46-47 will make this not work. Maybe make it a separate override, or split that check up somehow? Remember we still need to check holographic and reinf_material.

2024-02-27 17:17 UTC, out-of-phaze commented on code/modules/materials/material_sheets.dm
>  			planks.add_to_stacks(user, TRUE)
```suggestion
			var/obj/item/stack/planks = new plank_type(get_turf(src), rand(2,4), material?.type, reinf_material?.type) // todo: change plank amount based on carpentry skillcheck
			if(!planks.add_to_stacks(user, TRUE))
				user.put_in_hands(planks)
```
The put_in_hands part is optional, but as-is, using `loc` means planks cut from held logs will appear inside your body.

2024-02-27 20:10 UTC, MistakeNot4892 commented on code/modules/materials/definitions/solids/materials_solid_wood.dm
> +	if(stack_type == /obj/item/stack/material/log)
I need to systematize the stack type system I think. Another dep incoming...

2024-02-29 00:11 UTC, MistakeNot4892 commented on code/modules/materials/material_sheets.dm
>  			planks.add_to_stacks(user, TRUE)
Had to tweak add_to_stacks to have a meaningful return value but good call.

2024-03-07 05:11 UTC, out-of-phaze approved these changes, later dismissed

2024-03-07 05:16 UTC, MistakeNot4892 commented
Need to do some review on how this all works once everything is in before it's merged.

2024-03-16 11:13 UTC, MistakeNot4892 commented
Calling this done for now. I'm not happy with the layering or movement hook stuff, but I would like to get this in alongside the natural floor rewrite PR before I do any further integration/generalizing as the conflicts are going to suck already.

2024-03-16 15:34 UTC, out-of-phaze approved these changes
I might modify `can_backfill_turf_type` to populate a typecache, but aside from future changes this is fine as-is.

2024-03-18 02:27 UTC, merged