Porting grilling and drying of items from Polaris.
NebulaSS13/Nebula pull request #3764
Opened 2024-03-03 09:34 UTC by MistakeNot4892

## Description of changes
- Drying racks can be built from furniture materials.
- Items can be dried on a drying rack or in the drying oven.
- Items can be grilled with fire.
- Raw cutlets, fish fillets and meatballs grill into cooked ones.
- Meat and cutlets dry into jerky.
- Food exposed to flames will either grill, dry out or burn.
- Butchery now uses tool quality (sharp/edge items have a default knife quality).
- Wild grass can be harvested to turn it into grass and spawn a dryable grass bundle stack.

I'm going to tie flame sources into grilling when I do a rewrite of our campfire code. 

## Why and what will this PR improve
More options for cooking without a microwave. Will likely integrate/refine the grilling stuff when I get to the recipes and cooking rework in 2 years.

## TODO in future PRs
- Drying logs and planks to improve their use as fuel.
- ~~Wetting skin and drying it to tan it into leather.~~ Turns out this mostly existed already and just needed to be hooked into the new drying rack item.

## Authorship
I did most of the code, @evreeone did the icons for jerky.

## Changelog
:cl:
add: Some food can now be dried or grilled.
/:cl:

2024-03-03 13:01 UTC, MistakeNot4892 commented on code/modules/hydroponics/grown.dm
> -	plantname = "biteleaf"
This is a Scav lore thing that missed the descavving.

2024-03-06 16:55 UTC, out-of-phaze requested changes

2024-03-06 16:55 UTC, out-of-phaze commented on code/modules/reagents/Chemistry-Holder.dm
> -	R.touch_turf(target)
I don't see this removal documented anywhere. Is `touch_turf` already called elsewhere in the chain?

2024-03-06 16:55 UTC, out-of-phaze commented on code/modules/materials/_materials.dm
> +	// Used by leather.
probably better to write a functional description of what it does/can be used for rather than just saying leather uses it, tbh

2024-03-06 16:55 UTC, out-of-phaze commented on code/modules/hydroponics/seed_datums.dm
I believe grass exists here as a bespoke plant, you may want to tie it into the new grass cutting stuff?

2024-03-06 23:22 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Holder.dm
> -	R.touch_turf(target)
Sorry, it's in one of the commit messages.
````
Simplifying trans_to_turf() so that the fluid system can take over most of these checks/calls.
````
`touch_turf()` is called by `fluid_act()` so anything with an appreciable amount of reagents in it will call the proc anyway.

2024-03-06 23:23 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Holder.dm
> -	R.touch_turf(target)
Realizing this may have broken mops, will need to test.

2024-03-06 23:24 UTC, MistakeNot4892 commented on code/modules/hydroponics/seed_datums.dm
I'll reconcile grass bundles with grass tiles and the new grass plant once the crafting rework is in, because I need to discriminate on stack type and doing that with the current code is a mess.

2024-03-06 23:45 UTC, MistakeNot4892 commented on code/modules/hydroponics/seed_datums.dm
Did a halfassed interim merge where the grass plant produces the bundle stack which can be used to make the tile.

2024-03-08 04:56 UTC, out-of-phaze requested changes

2024-03-08 04:56 UTC, out-of-phaze commented on code/modules/materials/recipes_furniture.dm
> +/datum/stack_recipe/furniture/drying_rack
```suggestion
/datum/stack_recipe/furniture/drying_rack
	title = "drying rack"
```

2024-03-08 06:26 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Holder.dm
> -	R.touch_turf(target)
Mops work, but don't make the floor slippery. Will revisit after this PR and #3714 are in to avoid duplicated work.

2024-03-08 20:19 UTC, out-of-phaze approved these changes, later dismissed

2024-03-12 03:07 UTC, out-of-phaze submitted a review, later dismissed

2024-03-14 01:54 UTC, out-of-phaze approved these changes
Was approved two days ago with only conflict resolutions since, so it's going in.

2024-03-14 01:54 UTC, merged