Reworking attack() -> use_on_mob()
NebulaSS13/Nebula pull request #3773
Opened 2024-03-08 04:32 UTC by MistakeNot4892

## Description of changes
- Renamed `attack()` to `use_on_mob()` and removed the zone parameter.
- Standardize parameters to `mob/living/target` and `mob/living/user`.
- Add return values and generally clean up the procs.

## Why and what will this PR improve
Standardized return value, standard parameters, less carbon types.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-04-09 21:52 UTC, out-of-phaze requested changes

2024-04-09 21:52 UTC, out-of-phaze commented on code/game/objects/items/weapons/material/knives.dm
> +		return eyestab(target, user)
this proc can return null, if you wanna enforce return type on `use_on_mob` you'll want either `eyestab()` to return `TRUE`/`FALSE` or just call `eyestab()` and `return TRUE` always

2024-04-09 21:52 UTC, out-of-phaze commented on code/game/objects/items/weapons/tools/screwdriver.dm
> +	return eyestab(target, user)
as with knife, eyestab returns null, may wanna handle that

2024-04-09 21:52 UTC, out-of-phaze commented on code/game/objects/items/weapons/towels.dm
> +		return use_on_mob(user, user, user.get_target_zone())
```suggestion
		return use_on_mob(user, user)
```

2024-04-10 01:04 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/material/knives.dm
> +		return eyestab(target, user)
Went with the former.

2024-04-10 04:28 UTC, out-of-phaze requested changes
quick one

2024-04-10 04:28 UTC, out-of-phaze commented on code/_onclick/item_attack.dm
>  mob/living/attackby() after checking for surgery, calls the item's attack() proc.
```suggestion
mob/living/attackby() after checking for surgery, calls the item's use_on_mob() proc.
```

2024-04-11 06:09 UTC, out-of-phaze approved these changes, later dismissed

2024-04-12 15:14 UTC, out-of-phaze approved these changes

2024-04-12 15:18 UTC, merged