Seeds spawning rework.
NebulaSS13/Nebula pull request #3781
Opened 2024-03-09 04:56 UTC by MistakeNot4892

## Description of changes
- Seed packets take a seed argument in Initialize().
- `seed_type` has been merged with `seed` on seed packets.
- `/obj/structure/flora/plant` will spawn some seeds on being cut down.
- `/obj/structure/proc/dismantle()` is now `/obj/structure/proc/dismantle_structure(mob/user)`.

## Why and what will this PR improve
Nicer seeds code, nicer survivalist experience, more searchable dismantle proc.

## Authorship
Myself.
## Changelog
:cl:
tweak: Exoplanet plants will now drop seeds.
/:cl:

2024-03-09 23:22 UTC, out-of-phaze reviewed
Is there a reason `/obj/item/chems/food/grown/var/plantname` wasn't also merged with its `seed` var?

2024-03-10 02:29 UTC, MistakeNot4892 commented
Because it's unrelated to seed packets?

2024-03-12 12:43 UTC, out-of-phaze requested changes
The chemistry unit test might need to explicitly test the predefined seed datums so that fruits that spawn acid don't destroy themselves. Alternatively, it'd be faster to just exclude growns from the test.

2024-03-12 21:48 UTC, out-of-phaze approved these changes

2024-03-14 00:22 UTC, merged