Adds fishing
NebulaSS13/Nebula pull request #3790
Opened 2024-03-12 15:03 UTC by MistakeNot4892

## Description of changes
- Ports several fish icons from Polaris and adds subtypes to use them.
- Adds craftable fishing rods and fishing line.
- Adds infrastructure for fishing in submerged turfs.

## Why and what will this PR improve
Fishing good.

## TODO
- [x] Add some fish or other item rewards for fishing to exoplanets as an example for main code.
- [x] Add sound effects and visuals to fishing.

## Authorship
Code is mine, icons are adapted from Polaris.

## Changelog
:cl:
add: Added fishing!
/:cl:

2024-03-17 08:08 UTC, MistakeNot4892 commented
Calling this ready to go. It'll need some playtesting and refinement, and I'd like to make the actual minigame more interesting, but it'll do for the time being.

2024-03-17 08:51 UTC, MistakeNot4892 commented
If I keep messing with this I'm never going to stop.

2024-03-17 08:51 UTC, MistakeNot4892 commented on code/game/area/area_fishing.dm
> +	// This is pretty rancid but we're limited in our ability to actually refine a
Calling this block out for review as in general I don't like it, but I can't think of anything less bad.

2024-03-17 08:53 UTC, MistakeNot4892 commented on code/game/objects/random/random.dm
> +	// Hang around for a tick in case someone wants our spawn results.
See comment about re: bad.

2024-03-17 08:55 UTC, MistakeNot4892 commented on code/modules/blob/blob.dm
> -/obj/effect/blob/core/proc/get_health_percent()
This got replaced by the generalized health percentage proc on /atom.

2024-03-24 02:37 UTC, out-of-phaze requested changes

2024-03-24 02:37 UTC, out-of-phaze commented on code/game/area/area_fishing.dm
> +	// This is pretty rancid but we're limited in our ability to actually refine a
Could potentially make it use `/datum/atom_creator` like closets?

2024-03-24 02:37 UTC, out-of-phaze commented on code/game/objects/random/random.dm
> +	// Hang around for a tick in case someone wants our spawn results.
I don't like this! `/datum/atom_creator/weighted()` is better for things where code might need to access the results, in my opinion.

2024-03-30 10:15 UTC, MistakeNot4892 commented on code/game/objects/random/random.dm
> +	// Hang around for a tick in case someone wants our spawn results.
I don't see how you can access results from `datum/atom_creator/weighted`, it just seems to dump stuff into the loc the same as a random spawner does.

2024-03-30 10:16 UTC, MistakeNot4892 commented on code/game/area/area_fishing.dm
> +	// This is pretty rancid but we're limited in our ability to actually refine a
Per my other comment I'm not sure I see how that would be an improvement.
EDIT: I think I get what you mean but I don't think it's a suitable solution.

2024-03-30 10:18 UTC, MistakeNot4892 commented on code/game/objects/random/random.dm
> +	// Hang around for a tick in case someone wants our spawn results.
Okay, I see what you mean, but it's not really what I want. It would lock the fishing results to a single type unless I regenerated the list every time I wanted to get a result from it.

2024-03-30 10:25 UTC, MistakeNot4892 commented
I just rolled back the random item handling, it can get sorted out in another PR.

2024-04-02 15:27 UTC, out-of-phaze approved these changes, later dismissed

2024-04-02 15:36 UTC, PlayerDeer commented
Does this feature the stardew valley style fishing minigame? If not and you need icons for that later feel free to hit me up MistakeNot :)

2024-04-02 15:47 UTC, MistakeNot4892 commented
No minigame currently, but it would be nice...

2024-04-04 01:45 UTC, out-of-phaze requested changes

2024-04-04 01:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +	var/line_integrity
this variable is unused

2024-04-04 01:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +	return FISHING_POSSIBLE
this doesn't check if something is blocking our path, and doing so is currently nontrivial. i have a commit that fixes this pretty well if you'd like, ask about it on Discord and i'll link it to you assuming i've pushed it by then

2024-04-04 01:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +			update_icon()
```suggestion
			update_icon()
			result.throw_at(get_turf(user), get_dist(src, result), 0.5, user, FALSE)
```
This way, you actually 'reel' the catch in and don't have to wade out into the water to collect your fish.

2024-04-04 01:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +	user.visible_message(SPAN_NOTICE("\The [user] casts \the [src] into \the [target]."))
```suggestion
	user.visible_message(SPAN_NOTICE("\The [user] casts \the [src] into \the [target.get_fluid_name()]."))
```
ideally you cast it into the water (lava, blood, etc), not into the mud

2024-04-04 03:18 UTC, MistakeNot4892 commented
Grabbed your commits and put some time into the minigame. Need to add some sounds and visual cues but the logic seems to be working.

2024-04-04 17:45 UTC, out-of-phaze requested changes
I missed some cases of `[target]`, but the minigame looks fine!

2024-04-04 17:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +			to_chat(user, SPAN_NOTICE("You reel your line back in and abandon fishing in \the [is_fishing.target]."))
```suggestion
			to_chat(user, SPAN_NOTICE("You reel your line back in and abandon fishing in \the [is_fishing.target.get_fluid_name()]."))
```
Missed one, sorry.

2024-04-04 17:45 UTC, out-of-phaze commented on code/modules/fishing/fishing_rod.dm
> +		to_chat(user, SPAN_WARNING("Your fishing line is blocked from reaching \the [target] by \the [hit[1]]."))
```suggestion
		to_chat(user, SPAN_WARNING("Your fishing line is blocked from reaching \the [target.get_fluid_name()] by \the [hit[1]]."))
```

2024-04-06 22:25 UTC, out-of-phaze submitted a review, later dismissed

2024-04-08 03:54 UTC, out-of-phaze approved these changes

2024-04-08 03:54 UTC, merged