[MDB IGNORE] [IDB IGNORE] Unifying /turf/exterior with /turf/floor.
NebulaSS13/Nebula pull request #3793
Opened 2024-03-13 09:25 UTC by MistakeNot4892

## Description of changes
- Repaths /turf/exterior to /turf/floor/natural.
- Audits the entirety of the floor type tree, repathing or removing a few.
- Repaths several exterior turfs to the regular turf type (paths and concrete).
- Adds unit testing and validation for floor icon states and overlays.
- Restructures and cleans up the flooring and floor turf directories.

Has dependencies on #3792 and #3791. Currently opening for CI.

## Why and what will this PR improve
Working towards a unified flooring system and adding validation for what is currently a bit of a nightmare.

## Authorship
Myself.

## Changelog
Should be mostly nothing player-facing.

2024-03-13 11:07 UTC, MistakeNot4892 commented on code/controllers/subsystems/fluids.dm
> +		if(isspaceturf(current_fluid_holder) || (istype(current_fluid_holder, /turf/floor) && current_fluid_holder.is_outside() && (current_fluid_holder.reagents?.total_volume + current_fluid_holder.get_ph
Not completely sure about this one. The old behavior was mainly to prevent exoplanets flooding, and this does a similar job.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/modules/overmap/ships/computers/comms.dm
> +		if(istype(neighbor, /turf/space) || neighbor.is_outside())
This is another one I'm not totally sure about. It's used by sensors to ensure you don't build them inside, so even in a case where they're built inside and the roof is removed so it has LOS to the sky, that seems fine to me.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/modules/multiz/ladder.dm
> +			T.physically_destroyed() // this does not feel correct, but it's the proc that clears the turf and spawns a lattice
Pointing this out for review.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/modules/atmospherics/datum_pipeline.dm
> -	else if(istype(target, /turf/exterior) && !target.blocks_air)
This block is redundant in view of the block immediately above it.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/game/turfs/floors/subtypes/floor_plating.dm
> +// simulated/floor is currently plating by default, but there really should be an explicit plating type. // Why?
Reiterating: why do we need a redundant subtype when `/turf/floor` is functionally identical?

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/game/turfs/floors/natural/natural_ice.dm
> +	ChangeTurf(/turf/floor/natural/ice)
Noting to self that this should probably just turn snow and ice into mud with water.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/game/turfs/floors/natural/_natural_icon.dm
> -				if(draw_state && check_state_in_icon(draw_state, icon))
All these `check_state_in_icon` should in theory be handled by the new unit test.

2024-03-16 07:29 UTC, MistakeNot4892 commented on code/game/turfs/floors/natural/_natural.dm
> +	if(!QDELETED(src) && reagent_type && height < 0 && !QDELETED(reagents) && reagents.total_volume < abs(height))
This may not be super necessary, my unit test does some extremely weird shit with turf spawning and was runtiming here.

2024-03-16 20:52 UTC, out-of-phaze submitted a review, later dismissed
This was originally going to be an approval, but I noticed one or two issues that required changes. Most of the comments are just comments and not requests for changes.

2024-03-16 20:52 UTC, out-of-phaze commented on code/modules/overmap/ships/computers/comms.dm
> +		if(istype(neighbor, /turf/space) || neighbor.is_outside())
I think it's also useful for preventing sensors from working on landable ships while in a mothership's hangar, so this solution works fine as well.

2024-03-16 20:52 UTC, out-of-phaze commented on code/game/turfs/floors/natural/natural_ice.dm
> +	ChangeTurf(/turf/floor/natural/ice)
Noting that originally the resulting turf was named "permafrost," which should *probably* be (mostly-)unmeltable ice? Frozen soil? Dunno.

2024-03-16 20:52 UTC, out-of-phaze commented on code/controllers/subsystems/fluids.dm
> +		if(isspaceturf(current_fluid_holder) || (istype(current_fluid_holder, /turf/floor) && current_fluid_holder.is_outside() && (current_fluid_holder.reagents?.total_volume + current_fluid_holder.get_ph
The change here seems fine, but the clause directly after might cause issues in other PRs (particularly, trenches—things like gently sloping hillsides and flat, slightly-inset areas could cause problems. Noting for future concern.

2024-03-16 20:52 UTC, out-of-phaze commented on code/game/turfs/floors/natural/_natural_icon.dm
> -				if(draw_state && check_state_in_icon(draw_state, icon))
As long as there's no runtime icon mutation/creation, yeah.

2024-03-16 20:52 UTC, out-of-phaze commented on code/game/turfs/floors/subtypes/floor_plating.dm
> +// simulated/floor is currently plating by default, but there really should be an explicit plating type. // Why?
Probably user-friendliness? When searching for plating in build mode/a map editor/etc., something with the word "plating" in it is a lot clearer. Otherwise, you'd just have to guess that `/turf/floor` is plating.

2024-03-16 20:52 UTC, out-of-phaze commented on code/modules/multiz/ladder.dm
> +			T.physically_destroyed() // this does not feel correct, but it's the proc that clears the turf and spawns a lattice
I mean, I kind of think `physically_destroyed()` should be calling a helper so that on subtypes that expect *destruction* we don't do things like spawn shrapnel, but that's what it did before and you removed said helper in favor of this. If you think it's alright, it's alright.

2024-03-16 20:52 UTC, out-of-phaze commented on code/game/turfs/floors/natural/_natural.dm
> +	if(!QDELETED(src) && reagent_type && height < 0 && !QDELETED(reagents) && reagents.total_volume < abs(height))
Your unit test probably uncovered a real issue with ChangeTurf on flooded turfs, so I think this is fine.

2024-03-16 20:52 UTC, out-of-phaze commented on code/game/turfs/turf_changing.dm
> +/turf/floor/natiral
```suggestion
```

2024-03-16 20:52 UTC, out-of-phaze commented on code/modules/atmospherics/datum_pipeline.dm
> -	else if(istype(target, /turf/exterior) && !target.blocks_air)
This probably predates atmos unification and so the istype should probably be replaced with `(target.external_atmosphere_participation && target.is_outside()` or something similar.

2024-03-17 00:48 UTC, MistakeNot4892 commented on code/game/turfs/turf_changing.dm
> +/turf/floor/natiral
Where did THAT come from...

2024-03-17 00:49 UTC, MistakeNot4892 commented on code/controllers/subsystems/fluids.dm
> +		if(isspaceturf(current_fluid_holder) || (istype(current_fluid_holder, /turf/floor) && current_fluid_holder.is_outside() && (current_fluid_holder.reagents?.total_volume + current_fluid_holder.get_ph
I think it should probably be fine, since turfs being inset like that kind of implies you _want_ them to interact with fluids. Rain flowing downhill to pool at the bottom seems expected for example. Unsure though, we probably need a turf flag or something to absorb water.

2024-03-17 00:53 UTC, MistakeNot4892 commented on code/modules/multiz/ladder.dm
> +			T.physically_destroyed() // this does not feel correct, but it's the proc that clears the turf and spawns a lattice
The helper was pretty specific to constructed turfs, is the thing.
I think what I'll do is generalize `dismantle_wall` to turf.

2024-03-17 01:08 UTC, MistakeNot4892 commented on code/game/turfs/floors/subtypes/floor_plating.dm
> +// simulated/floor is currently plating by default, but there really should be an explicit plating type. // Why?
I put a stub type with no changes in _floor.dm instead since it's literally the exact same turf.

2024-03-17 01:08 UTC, MistakeNot4892 commented on code/game/turfs/floors/natural/natural_ice.dm
> +	ChangeTurf(/turf/floor/natural/ice)
It doesn't make a huge amount of sense for permafrost to be caused by fire, though.

2024-03-17 01:16 UTC, out-of-phaze commented on code/modules/multiz/ladder.dm
> +			T.physically_destroyed() // this does not feel correct, but it's the proc that clears the turf and spawns a lattice
I think that has an argument to not spawn dismantle products, so that's fine.

2024-03-17 01:19 UTC, out-of-phaze commented on code/game/turfs/floors/natural/natural_ice.dm
> +	ChangeTurf(/turf/floor/natural/ice)
I assumed the intent was that the snow on top was melted away to reveal the permafrost beneath it, but now that we have actual turf height stuff, there may be a better way to represent snow accumulation and melting down the line.

2024-03-17 01:23 UTC, MistakeNot4892 commented on code/controllers/subsystems/fluids.dm
> +		if(isspaceturf(current_fluid_holder) || (istype(current_fluid_holder, /turf/floor) && current_fluid_holder.is_outside() && (current_fluid_holder.reagents?.total_volume + current_fluid_holder.get_ph
I added a turf flag for a subset of natural turfs to absorb fluid instead of doing it based on type.

2024-03-19 09:46 UTC, MistakeNot4892 commented
There's an inconsistent CI failure in my new floor tests where it can't ChangeTurf as expected. Not quite sure what could be causing that at random.

2024-03-23 23:20 UTC, out-of-phaze requested changes
> There's an inconsistent CI failure in my new floor tests where it can't ChangeTurf as expected. Not quite sure what could be causing that at random.

The current one seems to be because of this:
```
/turf/floor/fixed/alium/ruin/Initialize()
	. = ..()
	if(prob(10))
		ChangeTurf(get_base_turf_by_area(src))
```
It changes to another turf 10% of the time, and that throws off your test, I assume.

2024-03-23 23:20 UTC, out-of-phaze commented on code/modules/atmospherics/datum_pipeline.dm
> +	else if(target.external_atmosphere_participation && !target.blocks_air)
Does this need `target.is_outside()`? If `target` has `zone_membership_candidate = FALSE` but `external_atmosphere_participation = TRUE` while being indoors, it'd use `target.return_air()`. In fact, why do we not use that in all cases? Maybe this block should just check `!target.blocks_air`, since the `else` block ignores air entirely.

2024-03-24 01:19 UTC, out-of-phaze commented on code/modules/atmospherics/datum_pipeline.dm
> +	else if(target.external_atmosphere_participation && !target.blocks_air)
this was an old comment and not intended to be posted :p

2024-03-24 23:27 UTC, MistakeNot4892 commented
> ```dm
> urf/floor/fixed/alium/ruin/Initializ
> ```

I turned the logic into a landmark which should hopefully sort it out.

2024-03-30 18:41 UTC, out-of-phaze submitted a review, later dismissed

2024-03-31 11:14 UTC, MistakeNot4892 commented
Carpets are broken :I

2024-04-03 01:25 UTC, out-of-phaze approved these changes, later dismissed

2024-04-07 02:06 UTC, out-of-phaze submitted a review, later dismissed

2024-04-07 04:33 UTC, out-of-phaze approved these changes

2024-04-07 05:21 UTC, deathride58 approved these changes

2024-04-07 05:22 UTC, merged