Various rock and crafting tweaks.
NebulaSS13/Nebula pull request #3808
Opened 2024-03-18 01:04 UTC by MistakeNot4892

## Description of changes
- Rocks are now a material stack.
- Single natural walls no longer have no icon on Initialize().
- Mining requires a pickaxe with hardness greater than the target turf.
- Tool head crafting requires rocks or planks depending on the tool head.
- Stack crafting recipes or stacks themselves can have verbs specified for crafting messages.

## Why and what will this PR improve
Various stuff to make toolmaking and mining more entwined.

## Authorship
Myself.
## Changelog
:cl:
tweak: Mining now requires a tool of sufficient hardness.
tweak: Tool crafting is now restricted to specific stack types.
/:cl:

2024-03-18 02:02 UTC, out-of-phaze requested changes

2024-03-18 02:02 UTC, out-of-phaze commented on code/game/objects/items/rock.dm
> +	plural_name         = "rock"
`You need at least 4 rock` is not really ideal. Set it to rocks or like, remove it so it autosets?
```suggestion
	plural_name         = "rocks"
```

2024-03-18 02:02 UTC, out-of-phaze commented on code/modules/materials/_materials.dm
Line 300 should use `\the` instead of `the`, or drop the explicit article entirely.

2024-03-18 02:02 UTC, out-of-phaze commented on code/modules/tools/archetypes/tool_extension_variable.dm
> +	to_chat(user, SPAN_NOTICE("You adjust your grip on \the [holder] to use it as [tool_name]."))
I think the original idea here was something like changing a drill's bit from 'drill' to 'screwdriver' or what have you? Still, this message does work better for non-mechanical tools. I kind of think maybe the variable tool extension just shouldn't be used for those... could make it contextual and pop up a radial menu if it has two? Then again, that could make `IS_TOOL` blocking so you'd have to do it delicately...

2024-03-18 02:15 UTC, MistakeNot4892 commented on code/modules/tools/archetypes/tool_extension_variable.dm
> +	to_chat(user, SPAN_NOTICE("You adjust your grip on \the [holder] to use it as [tool_name]."))
Oh you're right, I thought this was separate to the powertools but it's all the same extension type.

2024-03-18 02:51 UTC, MistakeNot4892 commented on code/modules/tools/archetypes/tool_extension_variable.dm
> +	to_chat(user, SPAN_NOTICE("You adjust your grip on \the [holder] to use it as [tool_name]."))
Per Discord this isn't something I can really do in this PR.

2024-03-18 10:48 UTC, out-of-phaze submitted a review, later dismissed

2024-03-18 10:48 UTC, out-of-phaze commented on code/game/objects/items/weapons/surgery_tools.dm
> +	set_extension(src, /datum/extension/tool/variable/simple, list(
```suggestion
	set_extension(src, /datum/extension/tool/variable, list(
```
This is a digital tool, isn't it?

2024-03-18 11:33 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/surgery_tools.dm
> +	set_extension(src, /datum/extension/tool/variable/simple, list(
Yeah I must have find and replace'd that one.

2024-03-19 06:10 UTC, out-of-phaze submitted a review, later dismissed

2024-03-20 05:01 UTC, out-of-phaze approved these changes
Conflict resolution, so it's been 24hrs.

2024-03-20 06:35 UTC, merged