Fixing issues with mass testing of /atom/movable.
NebulaSS13/Nebula pull request #3812
Opened 2024-03-19 03:50 UTC by MistakeNot4892

## Description of changes
Fixes numerous issues with atoms being manually spawned in nullspace.

Used this code for testing:
````
/client/verb/test_atom_init()

    set name = "Test Atom Init"
    set category = "Debug"
    set src = usr

    for(var/atom_type in typesof(/atom/movable))
        try
            var/atom/movable/atom = atom_type
            if(TYPE_IS_SPAWNABLE(atom))
                atom_info_repository.get_instance_of(atom)
        catch(var/exception/E)
            to_chat(usr, "Failed: [atom_type] - '[E]'")
````

## Why and what will this PR improve
Allows for some atom subtype checking in the codex dump PR. Also generally good for code quality.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-03-20 08:47 UTC, comma commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	if(!body.loc)
Maybe these checks should go into whatever cycle calls do_process? Seems like none of processing should be happening in nullspace

2024-03-20 09:52 UTC, comma commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	if(!body.loc)
Missed one spot when reverting

2024-03-23 21:19 UTC, out-of-phaze requested changes

2024-03-23 21:19 UTC, out-of-phaze commented on code/datums/ai/ai.dm
> +	if(!body || !body.loc || ((body.client || body.mind) && !(body.status_flags & ENABLE_AI)))
Is this really sufficient? What issue was this for? If `body` is in something that is in nullspace, will it still have issues? Do we need to check `!get_turf(body)`?

2024-03-23 21:19 UTC, out-of-phaze commented on code/game/machinery/Beacon.dm
> +	if(!beacon && loc)
`get_turf(src)` could still be null on the next line.

2024-03-23 21:19 UTC, out-of-phaze commented on code/game/machinery/computer/area_atmos.dm
>  	var/area/A_src = T_src.loc
Could just use this instead, since T_src is not used other than to get the area. Same with T_scrub.
```
	var/area/A_src = get_area(src)
	if(!A.src) return FALSE
```

2024-03-23 21:19 UTC, out-of-phaze commented on code/game/machinery/computer/area_atmos.dm
>  	var/area/A = T.loc
Once again, this could just use `get_area(src)`.

2024-03-23 21:19 UTC, out-of-phaze commented on code/game/machinery/computer/area_atmos.dm
>  		var/turf/T2 = get_turf(scrubber)
This could also use `get_area(src)`!

2024-03-23 21:19 UTC, out-of-phaze commented on code/game/objects/random/date_based.dm
> +	if(date_check?.IsValid())
I would rather we just set `abstract_type = /obj/random/date_based`, personally?

2024-03-23 21:19 UTC, out-of-phaze commented on code/modules/holodeck/HolodeckControl.dm
> +	is_spawnable_type = FALSE
This is constructable, see `/obj/item/stock_parts/circuitboard/holodeckcontrol`. I don't think `is_spawnable_type = FALSE` should be set for anything directly constructable, to be honest!

2024-03-23 21:19 UTC, out-of-phaze commented on code/modules/power/smes.dm
> +	is_spawnable_type = FALSE
Is there a reason this isn't just using `abstract_type = /obj/machinery/power/smes`? Setting it back to `TRUE` on every child type seems to indicate it should use `abstract_type` instead.

2024-03-23 21:19 UTC, out-of-phaze commented on code/unit_tests/del_the_world.dm
> +	SSfluids.suspend()
I still worry about fluid_act() causing issues.

2024-03-23 21:19 UTC, out-of-phaze commented on maps/random_ruins/exoplanet_ruins/monoliths/monoliths.dm
>  	var/datum/planetoid_data/E = SSmapping.planetoid_data_by_z[z]
I would rather just gate this section rather than disallowing it from being spawned in nullspace
```suggestion
	var/datum/planetoid_data/E = loc ? SSmapping.planetoid_data_by_z[get_z(src)] : null
```

2024-03-23 23:35 UTC, MistakeNot4892 commented on code/datums/ai/ai.dm
> +	if(!body || !body.loc || ((body.client || body.mind) && !(body.status_flags & ENABLE_AI)))
Generally for wandering or targeting adjacent turfs, so checking for null loc does the job. It's just to stop runtimes in the testing period.

2024-03-24 23:58 UTC, MistakeNot4892 commented on code/unit_tests/del_the_world.dm
> +	SSfluids.suspend()
Not a lot we can do about it other than disabling the subsystem.

2024-03-24 23:59 UTC, MistakeNot4892 commented on code/modules/power/smes.dm
> +	is_spawnable_type = FALSE
There was a reason but I can't remember it now.

2024-03-25 03:32 UTC, out-of-phaze commented on code/unit_tests/del_the_world.dm
> +	SSfluids.suspend()
Blacklist the fluid spawner effects from the test, as before...?

2024-03-25 13:01 UTC, MistakeNot4892 commented on code/unit_tests/del_the_world.dm
> +	SSfluids.suspend()
Won't stop atoms spawning reagents on the test turf though, so the issue is just masked, not resolved.

In a perfect universe the exceptions list wouldn't exist - I would prefer to see how it goes with SSfluids suspended at least initially. If it causes issues we can add it back to the exception list.

2024-04-03 01:26 UTC, out-of-phaze approved these changes
holodeck_control fixes seem good. do we wanna do a snake_case pass on filenames at some point, by the way? now `holodeck_control` is in `HolodeckControl.dm` :p

2024-04-03 01:49 UTC, MistakeNot4892 commented
Maybe we can do a snake_case pass when we merge `game` and `modules`? It'd be nice but disruptive.

2024-04-04 01:36 UTC, merged