Starting cash choices are now handled the same way as surivival box options.
NebulaSS13/Nebula pull request #3822
Opened 2024-03-22 11:35 UTC by MistakeNot4892

## Description of changes
Allows maps to override cash options.

## Why and what will this PR improve
Flexibility in making forks.

## Authorship
Myself, cribbing the pattern Penny used for survival boxes.

## Changelog
Nothing player-facing.

2024-03-23 18:11 UTC, out-of-phaze requested changes, later dismissed
I had some commits for this but forgot to PR them, and aside from the changes I requested you seem to have implemented it a lot better than I did. Fair enough.

2024-03-23 18:11 UTC, out-of-phaze commented on code/modules/client/preference_setup/general/04_equipment.dm
> +	pref.starting_cash_choice =   decls_repository.get_decl_by_id(R.read("starting_cash_choice"), validate_decl_type = FALSE)
```suggestion
	pref.starting_cash_choice =   decls_repository.get_decl_by_id_or_var(R.read("starting_cash_choice"))
```
If you want to keep backwards compatibility.

2024-03-23 18:11 UTC, out-of-phaze commented on maps/~mapsystem/maps_currency.dm
>  	var/name = "all in bank account"
```suggestion
	var/name = "all in bank account"
	decl_flags = DECL_FLAG_MANDATORY_UID
	uid = "starting_cash_bank"
```
and so on with uids for the other ones.

2024-03-25 01:52 UTC, out-of-phaze approved these changes

2024-03-25 01:52 UTC, out-of-phaze commented on code/modules/client/preference_setup/general/04_equipment.dm
> +	pref.survival_box_choice =    decls_repository.get_decl_by_id_or_var(R.read("survival_box"), /decl/survival_box_option)
I'm not totally sure if `get_decl_by_id_or_var` is valid here, was it serialized by name beforehand? Either way, at worst it's just wasted effort, not going to harm anything.

2024-03-25 02:14 UTC, MistakeNot4892 commented on code/modules/client/preference_setup/general/04_equipment.dm
> +	pref.survival_box_choice =    decls_repository.get_decl_by_id_or_var(R.read("survival_box"), /decl/survival_box_option)
Not sure what else it could have been serialized for. You swapped it to UID and it must have been serialized or deserialized somehow beforehand.

2024-03-26 03:06 UTC, merged