Adding CI to Shaded Hills.
NebulaSS13/Nebula pull request #3835
Opened 2024-03-26 02:57 UTC by MistakeNot4892

Really need to enable the branch tests for this one.

2024-03-26 03:05 UTC, MistakeNot4892 commented
Seems like when I pushed the base branch I included some commits I shouldn't have, causing some conflicts/clobbering.

2024-03-26 03:12 UTC, out-of-phaze commented
> Really need to enable the branch tests for this one.

I don't think we can, since it's not on all branches? I'm not sure. Might have to make a special test action that only runs on this branch...

2024-03-26 03:13 UTC, MistakeNot4892 commented
CI runs off the workflow in the branch itself, so should be fine. Seems to be working on this one anyway.

2024-03-26 19:32 UTC, out-of-phaze requested changes

2024-03-26 19:32 UTC, out-of-phaze commented on maps/shaded_hills/jobs/_jobs.dm
> +	abstract_type = /decl/hierarchy/outfit/job/shaded_hills
```suggestion
	abstract_type = /decl/hierarchy/outfit/job/shaded_hills
	id_type = null
	pda_type = null
	l_ear = null
```

2024-03-26 19:33 UTC, out-of-phaze requested changes

2024-03-26 19:33 UTC, out-of-phaze commented on nebula.dme
> +#include "maps\tradeship\tradeship.dm"
```suggestion
#include "maps\shaded_hills\shaded_hills.dm"
#include "maps\shaded_hills\shaded_hills_define.dm"
```

2024-03-30 04:24 UTC, out-of-phaze approved these changes

2024-03-30 04:34 UTC, merged