Swaps world.turf from space to dark filler.
NebulaSS13/Nebula pull request #3880
Opened 2024-04-11 06:33 UTC by MistakeNot4892

## Description of changes
Changes `world.turf` to `/turf/unsimulated/dark_filler` instead of `/turf/space`.

## Why and what will this PR improve
Loaded z-levels aren't randomly surrounded by space.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-04-11 19:16 UTC, PsyCommando commented
I'm really confused here.. Isn't that changing a long established assumption? Like, feels like it would cause other problems to surface­, for the benefit of an edge case? Unless I don't understand what you mean by random space turfs surrounding a level?

Also, the transition edge stuff should be able to handle putting whatever filler turf you want around your levels?

2024-04-11 19:18 UTC, out-of-phaze requested changes, later dismissed
```dm
///Initialize the turfs on the z-level.
/datum/level_data/proc/initialize_new_level()
	//#TODO: Is it really necessary to do this for any and all levels? Seems mainly useful for space levels?
	var/picked_turf = filler_turf || base_turf //Pick the filler_turf for filling if it's set, otherwise use the base_turf
	var/change_turf = (picked_turf && picked_turf != world.turf)
	var/change_area = (base_area && base_area != world.area)
	if(!change_turf && !change_area)
		return
	var/corner_start = locate(1, 1, level_z)
	var/corner_end =   locate(world.maxx, world.maxy, level_z)
	var/area/A = change_area ? get_base_area_instance() : null
	for(var/turf/T as anything in block(corner_start, corner_end))
		if(change_turf)
			T = T.ChangeTurf(picked_turf)
```
Because of `filler_turf` being `null` and `base_turf` being `/turf/space`, which no longer matches `world.turf`, now every turf created by the unit test template loader has to run `ChangeTurf(/turf/space)`, which takes a long time. `/datum/level_data` or at least `/datum/level_data/unit_test` should have its `filler_turf` set to `/turf/unsimulated/dark_filler`, or else this makes space-level loading dramatically more expensive.

![image](https://github.com/NebulaSS13/Nebula/assets/110272328/f0b4095f-772a-4624-b362-caf3b847c2bf)

However, it also seems that this breaks exoplanet generation somehow.

2024-04-11 19:27 UTC, PsyCommando commented
> However, it also seems that this breaks exoplanet generation somehow.
I'm pretty sure random map will replace only turfs set to a specific type. And, the generators all expect space turf by default. That's cause world.turf is a runtime var.

Example:
```
/datum/random_map/noise/desert/replace_space
	descriptor = "desert (replacement)"
	target_turf_type = /turf/space
```

2024-04-11 21:09 UTC, MistakeNot4892 commented
`Unless I don't understand what you mean by random space turfs surrounding a level?`
When world.maxx and world.maxy change, the extra space is filled with world.turf. This leads to stuff like the overmap and exoplanets being surrounded by space tiles. It also means any newly created level is always going to be space.

I don't think it's an edge case. It's a conceptual problem. If Neb is going to support a variety of maps and settings I don't think every new level being deep space is desirable. Additionally, the adaptive client view can lead to seeing past the border turfs on some levels, into space.

There's also the overhead of initializing starlight and multiz stuff for space when it's in a filler context.

I'll have a look at template target turfs and unit tests later. Obviously if the performance impacts are this significant the change isn't feasible, but in general breaking the hard dependency on /turf/space is a good idea imo.

2024-04-12 00:04 UTC, out-of-phaze commented
> `Unless I don't understand what you mean by random space turfs surrounding a level?` When world.maxx and world.maxy change, the extra space is filled with world.turf. This leads to stuff like the overmap and exoplanets being surrounded by space tiles. It also means any newly created level is always going to be space.

so, i think at one point i talked with someone about having each level_data handle filling in new space on world resize, but that adds a significant ChangeTurf cost i think. might be better to just not explicitly support post-SSmapping-init existing-level resizing though, and this PR would be one way

2024-04-12 01:55 UTC, MistakeNot4892 commented
- Turbolifts on tradeship work with no issues.
- Exoplanets generate fine during round setup.
- Placed Bearcat on a new Z, no issues.

2024-04-12 15:16 UTC, out-of-phaze approved these changes

2024-04-14 09:30 UTC, merged