Repathed lockets, rings onto /jewelry.
NebulaSS13/Nebula pull request #3902
Opened 2024-04-17 06:47 UTC by MistakeNot4892

## Description of changes
Splits insignia, lockets and rings off accessory onto their own subtype.

## Why and what will this PR improve
Breaks #3798 up for ease of review.
Working towards destroying /obj/item/clothing/accessory.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-04-17 11:59 UTC, MistakeNot4892 commented
Tested, working.

2024-04-21 18:42 UTC, out-of-phaze requested changes, later dismissed
A little wary of dog tags being made jewelry, but since the jewelry type doesn't actually show up in checks or have any functionality yet, I guess it's fine.

Aside from that, necklaces don't have a map migration. Whoops.

2024-04-21 18:42 UTC, out-of-phaze commented on code/modules/clothing/jewelry/lockets.dm
> +/obj/item/clothing/jewelry/locket
Seems a bit weird to me that a locket isn't a type of necklace, but I suppose that's fine. Not blocking. left this comment before I found a blocker.

2024-04-21 18:42 UTC, out-of-phaze commented on tools/map_migrations/3902_jewelry.txt
> +/obj/item/clothing/accessory/badge/tags/@SUBTYPES : /obj/item/clothing/jewelry/dog_tags/@SUBTYPES{@OLD}
```suggestion
/obj/item/clothing/accessory/badge/tags/@SUBTYPES : /obj/item/clothing/jewelry/dog_tags/@SUBTYPES{@OLD}
/obj/item/clothing/accessory/necklace/@SUBTYPES : /obj/item/clothing/jewelry/necklace/@SUBTYPES{@OLD}
```

2024-04-21 23:38 UTC, MistakeNot4892 commented
Accidentally mashed in some changes that I need to split out again.

2024-04-23 04:24 UTC, MistakeNot4892 commented
Depends on #3931

2024-04-24 02:28 UTC, out-of-phaze approved these changes, later dismissed

2024-04-25 21:39 UTC, out-of-phaze approved these changes

2024-04-26 00:02 UTC, merged