Grown products rework.
NebulaSS13/Nebula pull request #3941
Opened 2024-04-26 12:50 UTC by MistakeNot4892

## Description of changes
- Growns now use sliceable vars to determine how they are processed with a knife.
- Growns can serve as seeds (specifically potatoes).
- Growns can have seeds extracted in most cases using a knife, if your Botany skill is higher than untrained.
- Products of growns have their own types, including a couple of new ones: slice (smaller icon, based on evree's apple slices), big slice (old slice icon), chopped (based on evree's sliced potato icon), crushed (new by me), sticks (new by me).

## Why and what will this PR improve
Allows for agriculture on Shaded Hills to sustain itself.
~~Lays some groundwork for some soup-related veggie chopping changes I want to make later~~. Had to implement these changes to get fruit slices to work, so uh, that's sorted.

## Authorship
Code and the reworked big slice icon, the crushed icon and the potato sticks icons were me.
New slice icons were done by @evreeone and I mauled them into greyscale.

## Changelog
:cl:
tweak: Growns can be processed into different forms based on the grown. Apples will be sliced, potatoes will be turned into sticks, and carrots will be chopped. You can also turn sticks into chopped veggies by using a knife again.
tweak: You can now extract seeds from growns using Botany skill and a sharp knife.
tweak: Potatoes can be planted directly without extracting seeds.
/:cl:

2024-04-26 15:30 UTC, MistakeNot4892 commented
![image](https://github.com/NebulaSS13/Nebula/assets/2468979/f14162b7-de36-4bb4-ae5f-8b429135e26f)

2024-04-26 15:37 UTC, MistakeNot4892 commented on code/game/objects/items/__item.dm
> +	usr.UnarmedAttack(src, usr.Adjacent(src))
Fixes a unreported issue with Pick Up not working.

2024-04-26 15:37 UTC, MistakeNot4892 commented on code/datums/trading/traders/food.dm
> -		/obj/item/chems/food/soydope             = TRADER_THIS_TYPE,
No idea why a fast food place was selling raw chopped soybeans.

2024-04-26 15:38 UTC, MistakeNot4892 commented on code/modules/food/cooking/_recipe.dm
> +	if(!container.reagents?.maximum_volume)
Fixes issues with every recipe that doesn't feature reagents runtiming.

2024-04-26 15:39 UTC, MistakeNot4892 commented on code/game/machinery/kitchen/microwave.dm
> +	while(recipe && recipe_sanity > 0)
Fixes an issue where a recipe runtiming during this loop caused contents to never be cleared, meaning that select_recipe() returned the same recipe, which then runtimed again, ad infinitum.

2024-04-26 15:40 UTC, MistakeNot4892 commented on tools/check_icon_state_limit.py
> +        except AttributeError as e:
Previously just threw an exception and fell over if it hit an empty DMI file.

2024-04-26 15:41 UTC, MistakeNot4892 commented on code/unit_tests/chemistry_tests.dm
> +			if(!TYPE_IS_SPAWNABLE(chem))
Prevents it spawning the semi-abstract types that delete themselves if not given correct Initialize args.

2024-04-26 15:41 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +		if(G.get_grown_tag() == "wheat")
Should dried or crushed wheat also work for feeding chickens?

2024-04-26 15:42 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
> +		else if(istype(I, /obj/item/chems/food/processed_grown/slice))
Should large slices (watermelon) still work for putting on the rim of drinks?

2024-04-26 15:43 UTC, MistakeNot4892 commented on code/modules/hydroponics/seed.dm
> +	var/grown_tag                // Used by the reagent grinder.
This rename was partially to make it easier to spot places I overlooked when fixing it to use the helper, but also because it's used in a few spots other than recipes.

2024-04-26 15:44 UTC, MistakeNot4892 commented on code/modules/hydroponics/seed.dm
> +	var/grown_is_seed = FALSE
Only set this on potatoes and garlic, any other bulb plants or whatever, please let me know.

2024-04-27 07:37 UTC, MistakeNot4892 commented
Depends on #3942

2024-04-27 08:37 UTC, out-of-phaze commented on code/modules/food/assembled.dm
> +/// The ingredient can be a typepath or a grown_tag string (used for mobs or plants)
iirc at some point `kitchen_tag` was also used for mob products (like a mouse holder being used in a mouseburger or something), unsure if that's presently needed though

2024-04-27 08:37 UTC, out-of-phaze commented on code/modules/clothing/head/misc_special.dm
> +/obj/item/clothing/head/pumpkinhead/attackby(obj/item/W, mob/user)
does this not result in you being able to carve a pumpkin head into a pumpkin head?

2024-04-27 08:37 UTC, out-of-phaze commented on code/modules/hydroponics/trays/tray.dm
> +			qdel(S)
is this ever valid? should we not, like, print a stacktrace if passed a datum directly instead? i could see someone passing a seed datum to plant_seed because theyre confused and then having the concept of that seed vanish from existence entirely, which would. suck!

edit: okay, i forgot that atoms are datums, the check here is just for "is able to be qdeleted". still, i think we should probably check for `/atom/movable` here and throw a stacktrace if it's not a seed packet, grown product, or other movable?

2024-04-27 08:37 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +		if(G.get_grown_tag() == "wheat")
yes I think so, it's still grain after all

2024-04-27 08:37 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
> +		else if(istype(I, /obj/item/chems/food/processed_grown/slice))
behold
<details>

![image](https://www.simplejoy.com/wp-content/uploads/2016/07/watermelon_limeade_4.webp)
</details>

2024-04-27 08:37 UTC, out-of-phaze commented on code/unit_tests/chemistry_tests.dm
> +			if(!TYPE_IS_SPAWNABLE(chem))
does this make `excepted_types` up above unnecessary?

2024-04-27 08:37 UTC, out-of-phaze commented on code/datums/trading/traders/food.dm
> -		/obj/item/chems/food/soydope             = TRADER_THIS_TYPE,
a few months ago i spent ages trying to track down why it was named soy dope. nothing. no evidence in blame, nothing at all.

2024-04-27 08:54 UTC, MistakeNot4892 commented on code/modules/clothing/head/misc_special.dm
> +/obj/item/clothing/head/pumpkinhead/attackby(obj/item/W, mob/user)
Fuck, yes. Should have tested this.

2024-04-27 08:54 UTC, MistakeNot4892 commented on code/modules/hydroponics/trays/tray.dm
> +			qdel(S)
Could throw in a stack trace for the sake of debugging, sure.

2024-04-27 08:56 UTC, MistakeNot4892 commented on code/unit_tests/chemistry_tests.dm
> +			if(!TYPE_IS_SPAWNABLE(chem))
The comment on that list is `// Types to be skipped for reasons other than abstraction/spawnability.` so I assumed I should leave it alone.

2024-04-27 08:56 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
> +		else if(istype(I, /obj/item/chems/food/processed_grown/slice))
Ok I will leave it alone for now then.

2024-04-27 09:05 UTC, out-of-phaze commented on code/unit_tests/chemistry_tests.dm
> +			if(!TYPE_IS_SPAWNABLE(chem))
they do in fact have spawnable set to false, actually, so they can all be removed. i don't know why the comment mentions spawnability when it didn't check that when the comment was written

2024-04-28 10:36 UTC, out-of-phaze requested changes

2024-04-28 10:36 UTC, out-of-phaze commented on code/modules/clothing/head/misc_special.dm
> +/obj/item/clothing/head/pumpkinhead/attackby(obj/item/W, mob/user)
going to keep this for some reason?

2024-04-28 11:09 UTC, MistakeNot4892 commented on code/modules/clothing/head/misc_special.dm
> +/obj/item/clothing/head/pumpkinhead/attackby(obj/item/W, mob/user)
I changed the product type.

2024-04-28 12:21 UTC, MistakeNot4892 commented on code/unit_tests/chemistry_tests.dm
> +			if(!TYPE_IS_SPAWNABLE(chem))
Removed them from the list.

2024-04-28 22:13 UTC, out-of-phaze approved these changes, later dismissed

2024-04-29 23:29 UTC, out-of-phaze approved these changes
Conflict resolution rule, good to go if it passes CI this run.

2024-04-29 23:50 UTC, merged