[MDB IGNORE] [IDB IGNORE] Splitting up uniforms and implementing component clothing.
NebulaSS13/Nebula pull request #3948
Opened 2024-04-28 00:16 UTC by MistakeNot4892

## Description of changes
- Implements dresses, shirts, skirts, jumpsuits and several other types as their own subtypes of clothing instead of sitting under uniforms.
- Splits a lot of uniforms up into ensembles using starting_accessories.

## Why and what will this PR improve
More flexibility

## TODO
- [x] Finish this pass over uniforms or decide the PR is too large.
- ~~Adjust equip procs so that they try to equip the accessory to the already-equipped item.~~ split to a separate PR.
- ~~Reorganize the clothing icons folder.~~

## Authorship
Myself.

## Changelog
Will fill this out before merge.

2024-04-29 03:14 UTC, MistakeNot4892 commented
Will depend on #3951 for some accessory and state CI stuff.

2024-05-22 21:26 UTC, out-of-phaze requested changes
aside form this, looks good. dreading having to convert stuff downstream eventually but at least i can keep them mostly as-is now

2024-05-22 21:26 UTC, out-of-phaze commented on code/modules/clothing/webbing/holster.dm
> +	holder = loc
uh, was this ever valid/necessary? like... on_attached can return FALSE meaning it didn't attach and nothing got moved, but like, if it does succeed, `loc` will be `holder` (because `..()` does `forceMove(holder)`). this line just feels like it's redundant at best and a bad idea at worst
```suggestion
```

2024-05-24 06:01 UTC, out-of-phaze approved these changes

2024-05-25 23:37 UTC, merged