Adding deer and foxes, and tweaking mice and rabbits.
NebulaSS13/Nebula pull request #3987
Opened 2024-05-10 04:00 UTC by MistakeNot4892

## Description of changes
- Darkens rabbit ears and tweaks their facial structure.
- Adds a passive AI type that implements fleeing from harm like cats. Moved mice and rabbits onto this type.
- Adds foxes and deer (icons by @PlayerDeer). Deer are passive mobs, foxes hunt small mobs or scavenge dead mobs.

## Why and what will this PR improve
More dynamic mob behavior, more mobs for shadyhills.

## Authorship
My code, Doe's icons.

## Changelog
:cl:
tweak: Mice will now flee from harm.
/:cl:

2024-05-10 05:21 UTC, out-of-phaze requested changes

2024-05-10 05:21 UTC, out-of-phaze commented on tools/map_migrations/3987_deer_foxes.txt
> +/mob/living/simple_animal/mouse : /mob/living/simple_animal/passive/mouse/@SUBTYPES{@OLD}
```suggestion
/mob/living/simple_animal/mouse/@SUBTYPES : /mob/living/simple_animal/passive/mouse/@SUBTYPES{@OLD}
```

2024-05-10 11:58 UTC, PlayerDeer commented
WOOHOO YEAH

2024-05-10 14:12 UTC, Greenjoe12345 commented
Should frogs be made into a passive mob like mice and rabbits are? Also why is food.dmi deleted?

2024-05-10 15:48 UTC, out-of-phaze commented
> Should frogs be made into a passive mob like mice and rabbits are? Also why is food.dmi deleted?

i accidentally added polaris' food.dmi while porting some missing sprites, it's an extra file

2024-05-10 16:00 UTC, out-of-phaze requested changes
some annoying nitpicks but the PR is good overall, yay foxes and deer

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +/datum/level_data/player_level/shaded_hills/proc/place_mobs()
proc appears to be unused, were you going to move mob placement out of `after_generate_level` and into here?

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/grass/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
```suggestion
		var/turf/floor/natural/grass/place_mob_at = locate(rand(level_inner_min_x, level_inner_max_x), rand(level_inner_min_y, level_inner_max_y), level_z)
```
if we have an 80x80 level but world.maxx is 255, we shouldn't waste our time with the extra tiles outside the level.

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/grass/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
see above re: maxx vs level_inner_max_x

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/mud/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
see above, again. also this should really be written in a way that has less code duplication...

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/grass/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
once more, level_inner_min_x and level_inner_max_x etc

2024-05-10 16:00 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/grass/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
see above, just leaving all these comments to avoid any of them getting missed

2024-05-10 16:00 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/passive/fox.dm
> +	if(!isliving(hunt_target_atom) || QDELETED(hunt_target_atom) || !(hunt_target_atom in view(body)))
i think `body in hunt_target_atom.viewers()` might be faster, but idk how that interacts with setting view on body or whatever

2024-05-10 16:00 UTC, out-of-phaze commented on code/modules/mob/living/simple_animal/passive/fox.dm
> +	if(!.  && !hunt_target) // TODO: generalized nutrition process. && body.get_nutrition() < body.get_max_nutrition() * 0.5)
does this mean that currently they will devour every prey animal in sight? may be better to use a cooldown of a few minutes for now, until they handle nutrition properly.

2024-05-10 16:00 UTC, out-of-phaze commented on code/modules/butchery/butchery_data_livestock.dm
> +	meat_type     = /obj/item/chems/food/butchery/meat/
either you meant for this to be a nonexistent subtype, or you should remove the trailing `/`.

2024-05-10 17:54 UTC, comma commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/mud/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
Yeah some sort of 'get_level_block' proc might be good to have for this

2024-05-10 18:41 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
> +		var/turf/floor/natural/mud/place_mob_at = locate(rand(10,world.maxx-10), rand(10,world.maxy-10), level_z)
nah i specifically meant the repeated mob spawning while loops which are 90% the same except for
- the turf to spawn the mobs on
- the mobs to pick from
- how many mobs to spawn
could really be made into a proc or something, i think...

2024-05-10 20:53 UTC, MistakeNot4892 commented on maps/shaded_hills/levels/_levels.dm
> +/datum/level_data/player_level/shaded_hills/proc/place_mobs()
I actually decided to just override `after_generate_level` and forgot to remove this.

2024-05-10 20:55 UTC, MistakeNot4892 commented on code/modules/mob/living/simple_animal/passive/fox.dm
> +	if(!isliving(hunt_target_atom) || QDELETED(hunt_target_atom) || !(hunt_target_atom in view(body)))
This is more or less copied from cats, which work, so I'm reluctant to mess with it too much currently.

2024-05-11 01:12 UTC, out-of-phaze approved these changes, later dismissed

2024-05-13 00:05 UTC, out-of-phaze approved these changes
Conflict resolution, should be good to go now.

2024-05-13 00:05 UTC, merged