Reworking daycycle.
NebulaSS13/Nebula pull request #3988
Opened 2024-05-10 08:20 UTC by MistakeNot4892

Opening for review/commentary, still needs some refinement to be good to merge.

## Description of changes
- Rips out old daycycle behavior.
- Adds daycycle datums that compare a time offset to a mapping of periods to time_of_day datums.
- Adds daycycle checking to ambient light updates on turfs.
- Changes area ambience to be a modifier for the ambience that would otherwise be applied, so tree shadows cooperate with daycycles.
- Adds weather and time of day checking to Look Up verb and new Check Sky verb.
 
## Why and what will this PR improve
Existing daycycle system works only for very specific uses cases (single level exoplanets) and is not integrated with any other source of ambience.

## Authorship
Myself.

## Changelog
:cl:
add: When on a level with weather or a daycycle, Look Up or Check Sky will show weather and time of day.
/:cl:

2024-05-10 08:26 UTC, MistakeNot4892 commented on code/modules/admin/verbs/debug.dm
> +		SSdaycycle.remove_level(PD.get_linked_level_ids(), PD.daycycle_id)
Realizing now this is the wrong proc, this is going to return IDs rather than zs I suspect.

2024-05-10 21:18 UTC, out-of-phaze requested changes, later dismissed

2024-05-10 21:18 UTC, out-of-phaze commented on code/datums/daycycle/daycycle.dm
> +		time_of_day -= day_duration
```suggestion
	time_of_day += world.time - last_update
	time_of_day %= day_duration
	last_update = world.time
```
1) with enough lag, `time_of_day -= day_duration` can still be greater than `day_duration`.
2) last_update needs to be set here or else the passage of time will accelerate.

2024-05-12 13:27 UTC, MistakeNot4892 commented
If anyone has any suggestions for lighting variations, colours, periods, etc. please let me know, I am a lot more interested in just having the system in place than I am in making it look nice.

2024-05-13 02:24 UTC, out-of-phaze requested changes, later dismissed

2024-05-13 02:24 UTC, out-of-phaze commented on code/datums/daycycle/daycycle.dm
> +			if((T.z in levels_affected) && T.is_outside())
```suggestion
			if(T && (T.z in levels_affected) && T.is_outside())
```
without this it'll runtime if players are in the lobby, nullspace, etc

2024-05-13 02:24 UTC, out-of-phaze commented on code/modules/multiz/level_data.dm
> +		for(var/turf/level_turf as anything in block(locate(1, 1, level_z), locate(world.maxx, world.maxy, level_z)))
```suggestion
		for(var/turf/level_turf as anything in block(locate(level_inner_min_x, level_inner_min_y, level_z), locate(level_inner_max_x, level_inner_max_y, level_z)))
```

2024-05-13 02:24 UTC, out-of-phaze commented on code/datums/daycycle/time_of_day.dm
> +	period = 0.4
daytime seems to have a null power? that means it falls back to level_data's general ambience.

2024-05-13 02:24 UTC, out-of-phaze commented on code/controllers/subsystems/ambience.dm
> +				set_ambient_light(daycycle.current_period.color, clamp(daycycle.current_period.power + ambient_light_modifier, 0, 1))
this might make it so that a power of 0 wouldn't clear ambience, which is unfortunate. should maybe check `else if (daycycle?.current_period?.power == 0)` and clear ambient light then?

fwiw i went with this:
```dm
		// Check for daycycle ambience.
		if(level_data.daycycle_id)
			var/datum/daycycle/daycycle = SSdaycycle.get_daycycle(level_data.daycycle_id)
			var/resulting_power = isnull(daycycle?.current_period?.power) ? null : clamp(daycycle.current_period.power + ambient_light_modifier, 0, 1)
			if(resulting_power)
				set_ambient_light(daycycle.current_period.color, resulting_power)
				return TRUE
			else if(resulting_power == 0) // equals zero, non-null
				clear_ambient_light()
				return TRUE
```

2024-05-13 02:24 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
personally i would remove the base `ambient_light` vars from here and have it rely on daycycle entirely instead, which requires giving daylight a power/color

2024-05-13 02:24 UTC, out-of-phaze commented on maps/planets/test_planet/test_planet.dm
>  	surface_light_color = COLOR_OFF_WHITE
does this need to be replaced or adjusted to work with daycycle?

2024-05-13 02:24 UTC, out-of-phaze commented on code/datums/daycycle/time_of_day.dm
> +	power = 0.3
tested these and they looked alright! will have to add `COLOR_DAYLIGHT` to colors.dm, i used `#define COLOR_DAYLIGHT         "#f3e6ca"` taken from shaded hills level data
```suggestion
/datum/time_of_day/sunrise
    name = "sunrise"
    announcement = "The sun peeks over the horizon, bathing the world in rosy light."
    period = 0.1
    color = COLOR_RED_LIGHT
    power = 0.5

/datum/time_of_day/daytime
    name = "daytime"
    announcement = "The sun rises over the horizon, beginning another day."
    period = 0.4
    power = 1
    color = COLOR_DAYLIGHT

/datum/time_of_day/sunset
    name = "sunset"
    announcement = "The sun begins to dip below the horizon, and the daylight fades."
    period = 0.6
    color = COLOR_ORANGE
    power = 0.5

/datum/time_of_day/night
    name = "night"
    announcement = "Night falls, blanketing the world in darkness."
    period = 1
    color = COLOR_CYAN_BLUE
    power = 0.3
```

2024-05-13 02:24 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
should probably remove the ambient light stuff from `/datum/level_data/player_level/shaded_hills` once the values are moved over to daycycle

2024-05-13 02:26 UTC, MistakeNot4892 commented on code/datums/daycycle/time_of_day.dm
> +	period = 0.4
Yeah null power means no changes from level preset.

2024-05-13 02:27 UTC, MistakeNot4892 commented on maps/planets/test_planet/test_planet.dm
>  	surface_light_color = COLOR_OFF_WHITE
Shouldn't need to be changed. Daycycle completely overwrites colour and power if the values are non-null for the period.

2024-05-13 02:28 UTC, MistakeNot4892 commented on maps/shaded_hills/levels/_levels.dm
Why's that?

2024-05-13 02:33 UTC, MistakeNot4892 commented on code/controllers/subsystems/ambience.dm
> +				set_ambient_light(daycycle.current_period.color, clamp(daycycle.current_period.power + ambient_light_modifier, 0, 1))
Ambient light is cleared at the start of the proc regardless, and presumably we should support periods with a light value of 0. So we really just need a nullcheck.

2024-05-13 03:03 UTC, out-of-phaze commented on maps/shaded_hills/levels/_levels.dm
actually no, it's fine as a fallback for if daycycle is disabled in config

2024-05-13 15:23 UTC, out-of-phaze approved these changes

2024-05-13 15:25 UTC, out-of-phaze requested changes

2024-05-13 15:25 UTC, out-of-phaze commented on code/controllers/subsystems/ambience.dm
> +					set_ambient_light(daycycle.current_period.color, clamp(new_power + ambient_light_modifier, 0, 1))
Actually, I think this should probably `clear_ambient_light()` if it's equal to zero?

2024-05-13 16:10 UTC, MistakeNot4892 commented on code/controllers/subsystems/ambience.dm
> +					set_ambient_light(daycycle.current_period.color, clamp(new_power + ambient_light_modifier, 0, 1))
See previous comment, we already clear ambient light every call.

2024-05-13 16:19 UTC, out-of-phaze approved these changes

2024-05-14 23:21 UTC, merged