Fix many double variable definitions
NebulaSS13/Nebula pull request #4068
Opened 2024-05-31 01:14 UTC by out-of-phaze

## Description of changes
Fixes issues where a variable was set twice in one type definition block, which can lead to confusion as only the second value applies.
I tried doing it in CI but automating it would be incredibly difficult; only ripgrep is powerful enough to handle it, and the grep is really brittle. Here's the regex anyway, it has to be used in VSC because that automatically adds `--crlf` and does some annoying conversion of `\n` to `\r\n` in the regex.
`^(?!\/\/)\/?[\w\/]+\/\w+(?:\s*\/\/.*)?$(?:\n+^\s*[^\s\/].*$)*?\n+\t(\w+\b)\s*=\s*.+$\n+(?:^\s*?(?:[^\s\/]|\/\/).*$\n+)*?\t\1\b`

## Why and what will this PR improve
Fixes issues where the actual value of a variable was unclear, or where the intended value was clobbered by a later definition. A lot of these were cases where `obj_flags` was defined twice, so I kept both sets of flags and just combined them into one.

2024-05-31 08:45 UTC, comma submitted a review, later dismissed

2024-06-01 06:45 UTC, MistakeNot4892 commented on code/datums/inventory_slots/slots/slot_cuffs.dm
> -	slot_id = "Handcuffs"
This is actually an error rather than a duplicate var, should be `slot_name`

2024-06-01 06:46 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/circuitboards/machinery/research.dm
> -	req_components = list(/obj/item/stack/cable_coil = 15)
Should the cable coil be moved into the second list?

2024-06-01 06:47 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/storage/boxes.dm
> -	icon_state = "part"
`part` seems to be the correct state here.

2024-06-01 06:49 UTC, MistakeNot4892 commented on code/modules/materials/definitions/gasses/material_gas_mundane.dm
> -	metabolism = 0.05 // So that low dosages have a chance to build up in the body.
This doesn't seem to be set elsewhere. Base `gas` doesn't set metabolism and `/decl/material` has it set to `0.2`.

2024-06-01 06:50 UTC, MistakeNot4892 commented on code/modules/materials/definitions/gasses/material_gas_mundane.dm
> -	metabolism = 0.05 // So that low dosages have a chance to build up in the body.
Disregard, Github wasn't showing me context.

2024-06-01 06:55 UTC, MistakeNot4892 commented on code/modules/tools/subtypes/xenoarchaeology_picks.dm
> -	item_state        = "utility"
I think `utility` might have been the correct state.

2024-06-01 06:55 UTC, MistakeNot4892 commented on mods/content/corporate/datum/antagonists/commando.dm
> +	r_ear =   /obj/item/radio/headset/hacked
Are they really meant to have two headsets?

2024-06-01 06:56 UTC, MistakeNot4892 commented on mods/content/corporate/datum/antagonists/deathsquad.dm
> +	r_ear =    /obj/item/radio/headset/hacked
As above, it seems kinda bizzare to have a headset in each ear.

2024-06-01 06:57 UTC, MistakeNot4892 requested changes
Left a handful of comments.

2024-06-01 17:21 UTC, out-of-phaze commented on code/modules/tools/subtypes/xenoarchaeology_picks.dm
> -	item_state        = "utility"
it literally does not exist, i checked

2024-06-01 17:22 UTC, out-of-phaze commented on mods/content/corporate/datum/antagonists/commando.dm
> +	r_ear =   /obj/item/radio/headset/hacked
if you were present i would've asked. but i assume so, one lets you intercept the station's comms (but it's useless for speaking into, thus right ear) and the other is used for communicating with your team.

2024-06-01 17:23 UTC, out-of-phaze commented on code/game/objects/items/weapons/storage/boxes.dm
> -	icon_state = "part"
no, i assumed `part` was for the single-type packs later in the file. `big` is unused elsewhere and makes sense given that this is `ITEM_SIZE_NORMAL` and has more parts, while the other one is `ITEM_SIZE_SMALL` and has fewer

2024-06-03 00:36 UTC, MistakeNot4892 commented on mods/content/corporate/datum/antagonists/deathsquad.dm
> +	r_ear =    /obj/item/radio/headset/hacked
Would suggest adding this to the ERT encryption key and removing the r_ear set:
````
/obj/item/encryptionkey/ert/Initialize(ml, material_key)
	. = ..()
	can_decrypt |= get_all_station_access()
````

2024-06-03 00:37 UTC, MistakeNot4892 commented on mods/content/corporate/datum/antagonists/commando.dm
> +	r_ear =   /obj/item/radio/headset/hacked
Would suggest adding this and removing the other headsets:
````
/obj/item/radio/headset/mercenary/commando
	encryption_keys = list(
		/obj/item/encryptionkey/mercenary,
		/obj/item/encryptionkey/hacked
	)
````

2024-06-03 00:38 UTC, out-of-phaze commented on mods/content/corporate/datum/antagonists/deathsquad.dm
> +	r_ear =    /obj/item/radio/headset/hacked
it's something only deathsquad is supposed to have though, not normal ERT

2024-06-03 00:42 UTC, MistakeNot4892 commented on mods/content/corporate/datum/antagonists/deathsquad.dm
> +	r_ear =    /obj/item/radio/headset/hacked
Per Discord, ERT's meant to have all station channel access.

2024-06-03 20:08 UTC, MistakeNot4892 approved these changes

2024-06-04 23:41 UTC, merged