Bow rework.
NebulaSS13/Nebula pull request #4076
Opened 2024-06-03 04:11 UTC by MistakeNot4892

## Description of changes
- Adds bows, crossbows and slings within a subtype that includes powered crossbows and RCD crossbows.
- Redoes powered crossbow and RCD crossbow icons to play nicely with the new type.
- Adds a bowstring item.

## TODO
- [X] Add arrow crafting ~~and fletching.~~
- [x] Add fancy bow subtype to use fancy bow icon.
- [x] Rework/balance/test various bow types and tension levels.
- [x] Less awful bow inhands and on back icon.
- [x] String and arrow overlays for inhands.

## Why and what will this PR improve
Medieval weapons for Shaded Hills, slightly nicer code.

## Authorship
Myself for the most part, Keekenox for the base of the bow and fancy bow icons.

## Changelog
:cl:
tweak: Bows/crossbows have been adjusted. Please report issues to the tracker.
/:cl:

2024-06-04 02:34 UTC, MistakeNot4892 commented
Depends on #4079

2024-06-04 10:22 UTC, MistakeNot4892 commented
Calling this done for now. Proper fletching and bowery need to be added, but that can happen later.

2024-06-05 18:25 UTC, out-of-phaze submitted a review, later dismissed

2024-06-05 18:25 UTC, out-of-phaze commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	if(effective_force)
uhhhhhhhh. there's no call to `apply_damage()` or `..()` here now. does damage even work?

2024-06-05 22:18 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	if(effective_force)
This is a dep, I'll address it in the other PR.

2024-06-08 01:35 UTC, out-of-phaze requested changes
also remove_implant does not remove from embedded list :(

and small mobs like rabbits fly super far when shot, like 9 tiles

2024-06-08 01:35 UTC, out-of-phaze commented on code/modules/crafting/stack_recipes/recipes_planks.dm
> +	result_type            = /obj/item/gun/launcher/bow/fancy/crafted
this makes it impossible to craft the base bow type because the name is identical. `title = "engraved bow"` maybe?

2024-06-08 01:35 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/arrow.dm
> +	name = "arrows"
this makes it so that the recipe name is `arrowss`, should this be `arrow` just like how bolts are `bolt`?

2024-06-08 03:25 UTC, out-of-phaze requested changes

2024-06-08 03:25 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
> +			SPAN_NOTICE("You nocks \the [_loaded] on \the [src].")
```suggestion
			SPAN_NOTICE("You nock \the [_loaded] on \the [src].")
```

2024-06-08 03:25 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
> +			SPAN_NOTICE("\The [user] begins to draw back the string of \the [src]."),
all of these cases of `the string` could easily be `\the [string]`, and `\the [src]'s string` could be `\the [src]'s [string.name]`

2024-06-08 03:25 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
i would like it if something like this were added
```
/obj/item/gun/launcher/bow/examine(mob/user)
	. = ..()
	var/list/strings = list()
	if(material_alteration & MAT_FLAG_ALTERATION_DESC)
		strings += "is made of [material.solid_name]"
	if(string)
		strings += "is strung with \a [string]"
	if(_loaded)
		strings += "has \a [_loaded] nocked"
	if(!length(strings))
		return
	to_chat(user, "It [english_list(strings)].")
```
some simulated output from my testing to make sure english_list works for this:
```
It is strung with a nylon bowstring.
It is made of adamantine, is strung with a copper bowstring, and has a steel arrow nocked.
It is strung with a nylon bowstring and has a bone arrow nocked.
It is strung with a dried gut bowstring.
It is made of steel and is strung with a copper bowstring.
It is made of steel and is strung with a nylon bowstring.
It is made of ebony and is strung with a cotton bowstring.
It is strung with a cotton bowstring and has a steel arrow nocked.
It is strung with a copper bowstring and has a steel arrow nocked.
It is strung with a nylon bowstring.
It is made of copper, is strung with a dried gut bowstring, and has a bone arrow nocked.
It is made of copper, is strung with a copper bowstring, and has a copper arrow nocked.
It is strung with a dried gut bowstring.
It is strung with a cotton bowstring and has an ebony arrow nocked.
It is made of ebony and is strung with a cotton bowstring.
It is made of steel and is strung with a nylon bowstring.
It is strung with a nylon bowstring.
```
which seems pretty okay to me

2024-06-08 03:25 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/bow_string.dm
> +	// END TEMP
nitpicking here but `icon_state` will presumably still be `ICON_STATE_WORLD` even once it gets a real icon, so the temp should probably just be on the icon var :p

2024-06-08 03:47 UTC, MistakeNot4892 commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
> +			SPAN_NOTICE("\The [user] begins to draw back the string of \the [src]."),
That might get a bit verbose though, do you really need to know it's a dried gut string?

2024-06-08 03:48 UTC, MistakeNot4892 commented on code/modules/projectiles/guns/launcher/bows/bow_string.dm
> +	// END TEMP
To be honest the temp icon works fine anyway, I might just leave it.

2024-06-08 03:54 UTC, out-of-phaze commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
> +			SPAN_NOTICE("\The [user] begins to draw back the string of \the [src]."),
i mean i think it's neat but fair enough

2024-06-08 06:49 UTC, MistakeNot4892 commented on code/modules/projectiles/guns/launcher/bows/bow_messages.dm
> +			SPAN_NOTICE("\The [user] begins to draw back the string of \the [src]."),
I would rather not make the message even longer, it's already going to be printed about 900 times.

2024-06-08 13:07 UTC, out-of-phaze approved these changes

2024-06-09 21:33 UTC, merged