Fixes issues with object embedding.
NebulaSS13/Nebula pull request #4079
Opened 2024-06-04 01:04 UTC by MistakeNot4892

- Embedding is now unified under `try_embed_in_mob()`.
- Embedding will proactively try to find an appropriate limb and create a wound if unsupplied.
- Failed embedding will not teleport the item inside the mob with no way to remove it.
- Pinning should work again.
- Slightly lowered the damage threshold for embedding.

2024-06-04 14:36 UTC, out-of-phaze commented on code/game/atoms_movable.dm
> +
?

2024-06-04 14:36 UTC, out-of-phaze commented on code/modules/organs/external/wounds/wound.dm
>  	if(bandaged || clamped)
could maybe replace the bandaged check here with a !is_open() check, removing the one in the final return

2024-06-04 21:01 UTC, MistakeNot4892 commented on code/game/atoms_movable.dm
> +
What?

2024-06-05 15:08 UTC, out-of-phaze commented on code/game/atoms_movable.dm
> +
there's a blank line here

2024-06-05 18:26 UTC, out-of-phaze requested changes

2024-06-05 18:26 UTC, out-of-phaze commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		try_embed_in_mob(I, hit_zone, effective_force, direction = get_dir(user, src))
this doesn't call parent or `apply_damage()` which means... i don't think weapons will do damage?

2024-06-05 18:32 UTC, out-of-phaze requested changes

2024-06-05 18:32 UTC, out-of-phaze commented on code/modules/mob/living/living_defense.dm
> +	if(!istype(O) || !O.can_embed())
ok so it seems like only weapons that can embed can deal damage now. should probably do `if(!O.can_embed()) return FALSE` *after* the apply_damage call?

2024-06-05 22:15 UTC, MistakeNot4892 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		try_embed_in_mob(I, hit_zone, effective_force, direction = get_dir(user, src))
It calls apply_damage if no wound is supplied to the embed proc.

2024-06-05 22:42 UTC, out-of-phaze commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		try_embed_in_mob(I, hit_zone, effective_force, direction = get_dir(user, src))
see my review, before these changes it returned after apply_damage, now it returns before

2024-06-05 23:10 UTC, MistakeNot4892 commented on code/modules/mob/living/living_defense.dm
> +	if(!istype(O) || !O.can_embed())
Fixed ordering.

2024-06-05 23:11 UTC, MistakeNot4892 commented on code/game/atoms_movable.dm
> +
Per Discord it was an accidental inclusion, but it looks nicer than having it crammed up against the header so I'm going to leave it.

2024-06-06 06:49 UTC, out-of-phaze approved these changes

2024-06-07 11:25 UTC, merged