Skeletonized limb tweaks.
NebulaSS13/Nebula pull request #4122
Opened 2024-06-18 01:08 UTC by MistakeNot4892

## Description of changes
Skeletonized limbs have specialized damage handling and more consistent icon colouring.

## Why and what will this PR improve
Supporting code for undead downstream, and just kind of nice to have if limb skeletonization is ever used upstream.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-06-18 11:42 UTC, MistakeNot4892 commented
Ripped the zombies and skeletons stuff out, will push that to Pyrelight since it's a bit too invasive to justify on main Neb imo.

2024-06-18 21:54 UTC, comma submitted a review, later dismissed

2024-06-18 23:52 UTC, out-of-phaze requested changes

2024-06-18 23:52 UTC, out-of-phaze commented on maps/shaded_hills/shaded_hills_turfs.dm
> +/mob/living/carbon/human/zombie/hnoll/Initialize(mapload, species_name, datum/dna/new_dna, decl/bodytype/new_bodytype)
are these meant to still be included upstream?

2024-06-18 23:55 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_turfs.dm
> +/mob/living/carbon/human/zombie/hnoll/Initialize(mapload, species_name, datum/dna/new_dna, decl/bodytype/new_bodytype)
Whoops

2024-06-19 00:30 UTC, out-of-phaze approved these changes

2024-06-19 00:32 UTC, comma approved these changes

2024-06-19 01:44 UTC, merged