Added shrine and clerics to Shaded Hills.
NebulaSS13/Nebula pull request #4126
Opened 2024-06-19 05:18 UTC by MistakeNot4892

## Description of changes
- Corrects `travelling` to `traveling`.
- Adds a shrine/church to the downland Shaded Hills map.
- Adds seeds to the farm on Shaded Hills.
- Adds skillet to the inn on Shaded Hills.
- Adds Shrine Keeper, Shrine Attendant and Traveling Cleric jobs.

## Why and what will this PR improve
Medical roles.

## Authorship
Myself.

## Changelog
:cl:
add: Shrine attendant and Cleric roles added to Shaded Hills.
/:cl:

2024-06-19 17:09 UTC, out-of-phaze requested changes
Needs job HUD icons... because ghosts can see them, I guess.

2024-06-20 02:04 UTC, MistakeNot4892 commented
> Needs job HUD icons... because ghosts can see them, I guess.

The funny thing is, that DMI is just a bunch of empty states anyway.

2024-06-20 02:12 UTC, out-of-phaze submitted a review, later dismissed

2024-06-20 03:39 UTC, out-of-phaze approved these changes

2024-06-21 03:44 UTC, merged