Fixes some dex issues with food and natural weapons.
NebulaSS13/Nebula pull request #4196
Opened 2024-07-13 12:30 UTC by MistakeNot4892

- Fixes #4193
- Fixes #4194
- Fixes drake food issue in #4191

2024-07-13 18:34 UTC, out-of-phaze requested changes

2024-07-13 18:34 UTC, out-of-phaze commented on code/modules/mob/animations.dm
> +/atom/movable/proc/reset_windup_animation()
Uh, what's the difference between this and `reset_offsets(anim_time = 2)` (the default)? It just seems like this is less robust? Does it interact with grabs properly?

2024-07-13 18:34 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
I don't like this. We confirmed drakes can eat foods fine by using it in-hand, which I thought was the intended way for them to do it? This only affects clicking themselves (and other things) with food, and will undoubtedly have other side effects.

2024-07-13 23:28 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
This is fixing them not being able to eat food inhand.

2024-07-13 23:28 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
Either that or Greenjoe misreported the issue.

2024-07-13 23:31 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
it was misreported, we confirmed it on discord. using it inhand worked, clicking yourself is what didn't and that's intended afaik

2024-07-14 04:02 UTC, MistakeNot4892 commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
Per Discord I think I was misunderstood re: intentionality. I don't think it's good UX to arbitrarily have one method work and the other not for something as fundamental as eating. With respect to side effects, I can't think of anything offhand other than drakes feeding food to people, which is a bit whatever.

2024-07-14 04:02 UTC, MistakeNot4892 commented on code/modules/mob/animations.dm
> +/atom/movable/proc/reset_windup_animation()
It was just extracting the existing line. I'll swap it out for reset_offsets() I guess.

2024-07-14 13:31 UTC, out-of-phaze commented on code/modules/reagents/reagent_containers/food.dm
> +	needs_attack_dexterity = DEXTERITY_NONE
in that case yeah, this is fine

2024-07-14 13:31 UTC, out-of-phaze submitted a review, later dismissed

2024-07-16 00:39 UTC, out-of-phaze commented on code/_onclick/other_mobs.dm
> +	a_intent = I_HURT
already exists on line 77

2024-07-16 00:41 UTC, MistakeNot4892 commented on code/_onclick/other_mobs.dm
> +	a_intent = I_HURT
Line 77 is actually in error. Resolved now anyway.

2024-07-16 00:42 UTC, out-of-phaze approved these changes
still 24h under conflict resolution rule, yay

2024-07-16 01:05 UTC, merged