Adds map-specific skill names descriptions for Shaded Hills
NebulaSS13/Nebula pull request #4213
Opened 2024-07-15 23:32 UTC by Greenjoe12345

## Description of changes
Adds some overrides for some skill names and descriptions to make them more fitting for Shaded Hills. Currently WIP, putting it up so others can see the changes easier.

## Why and what will this PR improve
It doesn't mention modern things like microwaves that don't exist in Shaded Hills, as well as removing references to modern jobs such as EMTs.

## Authorship
Myself

## Changelog
:cl:
add: Added map-specific skill name and description overrides for Shaded hills.
/:cl:

2024-07-16 01:51 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Master"      = "You're a specialized botanist. You can care for even the most exotic, fragile, or dangerous plants.."
Double period.

2024-07-16 05:25 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	name = "Catering"
Possibly `Domestic` or `Household`? Something broader like that. `Catering` sounds like you're providing food for a film set or wedding.

2024-07-16 05:26 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	name = "Finance"
I wonder if we should reskin Finance as Arithmetic to go along with Literacy. A lot of 'finance' is very modern ('financial devices' etc. feels odd in a fantasy setting).

2024-07-16 05:26 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Master"      = "You have an excellent knowledge of finance, will often make brilliant investments, and have an instinctive feel for kingdom-wide economics. Financial instruments are weapons in you
I think narrowing the scope of these descriptions to individual trades and purchases might be the way to go.

2024-07-16 05:31 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	return //we don't want legalese here
It might be fun/characterful to make some kind of international trader or thieve's cant to replace Legalese.

2024-07-16 05:31 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Unskilled"   = "You are not used to manual labor, tire easily, and are likely not in great shape. Extended heavy labor may be dangerous for you.<br>- You can pull objects but start to generate Lac
Per Discord I think `but start to generate Lactate after tiring out` should just be a comment about getting tired faster based on skill level.

2024-07-16 05:32 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Master"      = "In addition to your excellent strength and endurance, you have a lot of experience with the specific physical demands of your job. You may have competitive experience with some for
I would remove the `You may have competitive experience with some form of athletics` section entirely I think.

2024-07-16 05:32 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	name = "Botany"
`Gardening` or `Horticulture` maybe? Botany is pretty specific/scientific.

2024-07-16 05:33 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Basic"       = "You've done some gardening. You can water, weed, fertilize, plant, and harvest, and you can recognize and deal with pests. You may be a hobby gardener.<br>- You can safely plant an
I would trim `You may be a hobby gardener.`

2024-07-16 05:34 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Experienced" = "You're a farmer, capable of running a village's farms or doing botanical research.",
Farmers don't necessarily need highly detailed or refined skills in tending plants. I would make it something like `You are an experienced horticulturalist with an encyclopedic knowledge of plants and their properties'.

2024-07-16 05:35 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Unskilled"   = "You barely know anything about cooking, and rely on others when you can. The oven is a device of black magic to you, and you avoid it when possible.",
Maybe `stove` instead of `oven`, we don't have ovens in code for Shaded Hills.

2024-07-16 05:36 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Unskilled"   = "You can throw a punch or a kick, but it'll knock you off-balance. You're inexperienced and have probably never been in a serious hand-to-hand fight. In a fight, you might panic and
This has some really strange phrasing. I appreciate it's mostly copied from the base skill, but it's weird.

2024-07-16 05:36 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Basic"       = "You either have some experience with fistfights, or you have some training in a martial art. You can handle yourself if you really have to, and know the basics of how to swing a sw
These messages all refer to martial arts and CQC. I would rewrite them for Shaded Hills to prioritize melee weapons, and refer to martial arts/CQC as brawling.

2024-07-16 05:37 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	desc = "Gives you a detailed insight of the human body. A high skill in this is required to perform surgery. This skill may also help in examining nonhuman biology."
These messages are all flavoured like xenobiology is a thing. I don't know if 'nonhuman biology' is a thing in a setting where the guys running the show are the furries.

2024-07-16 05:38 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Trained"     = "You have some training in anatomy. Diagnosing broken bones, damaged ligaments, shrapnel wounds, and other trauma is straightforward for you. You can splint limbs with a good chance
Shrapnel wounds and CPR are probably not ubiquitous in our setting. We need to decide what CPR is.

2024-07-16 05:38 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	name = "Alchemy"
Alchemy is going to be a specific discipline down the track, I would keep this as Chemistry or Chymistry.

2024-07-18 07:18 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +	name = "Arithmetic"
Per Discord, this needs to go back to Finance.

2024-07-18 07:18 UTC, MistakeNot4892 commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Master"      = "You have an excellent knowledge of finance, will often make brilliant investments, and have an instinctive feel for kingdom-wide economics. Financial instruments are weapons in you
I can do a pass on these later.

2024-07-18 17:06 UTC, out-of-phaze requested changes

2024-07-18 17:06 UTC, out-of-phaze commented on maps/shaded_hills/shaded_hills_skills.dm
> +		"Experienced" = "With your experience, you are familiar with any financial entities you may run across, and are a shrewd judge of value. More often than not, investments you make will pan out well.
```suggestion
		"Experienced" = "With your experience, you are familiar with any financial entities you may run across, and are a shrewd judge of value. More often than not, investments you make will pan out well.",
```
no Legalese on shadyhills please

2024-07-18 22:40 UTC, MistakeNot4892 approved these changes
I will probably do a second pass on these, they're fine for now.

2024-07-22 00:30 UTC, out-of-phaze approved these changes

2024-07-22 00:30 UTC, merged