Generalizing the weather processing system for atoms.
NebulaSS13/Nebula pull request #4222
Opened 2024-07-18 09:31 UTC by MistakeNot4892

- `SSweather_atoms` handles processing atoms that care about weather (humans and cleanable decals currently).
- Most cleanable decals will slowly fade away while rained on. 
- Weather ambience for mobs is handled by `handle_environment()` while exposure effects are handled by `process_weather()`.
- `get_affecting_weather()` and `is_outside()` have been generalized to `/atom`.

2024-07-24 18:42 UTC, out-of-phaze commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
i don't think this is correct, i think `WEATHER_IGNORE` should block ambience, while `WEATHER_EXPOSED`, `WEATHER_ROOFED`, and `WEATHER_PROTECTION` should allow it

2024-07-24 23:07 UTC, MistakeNot4892 commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
Why would WEATHER_IGNORE block ambience? Ambience is stuff like rain drumming on the roof or wind noises.

2024-07-24 23:15 UTC, MistakeNot4892 commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
Nvm I'm stupid and forgot my own code, WEATHER_IGNORE skips ambience anyway. Dunno if I like that on reflection, it'd be nice to hear rain from inside a locker or tent or such.

2024-07-26 11:57 UTC, MistakeNot4892 commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
Updated the comment but I think the structure is sound. Mobs without clients don't need to do any weather ambience processing and the other proc has a client check.

2024-07-26 20:35 UTC, out-of-phaze commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
I'm pretty sure `WEATHER_IGNORE` is specifically for "you are two z-levels down and there is no way the weather could reach you," IIRC? Like how we wouldn't want rain sounds to be audible from within the deep caverns

2024-07-26 21:58 UTC, MistakeNot4892 commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
I'm not touching that logic so I'm a bit confused by what this comment thread wants me to do.

2024-07-26 23:43 UTC, out-of-phaze commented on code/modules/mob/living/life.dm
> +	// as clients should get wind noise etc. regardless of weather sensitivity.
was just replying to `Dunno if I like that on reflection, it'd be nice to hear rain from inside a locker or tent or such.`, no request for changes. as evidenced by how there were not changes requested

2024-07-29 04:30 UTC, out-of-phaze requested changes
Has an extra commit that shouldn't be in there.

2024-07-29 06:02 UTC, out-of-phaze approved these changes

2024-07-30 19:40 UTC, merged