Reworks bees and beehives.
NebulaSS13/Nebula pull request #4266
Opened 2024-07-28 12:24 UTC by MistakeNot4892

## Description of changes
- Reworks beehive frames into a general frame type that is filled with reagents, rather than a bespoke item subtype.
- Removes the existing beehive machinery and replaces it with `/obj/structure/apiary`, which is crafted directly from planks rather than using a bespoke parts item.
- Implements `/datum/extension/insect_hive` and `/decl/insect_species` to allow for nests to go on any structure, and contain a variety of insects with a variety of products.
- Implements bees using the above. Beehives will generate swarms, which will gather pollen (not currently modeled via reagent, just a counter) from nearby flowers, then return the pollen to the hive, where it will be used to fill a frame or create a comb.
- Swarms will need to be smoked before harvesting frames to avoid agitating the hive and getting stung.

## TODO
- [x] Rewrite beehive/implement apiary.
- [x] Implement and test frame filling/creating behavior.
- [x] Implement and test swarm behavior.
- [x] Add wasp and bee hives to dead trees.
- [x] Balance swarm growth and honey generation time.
- [x] Balance stinging.
- [x] Reimplement smoking.
- ~~Implement wasps venom and wasp stinging.~~

Ants and silkworms can come in another PR, this one needs to get finished.

## Why and what will this PR improve
Generalizes beekeeping in a way that allows for an expansion into other species (ants and wasps) and allows hives to be placed on arbitrary structures like dead trees or old closets.

## Authorship
Myself.

## Changelog
:cl:
add: Beekeeping has been rewritten almost entirely, please refer to the Beewrite PR on the GitHub repo for details.
/:cl:

2025-02-09 07:32 UTC, MistakeNot4892 commented
Depends on #4855 and #4846

2025-04-06 02:37 UTC, MistakeNot4892 commented
Not realistically going to finish the last 10% of this. It's functional other than balancing and reimplementation of smoking if someone wants to pick it up down the track.

2025-09-22 05:08 UTC, MistakeNot4892 commented
TODO:
- ~~Run through building a beehive, adding the frame, planting flowers, etc. and see how it feels and if it all works.~~
- ~~Test stinging behaviors and swarm aggression.~~
- ~~Test smokers.~~

2025-09-22 11:24 UTC, MistakeNot4892 commented
This is probably as good as it'll get for now. Swarm splitting would be nice to get working but this is a functional replacement for old bee mechanics.

2025-10-12 16:30 UTC, out-of-phaze commented on code/game/objects/structures/flora/plant.dm
> +	var/harvestable = 0
comment explaining that this is the number of harvests rather than a legacy bool (e.g. hasn't been changed to use `FALSE` instead of `0`) would be nice but isnt mandatory

2025-10-12 16:30 UTC, out-of-phaze commented on code/game/objects/structures/flora/plant.dm
> +	if(pollen < 10)
not a huge fan of bare constants like this, would prefer making it a member var or a local const like `var/const/max_pollen = 10` at the top of the proc. sometimes code like this gets copied around (e.g. someone wants to copy pollen behavior to their new custom type) and the original constant gets misused/misinterpreted. not mandatory though

2025-10-12 16:30 UTC, out-of-phaze commented on code/game/objects/structures/flora/plant.dm
> +	if(isnull(flower_variants))
noting that this will only ever contain roundstart plants, but that's probably desirable even if not explicitly made clear in the code

2025-10-12 16:30 UTC, out-of-phaze commented on code/modules/client/preference_setup/occupation/occupation.dm
> +				if(!user.skillset?.skills_transferable)
no longer necessary because of https://github.com/NebulaSS13/Nebula/pull/5150

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +/obj/effect/insect_swarm
a little curious why this is an effect and not a simple_animal. too much boilerplate you'd have to work around, i assume?parrots already do a similar species/type thing, so i figured it wouldn't be impossible, and mobs-as-effects has historically been a pain (see spiderlings for an example)

edit: oh it might be the merging? mob gc churn would be more annoying than doing the same with effects

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +		if(victim.isSynthetic())
another one for the list of 'isSynthetic uses to remove someday'. though i might as well ask: what is this meant to represent? is it "swarms won't target someone that isn't alive (because they don't exhale, aren't warm, aren't made of meat materials-wise, etc)" or "swarms can't sting someone if their stinger isn't strong enough to break the skin (e.g. if the skin is made of metal, stone, whatever)"?

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	//. = ..() // TODO work out why they're not automoving
noting this todo here, is it still the case?

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	//. = ..() // TODO work out why they're not automoving
ditto, is this TODO still current? was under the impression the PR has been ready to review for a bit

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +// TODO: lower agitation
are these work for a future PR or for this one?

2025-10-12 16:30 UTC, out-of-phaze commented on mods/content/beekeeping/items.dm
> +// TODO: consume reagents or charges? Unnecessary complexity?
> There are many options for beehive smoker fuel including cotton, bailing twine, pine needles, and wood chips. For best results, use fuel that produces cool, white smoke and avoid harsh smoke that can irritate bees.

seems pretty simple irl, just any flammable waste matter. i think the only thing that wouldnt work is lamp oil. actually it seems a useful thing irl for this is cardboard pellets/scraps which would work perfectly on a space map, probably?

2025-10-12 23:14 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +		if(victim.isSynthetic())
Both, I was thinking a bee swarm wouldn't identify a machine as alive and can't sting it. The sting proc does check can_inject so this could probably be relaxed.

2025-10-12 23:14 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	//. = ..() // TODO work out why they're not automoving
Yeah this is fixed, I just missed those. That actually explains why the automove isn't very snappy.

2025-10-12 23:15 UTC, MistakeNot4892 commented on mods/content/beekeeping/items.dm
> +// TODO: consume reagents or charges? Unnecessary complexity?
I guess I could use that general proc for burning materials and returning waste products, and make the smoker a container that can hold a stack. My concern is mostly that it will mean anyone who wants to do beekeeping now needs to source smoker fuel.

2025-10-12 23:26 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +// TODO: lower agitation
Missed this one, I'll hack out some sleepy states.

2025-10-12 23:28 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +/obj/effect/insect_swarm
The merging and also general health and processing behavior - I don't want you to be able to beat up a swarm with a baseball bat or inject it with a syringe like you can with mobs in general. That said, it would be nice to be able to put someone in control of a swarm of bees, and maybe swarm intensity could be handled via health or something, but... yeah.

2025-10-12 23:28 UTC, MistakeNot4892 commented on code/game/objects/structures/flora/plant.dm
> +	if(isnull(flower_variants))
Yeah I'll add a comment to make it clear.

2025-10-12 23:29 UTC, MistakeNot4892 commented on code/game/objects/structures/flora/plant.dm
> +	if(pollen < 10)
I'll add a define alongside the other pollen constants.

2025-10-12 23:30 UTC, MistakeNot4892 commented on code/game/objects/structures/flora/plant.dm
> +	var/harvestable = 0
I'll add a comment.

2025-10-13 00:29 UTC, out-of-phaze commented on mods/content/beekeeping/items.dm
> +// TODO: consume reagents or charges? Unnecessary complexity?
yeah, but 'cardboard cubes/pellets/etc comes in the beekeeping kit in cargo' would be an okay solution to that

2025-10-16 01:01 UTC, MistakeNot4892 commented on mods/content/beekeeping/items.dm
> +// TODO: consume reagents or charges? Unnecessary complexity?
Had a poke but I think I want to call this out of scope. We don't have a pellets stack and I don't really want to add one, add recipes, etc. As well as redoing the smoker to handle refuelling and such.

2025-10-18 11:18 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +// TODO: lower agitation
Done.

2025-10-18 11:19 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +		if(victim.isSynthetic())
This is removed, not sure why it's not showing up as out of date.

2025-10-18 11:42 UTC, MistakeNot4892 commented
- Automove is not working.
- ~~Pollen generation is wrong, it's adding 0.000003 per SSplants run instead of 0.2.~~ I thought it generating 12 per run was an error but nope SSplants is just on a massive wait.

2025-10-19 22:27 UTC, out-of-phaze requested changes

2025-10-19 22:27 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	movement_handlers = list(/datum/movement_handler/delay/insect_swarm)
```dm
/datum/movement_handler/delay/New(var/host, var/delay)
	..()
	src.delay = max(1, delay)
```
it's gonna get its delay set wrong bc of this inheritance, maybe `/delay` needs an isnull to avoid setting it if we pass null. that or just do `list(/datum/movement_handler/delay = 1 SECOND)`

2025-10-19 22:27 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	SHOULD_CALL_PARENT(FALSE)
```suggestion
	move_target = null
	. = ..()

/obj/effect/insect_swarm/can_do_automated_move(variant_move_delay)
	return !is_smoked()

/obj/effect/insect_swarm/start_automove(target, movement_type, datum/automove_metadata/metadata)
```

2025-10-19 22:30 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	movement_handlers = list(/datum/movement_handler/delay/insect_swarm)
I did do the latter already.

2025-10-19 22:33 UTC, out-of-phaze requested changes, later dismissed

2025-10-19 22:33 UTC, out-of-phaze commented on code/game/objects/items/devices/chameleonproj.dm
> +	movement_handlers = list(/datum/movement_handler/delay/chameleon_projector = list(2.5 SECONDS))
```suggestion
	movement_handlers = list(/datum/movement_handler/delay = list(2.5 SECONDS))
```
subtype no longer needed

2025-10-19 22:33 UTC, out-of-phaze commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	movement_handlers = list(/datum/movement_handler/delay/insect_swarm = list(1 SECOND))
```suggestion
	movement_handlers = list(/datum/movement_handler/delay = list(1 SECOND))
```
subtype no longer necessary

2025-10-19 23:18 UTC, MistakeNot4892 commented on code/game/objects/items/devices/chameleonproj.dm
> +	movement_handlers = list(/datum/movement_handler/delay/chameleon_projector = list(2.5 SECONDS))
Subtype needed for MayMove/DoMove.

2025-10-19 23:18 UTC, MistakeNot4892 commented on mods/content/beekeeping/hives/hive_swarm.dm
> +	movement_handlers = list(/datum/movement_handler/delay/insect_swarm = list(1 SECOND))
Subtype is needed for DoMove.

2026-04-24 01:49 UTC, MistakeNot4892 commented
Still need to fix automoving on this.

2026-05-13 11:36 UTC, MistakeNot4892 commented
Automove is now working, tyvm Penny.

Have also tweaked sting amount and sting pain as one sting put 100u of bee venom into me, so that should be more reasonable now.

2026-05-20 06:50 UTC, out-of-phaze submitted a review, later dismissed

2026-06-27 20:33 UTC, out-of-phaze approved these changes

2026-07-18 21:54 UTC, merged