Adding lockpicks.
NebulaSS13/Nebula pull request #4433
Opened 2024-09-04 07:10 UTC by MistakeNot4892

## Description of changes
Adds a set of lockpicks with high lockpicking effectiveness.

## Why and what will this PR improve
Currently the best lockpicking tool in the codebase is a stick or a metal rod.

## Authorship
Code by myself, base icon by Zirc.

## Changelog
Nothing player-facing.

2024-09-05 20:01 UTC, out-of-phaze reviewed
huh i kinda figured these would be a storage object. doesn't this mean the whole thing will just disintegrate when you fail to pick a lock?

2024-09-08 15:50 UTC, out-of-phaze requested changes

2024-09-08 15:50 UTC, out-of-phaze commented on code/game/objects/items/lockpicks.dm
> +/obj/item/lockpick_roll/filled/Initialize(ml, material_key)
this should be WillContain, shouldn't it?

2024-09-09 00:17 UTC, MistakeNot4892 commented on code/game/objects/items/lockpicks.dm
> +/obj/item/lockpick_roll/filled/Initialize(ml, material_key)
Oh true.

2024-09-09 01:50 UTC, out-of-phaze requested changes

2024-09-09 01:50 UTC, out-of-phaze commented on code/game/objects/items/lockpicks.dm
> +		icon_state = "[get_world_inventory_state()][use_icon_state]"
is there a reason this isn't just an `update_icon()` call?

2024-09-09 01:50 UTC, out-of-phaze commented on code/game/objects/items/lockpicks.dm
> +				var/image/pick         = new /image
might be better to just do an appearance copy?
```dm
				var/image/pick         = new /image
				pick.appearance = thing
				pick.appearance_flags |= RESET_COLOR
				pick.pixel_x = x_offset
```
also pick is a global proc (builtin, technically), not super certain about using it as a keyword :(

2024-09-09 02:24 UTC, MistakeNot4892 commented on code/game/objects/items/lockpicks.dm
> +				var/image/pick         = new /image
I did an appearance copy in the previous revision of this and it broke colouration and layering for some reason.

2024-09-09 02:24 UTC, MistakeNot4892 commented on code/game/objects/items/lockpicks.dm
> +		icon_state = "[get_world_inventory_state()][use_icon_state]"
There is a reason but I don't remember what it is.

2024-09-09 03:52 UTC, out-of-phaze approved these changes

2024-09-11 00:46 UTC, merged