Port missing fixes from Spacefarers
NebulaSS13/Nebula pull request #4530
Opened 2024-10-16 16:49 UTC by out-of-phaze

apparently i have like over a year of fixes i just never cherrypicked lmao
there will be another PR for dev-specific stuff

2024-10-16 23:11 UTC, MistakeNot4892 commented on code/modules/client/preference_setup/general/01_basic.dm
> +	W.write("spawnpoint", spawnpoint?.uid)
This is going to write nulls, which seems... bad.

2024-10-17 00:02 UTC, out-of-phaze commented on code/modules/client/preference_setup/general/01_basic.dm
> +	W.write("spawnpoint", spawnpoint?.uid)
i guess? it's worked fine on spacefarers, this was a really early change I just never mirrored. the alternative was runtiming

2024-10-17 00:56 UTC, MistakeNot4892 commented on code/modules/client/preference_setup/general/01_basic.dm
> +	W.write("spawnpoint", spawnpoint?.uid)
I would honestly say this should be sanitized elsewhere in prefs, it should use one of the map spawnpoints or something instead of keeping it null. Not a huge fan of writing nulls to the save file json.

2024-10-17 14:09 UTC, out-of-phaze commented on code/modules/client/preference_setup/general/01_basic.dm
> +	W.write("spawnpoint", spawnpoint?.uid)
but there *are* no spawnpoints for spacefarers, because there's no roundstart jobs

2024-10-17 23:04 UTC, MistakeNot4892 commented on code/modules/client/preference_setup/general/01_basic.dm
> +	W.write("spawnpoint", spawnpoint?.uid)
Yeah you explained on Discord.
As we discussed I do think it should just not write anything if there's no spawnpoint decl rather than writing a null.

2024-10-18 07:30 UTC, MistakeNot4892 requested changes
Please change the spawn point pref saving to just skip if there's no spawnpoint decl, otherwise this is good to merge.

2024-10-19 03:12 UTC, MistakeNot4892 approved these changes

2024-10-20 02:29 UTC, merged