Port missing dev branch fixes from Spacefarers
NebulaSS13/Nebula pull request #4531
Opened 2024-10-16 18:05 UTC by out-of-phaze

Same as #4530 but for stuff that has to go to dev.

2024-10-16 22:59 UTC, MistakeNot4892 commented on code/modules/reagents/chems/chems_blood.dm
> +	return blood_data["blood_color"] || ..()
Data is lazylisted isn't it?

2024-10-16 23:56 UTC, out-of-phaze commented on code/modules/reagents/chems/chems_blood.dm
> +	return blood_data["blood_color"] || ..()
? yeah? so if it's null we want to return parent

2024-10-17 00:55 UTC, MistakeNot4892 commented on code/modules/reagents/chems/chems_blood.dm
> +	return blood_data["blood_color"] || ..()
So if it's null this will runtime.

2024-10-18 07:31 UTC, MistakeNot4892 requested changes
Please amend the blood data check to use LAZYACCESS() to avoid a null runtime, otherwise this PR is good to merge.

2024-10-19 03:13 UTC, MistakeNot4892 approved these changes

2024-10-20 02:29 UTC, merged