[MDB IGNORE] Moving broken/burned icons onto the flooring decl.
NebulaSS13/Nebula pull request #4555
Opened 2024-11-10 05:58 UTC by MistakeNot4892

Allows flooring decls to validate or override broken/burned states on a per-icon basis. Needs testing.

2024-11-11 01:52 UTC, MistakeNot4892 commented
Tested via explosion and fire on Tradeship.

2024-11-12 02:09 UTC, out-of-phaze commented
> Tested via explosion and fire on Tradeship.

was it tested with wood floor tiles? previously it only worked for tile

2024-11-12 02:14 UTC, MistakeNot4892 commented
It's only set up on plating and tiles. Wood etc don't have broken states defined currently and will need them added.

2024-11-12 06:36 UTC, out-of-phaze requested changes

2024-11-12 06:36 UTC, out-of-phaze commented on code/unit_tests/turf_icons.dm
line 18, `if(istype(floor))` should be `if(istype(floor, floor_type))` and also `var/turf/floor/check_floor` might just need to be `var/turf/check_turf` tbh... actually that var is unnecessary it should just do `if(TYPE_IS_ABSTRACT(floor_type))` shouldn't it

2024-11-12 07:40 UTC, out-of-phaze submitted a review, later dismissed

2024-11-12 16:39 UTC, out-of-phaze approved these changes

2024-11-14 00:08 UTC, merged