Vendor and smartfridge cleanup.
NebulaSS13/Nebula pull request #4578
Opened 2024-11-22 11:21 UTC by MistakeNot4892

## Description of changes
This should possibly be going to dev, but despite the footprint, is not really a significant code change.
- Breaks up vending.dmi.
- Moves smartfridges into their own folder.
- Makes smartfridges and vendors use add_overlay().
- Cleans up smartfridge/vendor icon updates.
- Adds required states for bar fridges, drying ovens and nutrimax.
- Adds unit tests for vendor and smartfridge icons/overlays.

## Why and what will this PR improve
- Fixes https://github.com/ScavStation/ScavStation/issues/1127
- Tests vendors and smartfridges in CI.
- Conceptually separates vendors and smartfridges.
- Allows easily moving vendor/smartfridge icons into modpacks.

## Authorship
Myself.

## Changelog
Nothing player-facing.

2024-11-22 12:45 UTC, out-of-phaze submitted a review, later dismissed
fwiw i'm pretty sure icondiffbot can handle a PR of this size just fine? i can double-check though

2024-11-22 12:45 UTC, out-of-phaze commented on code/game/machinery/smartfridge/foods.dm
> +	if(istype(O,/obj/item/food) || istype(O,/obj/item/utensil))
should maybe add soup bowls to this? could even check that they have reagents in them

2024-11-22 12:45 UTC, out-of-phaze commented on code/game/machinery/vending/_vending.dm
> +	icon_state = ICON_STATE_WORLD
I really don't get the point of using `ICON_STATE_WORLD` for non-objects. An inventory or worn sprite is never valid here. It's not like vendors are the only things that do this, obviously, but still, I don't rrrrrrrrreally get it?

2024-11-22 12:45 UTC, out-of-phaze commented on code/unit_tests/time_tests.dm
> +	name = "TIME: Shall not validate range that exlude 6th of June - Start before End"
while you're at it there's a typo here and on line 66, `exlude` :)

2024-11-22 21:30 UTC, MistakeNot4892 commented on code/game/machinery/vending/_vending.dm
> +	icon_state = ICON_STATE_WORLD
Main benefit is not having to set icon_state on subtypes, using `world` just tickles the consistency part of my brain.

2024-11-22 23:14 UTC, out-of-phaze requested changes

2024-11-22 23:14 UTC, out-of-phaze commented on code/game/machinery/smartfridge/foods.dm
> +	return istype(O) && O.reagents?.total_volume && is_type_in_list(O, _food_types)
this requires that utensils have reagents in them

2024-11-23 00:53 UTC, out-of-phaze approved these changes

2024-11-23 02:55 UTC, MistakeNot4892 commented on code/game/machinery/smartfridge/foods.dm
> +	return istype(O) && O.reagents?.total_volume && is_type_in_list(O, _food_types)
I don't really know why the hot foods fridge needs to take utensils, honestly.

2024-11-23 22:36 UTC, merged