Stubs and getters/setters for atom fires.
NebulaSS13/Nebula pull request #4645
Opened 2024-12-15 04:40 UTC by MistakeNot4892

Procs/varname changes to support #4644

2024-12-16 22:00 UTC, out-of-phaze requested changes, later dismissed
i feel like "does this have the ability to be lit, a la lighters" and "is the material this is made of *on fire?*" should be separate, conceptually, but I'm not hard tied to that

2024-12-16 22:00 UTC, out-of-phaze commented on code/game/machinery/igniter.dm
> +/obj/machinery/igniter/proc/create_sparks()
this doesn't actually produce sparks at all

2024-12-16 22:00 UTC, out-of-phaze commented on code/game/objects/items/flame/_flame.dm
> +		loc.ignite_fire()
could put an icon update in sconces' ignite_fire?

2024-12-16 22:00 UTC, out-of-phaze commented on code/game/objects/items/flame/_flame.dm
> +/obj/item/flame/extinguish_fire(mob/user, no_message = FALSE)
not sure how to feel about this. i feel like a lighter should be able to catch fire separately from it being on/off or lit/unlit? idk

2024-12-16 22:33 UTC, MistakeNot4892 commented on code/game/machinery/igniter.dm
> +/obj/machinery/igniter/proc/create_sparks()
Oh true, I assumed. Will rename it to `toggle_igniter` or something.

2024-12-16 22:36 UTC, MistakeNot4892 commented on code/game/objects/items/flame/_flame.dm
> +		loc.ignite_fire()
This actually might cause a recursion issue if the sconce then tries to light the torch again.

2024-12-16 22:39 UTC, MistakeNot4892 commented on code/game/objects/items/flame/_flame.dm
> +/obj/item/flame/extinguish_fire(mob/user, no_message = FALSE)
I wanted to condense all the procs but I was iffy on this too, I'll give it its own proc.

2024-12-16 23:00 UTC, MistakeNot4892 commented on code/game/objects/items/flame/_flame.dm
> +		loc.ignite_fire()
Looks like sconces don't try to light their contents via that proc so should be fine.

2024-12-17 11:24 UTC, out-of-phaze approved these changes

2024-12-18 13:59 UTC, merged