Fixing organs not burning in fires.
NebulaSS13/Nebula pull request #4669
Opened 2024-12-22 07:02 UTC by MistakeNot4892

Organs will now burn to ash on a fire.

2024-12-22 22:30 UTC, MistakeNot4892 commented
Temperature damage is stupid.

2024-12-24 17:24 UTC, out-of-phaze requested changes

2024-12-24 17:24 UTC, out-of-phaze commented on code/modules/materials/_material_stack.dm
> +	return istype(loc, /obj/structure/fire_source) ? FALSE : ..()
does nothing to stop molds taking damage when you fire them in a kiln

2024-12-24 19:24 UTC, MistakeNot4892 commented on code/modules/materials/_material_stack.dm
> +	return istype(loc, /obj/structure/fire_source) ? FALSE : ..()
Molds generally don't have an ignition temperature, these changes shouldn't impact them.

2024-12-25 22:21 UTC, MistakeNot4892 commented on code/modules/materials/_material_stack.dm
> +	return istype(loc, /obj/structure/fire_source) ? FALSE : ..()
Per Discord, I'm not sure what change is being requested here. I haven't adjusted the behavior for materials like clay that don't solely have an ignition point.

2024-12-25 22:23 UTC, out-of-phaze approved these changes
as i explained on discord i misunderstood

2024-12-26 23:47 UTC, merged