Compiled tweaks from old codex dump branch.
NebulaSS13/Nebula pull request #4681
Opened 2024-12-27 22:42 UTC by MistakeNot4892

Cleaning up old branches, there were a couple of small changes in my working copy that I missed when I got it merged to main apparently.

2024-12-27 23:34 UTC, out-of-phaze requested changes
well i sure *hope* they've been compiled! (joke)

2024-12-27 23:34 UTC, out-of-phaze commented on code/game/objects/items/weapons/policetape.dm
> +			var/obj/structure/tape_barricade/B = locate(/obj/structure/tape_barricade, target_turf)
```suggestion
			var/obj/structure/tape_barricade/B = locate(/obj/structure/tape_barricade) in target_turf
```
uhhhh. i don't know if the original syntax is valid or not but it definitely gives me the heebie-jeebies. please change it and i will get around to changing the other cases of this also

2024-12-27 23:42 UTC, MistakeNot4892 commented on code/game/objects/items/weapons/policetape.dm
> +			var/obj/structure/tape_barricade/B = locate(/obj/structure/tape_barricade, target_turf)
It's valid syntax, but I'll tweak it.

2024-12-28 19:15 UTC, out-of-phaze approved these changes

2024-12-29 23:21 UTC, merged