Removes spawn() count check from check-paths.sh.
NebulaSS13/Nebula pull request #532
Opened 2020-05-20 17:54 UTC by MistakeNot4892

The only time this comes up is when people are removing spawn and it decides to conflict or start failing random PRs post-merge. We can check for spawn use in review, we don't need to make builds fail because they removed one.

2020-05-20 17:55 UTC, Lohikar submitted a review, later dismissed

2020-05-20 17:56 UTC, deathride58 submitted a review, later dismissed
The check causes more trouble than it's worth. +support

2020-05-20 18:02 UTC, comma commented
Make it less than check rather than exact, would be looser but still there and someone bored can update count every so often

2020-05-20 18:04 UTC, MistakeNot4892 commented
Being discussed on Disco

2020-05-21 07:51 UTC, comma submitted a review, later dismissed

2020-05-24 22:53 UTC, Lohikar requested changes
Per maint-poll, pls just delete entirely.

2020-05-24 23:21 UTC, Lohikar approved these changes

2020-05-25 01:02 UTC, merged

2020-05-25 05:52 UTC, PsiOmegaDelta commented
Does mean that one PR could remove spawns and another could sneak new ones in if missed in a review

2020-05-25 09:20 UTC, comma approved these changes
I hate democracy