Fixes the mining processor.
NebulaSS13/Nebula pull request #811
Opened 2020-08-20 20:08 UTC by MarinaGryphon

Mining processor would previously make duplicate entries due to lacking a text2path. It would create a duplicate entry for `"/decl/material/solid/mineral/hematite"` in addition to the actual entry for `/decl/material/solid/mineral/hematite`.
Fun fact: `new "/decl/material/solid/mineral/hematite"()` apparently works, meaning it created a whole new decl, which is how it was able to get info like the proper `solid_name`.

I'll change check-paths.sh soon, I swear.

2020-08-20 20:08 UTC, MarinaGryphon commented
Oh, I also changed the name of `orename` to `orepath` to make it more clear that it uses a typepath, not a material name. That misconception made it much harder to track down this bug. I can revert it if needed though.

2020-08-20 20:10 UTC, MarinaGryphon commented
Oh, and no matter what this will require upping the number of `text2path`s to 20, that's unavoidable. But it would technically, maybe, be cleaner to do it in get_decl, depending on the overhead added by such? If this is an issue elsewhere it would also fix that as well.

2020-08-20 20:19 UTC, MarinaGryphon commented
Fixes #812.

2020-08-20 20:51 UTC, PsiOmegaDelta requested changes

2020-08-20 20:51 UTC, PsiOmegaDelta commented on code/modules/mining/machinery/mineral_processor.dm
> +		ores_processing[text2path(href_list["toggle_smelting"])] = choice
There is no need to text2ref. Pass the ref of the decl instance to the UI, instead of its path, and `locate()` the instance

2020-08-20 20:52 UTC, MarinaGryphon commented on code/modules/mining/machinery/mineral_processor.dm
> +		ores_processing[text2path(href_list["toggle_smelting"])] = choice
Uuuuuuuuuuuuuuuuuuuuuuuuh is that worth it? I feel like maybe a better option altogether would be just using text2path in get_decl to avoid this issue cropping up ever again

2020-08-20 20:52 UTC, PsiOmegaDelta commented on code/modules/mining/machinery/mineral_processor.dm
> +		ores_processing[text2path(href_list["toggle_smelting"])] = choice
Or pass the ref of the path and locate that, if that's what the `ores_processing()`-proc expects, is just a bit redundant.

2020-08-20 21:02 UTC, PsiOmegaDelta commented on code/modules/mining/machinery/mineral_processor.dm
> +		ores_processing[text2path(href_list["toggle_smelting"])] = choice
text2path is easier to exploit and has been known to fail to find types despite the string matching.
\ref + locate() is simply more robust.

2020-08-20 21:35 UTC, MistakeNot4892 commented on code/modules/mining/machinery/mineral_processor.dm
> +		ores_processing[text2path(href_list["toggle_smelting"])] = choice
Agree with Psi. `get_decl` is hot code additionally, adding checking there for behavior that is almost always a coder mistake is not a good idea.

2020-09-03 18:04 UTC, MistakeNot4892 commented
This should now be redundant in view of the mining rewrite.

2020-09-03 23:41 UTC, MistakeNot4892 commented
Going to close this for now, feel free to reopen if the issue needs further addressing and you update the PR.

2020-09-03 23:41 UTC, closed without merging