several hooks will now update higher z-levels
NebulaSS13/Nebula pull request #905
Opened 2020-09-15 04:05 UTC by ZirconiumWit

setname and setinvisibility will now update when viewing a scene from higher z-levels.

2020-09-16 16:52 UTC, PsiOmegaDelta approved these changes, later dismissed

2020-09-16 16:56 UTC, PsiOmegaDelta approved these changes, later dismissed

2020-09-16 17:16 UTC, Lohikar requested changes
Shoulda said originally, but please use `UPDATE_OO_IF_PRESENT` (no parens) instead of `update_above()` - it'll skip the proc-call entirely for unmimicked atoms.

2020-09-16 17:30 UTC, Lohikar commented
Fixes #893.

2020-09-18 01:07 UTC, ZirconiumWit commented
Changed to UPDATE_OO_IF_PRESENT and reverted upon determining that this was not an effective approach to the problem.

2020-09-18 01:08 UTC, Lohikar approved these changes

2020-09-18 02:54 UTC, merged