Assorted wizard fixes
NebulaSS13/Nebula pull request #917
Opened 2020-09-17 08:19 UTC by eckff

2020-09-18 02:50 UTC, MistakeNot4892 commented on code/modules/spells/general/area_teleport.dm
> +	return targets && islist(targets) && targets.len > 0
`islist(targets) && length(targets)`

2020-09-18 02:50 UTC, MistakeNot4892 commented on code/modules/spells/spell_code.dm
> +	var/duration = 0 				//how long the spell lasts
ree indenting with tabs >:

2020-09-18 02:51 UTC, MistakeNot4892 commented on code/modules/spells/spell_code.dm
> +		to_chat(user, SPAN_WARNING("[name] fizzles. There are no valid targets nearby."))
Would `\The [name]` be appropriate here and above in case a spell is not a proper noun?

2020-09-18 02:53 UTC, MistakeNot4892 commented on code/modules/spells/targeted/projectile/dumbfire.dm
> +	selection_type = "range"
Any chance you can change the "range" "view" etc values to macros?

2020-09-18 02:55 UTC, MistakeNot4892 requested changes, later dismissed
See comments.

2020-11-15 11:09 UTC, comma approved these changes

2020-11-19 22:20 UTC, merged